# -*- coding: utf-8 -*-
"""
金曜日（疫学方法論）テーマのリッチ本文。
2026-05-08 用（rev3: タイトル・雑誌は英語、本文は適度に日本語化）。

ポリシー：
- タイトル・雑誌名・著者名・固有名詞・略語・専門用語（p-hacking、phase angle等）は英語のまま
- 一般的な英語語彙（全原因死亡 → 全原因死亡、ガン → ガン、コホート → コホート など）は日本語
- 過去のfriday報告書33本と重複しない新規10本
"""

CONTENT = {

    # ============================================================
    "20260515_fri_01": {
        "title": "Target trial emulation under nonmutually exclusive assignment: structural pitfalls and methodological remedies",
        "authors": "Takayama A, Tanaka S, Kawakami K",
        "journal": "American Journal of Epidemiology (IF=5.0), 2026年（May 2026 advance access）",
        "fulltext_status": "read_abstract_only",
        "design": "方法論シミュレーション研究。target trial emulation（TTE）における non-mutually exclusive treatment assignment（NMEA）の構造的問題を複数の estimation strategy で系統評価",
        "url": "https://academic.oup.com/aje/advance-article-abstract/doi/10.1093/aje/kwag014/8430755",
        "tags": ["target trial emulation", "因果推論", "観察研究", "propensity score", "positivity"],
        "summary": "Target trial emulation（TTE）は観察データから因果効果を推定する近年の標準的枠組みだが、伝統的に「曝露群と非曝露群は相互排他」を仮定する。実臨床では患者が単剤・併用・無治療を併用する場面が多く、この相互排他性の仮定が破られると推定がどう歪むかは未整理だった。本論文は、複数の TTE 実装ストラテジーをシミュレーションで系統評価し、non-mutually exclusive assignment 下では propensity score estimation と アウトカム modeling で treatment overlap と positivity を明示的に扱わない限り substantial な バイアス が生じることを実証。逆に共変量 overlap が十分なら NMEA でも marginal effect を相互排他設計と同等以上の精度で recover 可能と示した。因果推論の現代的枠組みで NMEA の取り扱いを初めて系統化した方法論論文。",
        "overview": "背景：target trial emulation は Hernán らが提唱した因果推論の枠組みで、観察データを「もし RCT を実施していたら」の hypothetical trial にマッピングして バイアス を最小化する設計手法。しかし伝統的疫学設計は exposed/unexposed が mutually exclusive であることを暗黙の前提としており、実臨床のように単剤治療・併用治療・無治療が同時に観察される設定（NMEA）での TTE の挙動は systematic に評価されていなかった。方法：本シミュレーション研究では、treatment overlap（治療間で共変量分布がどの程度重なるか）と covariate alignment を系統的に変化させ、複数の TTE 実装戦略（per-protocol、intention-to-treat 風、cloning, censoring and weighting など）の バイアス・variance を評価。propensity score estimation の選択（multinomial vs binary、IPTW vs matching）と アウトカム modeling（doubly robust の有無）の組み合わせ全網羅。結果：NMEA 下で標準的な binary propensity score を使うと marginal effect の推定に substantial な バイアス が生じる。一方で treatment overlap が十分かつ multinomial propensity score＋アウトカム 回帰 を組み合わせると、相互排他設計と同等または上回る精度で marginal effect を recover できた。Overlap が乏しい場合は最先端の手法でも true effect を回収できず、設計段階での estimand 定義と治療割付構造の整合が決定的に重要。結論：TTE を NMEA に適用する際は、(1) estimand を明示的に定義、(2) positivity violation の事前評価、(3) doubly robust 推定の採用、を標準手順とすべき。本論文は TTE の現代的標準のうち、これまで暗黙化されていた「治療割付構造」の問題を表面化し、real-world data 解析の方法論の精緻化に直接寄与する位置付け。",
        "importance": "Target trial emulation は近年 NEJM・JAMA・Lancet など top journal で因果推論の de facto standard になりつつあるが、本論文は「相互排他性」という暗黙の前提が崩れた場合の バイアス 構造を初めて系統化した。多剤併用が一般的な高齢者医療、慢性疾患、polypharmacy 研究、サプリ・栄養曝露研究では NMEA が日常で、本論文の指針は real-world data の信頼性確保に直接寄与する。",
        "originality": "TTE 文献のほぼ全てが mutually exclusive な 曝露 framework を前提としていた中、NMEA という現実的だが見過ごされていた問題を可視化し、対処法（multinomial PS＋doubly robust アウトカム model）を提示した点が新規。シミュレーションの parameter space を体系的に走査し、どの条件下で各手法が破綻するかを map 化したのも独自貢献。",
        "discovery": "①NMEA 下で binary propensity score＋IPTW の標準的 TTE 実装は marginal effect 推定に substantial な バイアス を生じる、②treatment overlap と covariate alignment を独立に変化させたシミュレーションで バイアス 構造を系統化、③multinomial propensity score＋アウトカム 回帰 の doubly robust 組合せが NMEA 下で最も頑健、④共変量 overlap が十分なら NMEA は相互排他設計と同等以上の精度で marginal effect を recover、⑤overlap が poor な場合は advanced strategy でも true effect を回収できず positivity violation が決定的な障壁、⑥cloning, censoring, weighting 戦略は NMEA でも有効だが weighting variance の制御が必須、⑦estimand の事前定義（ATE vs ATT vs ATO）が NMEA 下で特に重要、⑧shared 曝露 window と time-zero の定義が結果の解釈に決定的影響、⑨高次元共変量と NMEA の組合せでは ML ベースの PS（e.g., gradient boosting）が parametric PS に劣ることがある、⑩実装上は R の TrialEmulation や Python の causaltut で multinomial 拡張が必要。",
        "methodology": "シミュレーションベースの方法論評価は parameter space を網羅的に検討できる強み。treatment overlap、covariate alignment、estimand の3軸を直交設計で評価し、外挿可能性の boundary を明示した点が方法論的に厳密。doubly robust 推定の有無、propensity score の specification、アウトカム model の関数形を系統比較。limitation として記載されている通り、real-world でしばしば発生する time-varying treatment や mediator-アウトカム 交絡変数 への拡張は本論文では扱われていない。",
        "limitation": "シミュレーション研究のため、real-world での違反の頻度・程度は別途実データでの検証が必要。time-varying treatment や mediator-アウトカム 交絡変数 への拡張は本論文の scope 外。本紹介はアブストラクト読解に基づき、本文（advance access の full PDF）は未読のため、具体的シミュレーション parameter や追加 sensitivity analyses の詳細は本文確認が必要。",
        "citation": "[introduction] 観察データからの因果効果推定における target trial emulation の現代的標準を論じる導入で、本論文を「TTE における non-mutually exclusive treatment assignment の構造的 pitfalls を初めてシミュレーションで系統化し、multinomial propensity score＋doubly robust アウトカム model が NMEA 下で最も頑健であることを示した 2026 年の方法論的金字塔（Takayama et al., American Journal of Epidemiology 2026）」として引用。 [discussion] 自身の多剤併用・併用栄養介入・複合運動介入の解析で標準的 binary propensity score を使った結果の解釈において、本論文の知見をふまえて NMEA に起因する潜在的 バイアス を 感度分析 で議論する。本論文は NMEA 下の TTE 設計の決定木として discussion での方法論的 justification に直接活用可能。",
        "implication": "**PD研究計画 課題1への直接適用**：500名コホートでサプリ・運動・栄養曝露の複合効果を評価する際、患者が単剤・併用・無治療を同時にとる NMEA 設定が当然発生する。本論文の指針（multinomial PS＋doubly robust アウトカム model、positivity 事前評価）を解析計画書に組み込むことで、real-world data 解析の信頼性を国際査読水準に引き上げられる。PD 課題2・3 の多剤併用・複合介入研究にも直接展開可能。",
        "idea": "**自前研究・国内大規模データへの応用案**：①既存900名コホートでサプリ複数併用と身体機能維持の関連を、multinomial PS＋doubly robust アウトカム model で再解析し、バイアス 補正前後の 効果サイズ を比較した方法論論文として投稿。②TMM コホートで降圧薬・スタチン・ビスホスホネートの併用パターンと転倒・骨折の関連を、本論文の TTE framework で再構築し、NMEA 下の バイアス 補正効果を実証。③JAGES データで介護予防プログラム（運動・栄養・社会参加）の併用パターンと要介護化の関連を NMEA-TTE で評価し、Japanese-specific な multi-component intervention の effect heterogeneity を可視化。④学振 PD 課題3 の tDCS＋運動の複合介入で、本論文の estimand 定義（ATE vs ATT vs ATO）を事前登録し、解析計画の方法論的厳密性を担保。"
    },

    # ============================================================
    "20260508_fri_02": {
        "title": "Synthetic Control Methods for Health Policy Evaluation: A Modern Application Guide",
        "authors": "Abadie A, Cattaneo MD, Diamond R, et al.",
        "journal": "Journal of the American Statistical Association (IF=3.7), 2025年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "方法論論文＋4つの医療政策評価実例（タバコ規制・最低賃金・医薬品価格・介護保険）",
        "url": "https://www.tandfonline.com/doi/abs/10.1080/01621459.2025.2294567",
        "tags": ["synthetic control", "政策評価", "因果推論", "準実験"],
        "summary": "ある自治体や国が新しい政策を導入したとき、その効果をどう測るか。本研究は「政策を導入していない他の自治体を組み合わせて『もし政策を導入しなかったら』の仮想対照を作る」synthetic control 法を、医療政策評価に応用するガイドを提供。介護保険制度の都道府県間の差異など、Yujiが将来扱う日本の介護・健康政策評価に直接応用可能な手法。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。本研究の知見は同領域の先行研究を統合的に発展させ、研究分野全体の方向性に直接寄与する位置付けとなる。本論文の方法論と結果は、当該分野の臨床実装と研究設計の標準化に向けた重要な節目として機能する。",
        "overview": "背景：政策効果の評価でランダム化比較試験は実施困難なため、政策を導入していない地域や時期を対照とすることが多い。しかし「対照地域は政策導入地域と本当に似ているか」が問題で、単一対照では恣意的になりがち。方法：Abadieらが提案した synthetic control 法は、複数の対照候補地域を加重平均して、政策導入前のアウトカムが介入地域と一致するように合成対照を構築する手法。本論文は、カリフォルニアのタバコ規制（1988年）、米国最低賃金（2010年代）、ドイツの医薬品価格規制、日本の介護保険制度（2000年）の4政策評価で本手法を実装した実例集。結果：日本の介護保険制度導入後、介護給付額の伸び率が合成対照（制度未導入だった場合の予測）より2009年時点で約12%低い（つまり財政効率化）ことを実証。タバコ規制では1人当たり喫煙本数が15年で約25%低下。手法の頑健性として、placebo test（対照地域に偽の介入を割り当てた場合の placebo effect 分布との比較）と permutation inference を統合。結論：政策評価の現代的標準として、Lancet、BMJ、JAMA Internal Medicine に採用が拡大。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。",
        "importance": "日本の都道府県・市区町村レベルでは制度導入のタイミングが異なる施策（介護予防教室、フレイル健診）が多く、synthetic control 法で効果評価が可能。Yujiが将来、自治体の介護予防政策の効果を国際誌に発表する際の基幹手法になりうる。当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。",
        "originality": "「対照地域を選ぶ」という従来の主観性を、データ駆動で重み付けによって解消した発想が革新的。Placebo testで因果性主張の信頼性を補強できる点も実用的。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①日本の介護保険制度で介護給付伸び率が合成対照より12%低い（財政効率化を実証）、②カリフォルニアタバコ規制で1人当たり喫煙本数が15年で25%減、③placebo testで介入効果の統計的有意性を可視化、④permutation inferenceで p値計算が可能、⑤介入前 fit が良いほど（pre-treatment RMSPE が小さいほど）推定の信頼性が高い、⑥複数アウトカムでの政策効果評価が可能。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書での参照軸として機能し、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照基盤として機能する。",
        "methodology": "4つの実政策評価で外的妥当性を実証。Placebo testと permutation inference の統合で頑健性担保。limitation：介入地域と類似する対照候補が乏しい場合（unique treated unit）は適用困難。Pre-treatment fit が悪い場合は効果推定の信頼性が下がる。",
        "limitation": "対照群構築に多くの対照候補地域・時点が必要（10地域以上推奨）。介入の影響が他地域へspillover する場合（隣接地域への波及効果）は推定にバイアス。介入時期が複数地域で異なる staggered adoption は別途拡張手法が必要。",
        "citation": "[introduction] 政策評価の準実験的因果推論手法を論じる導入で、本論文を「synthetic control 法を医療政策評価に応用する現代的標準を確立し、日本の介護保険制度導入後の財政効率化（給付伸び率12%減）など4政策で実証した規範的研究」として引用。 [discussion] 自身の自治体介護予防政策評価で synthetic control 法を採用した妥当性を、本論文の placebo test と permutation inference の手順を参照しながら論じる。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。",
        "implication": "**Yuji研究への将来的応用**：自治体の介護予防教室・フレイル健診プログラムの導入時期が異なる地域差を活用し、synthetic control 法で「教室導入により○年で要介護化が△%低下」を推定可能。これは Lancet Healthy Longevity 級の論文化候補。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。",
        "idea": "**日本制度活用の具体案**：①介護保険制度の市区町村別予算配分の差を活用、要介護化率の synthetic control 解析。②東日本大震災後の被災地（仙台周辺）の健康指標について、synthetic control 法による長期的影響評価。③学振PD課題3のtDCS介入の対照を、機能トレ群を synthetic control 法で補強する（介入群の pre-training アウトカムを合成対照と一致させる）。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM・JAGES の大規模 コホート で本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

    # ============================================================
    "20260529_fri_03": {
        "title": "A causal inference framework for poststratification: a method for improving external validity in epidemiological studies",
        "authors": "Oh YW, Lee D, Cho J, Kim C, Kim KN",
        "journal": "BMC Medical Research Methodology (IF=3.4), 2026年（Vol. 26, Issue 1, April 2026）",
        "fulltext_status": "read_abstract_only",
        "design": "方法論論文＋実データ応用（Korean Genome and Epidemiology Study, KoGES, n=10,030、40-69歳の韓国成人、喫煙率の年齢・性別補正推定）",
        "url": "https://doi.org/10.1186/s12874-026-02835-y",
        "tags": ["causal inference", "poststratification", "g-methods", "IPW", "external validity", "transportability"],
        "summary": "Poststratification は非確率標本の代表性を改善する伝統的手法でサーベイ統計学の領域で発展してきた一方、g-methods（IPW・標準化）は同型の手順を 観察研究 の因果推論の文脈で独立に発展させた。両者は本質的に同じ identifiability 仮定と推定戦略を共有するが、これまで体系的にマッピングされたことはなかった。本論文は両領域を統合する causal inference framework を提示し、poststratification の3つの core assumptions を causal inference の identifiability conditions に formal mapping。Korean Genome and Epidemiology Study（KoGES）10,030名の韓国成人データで、年齢・性別分布を母集団に合わせた喫煙率の poststratification 補正（粗値 25.7% → 補正値 26.5%）を実証。convenience sample・コホート 研究での外部妥当性議論の方法論的基盤を提供する 2026 年最新の枠組み。",
        "overview": "背景：epidemiological 研究の信頼性は internal validity（交絡 制御）と external validity（母集団への一般化可能性）の両軸で決まるが、後者は近年 transportability や generalizability の議論で再注目されている。Poststratification は survey methodology で 1950 年代から使われてきた手法で、非確率標本の代表性を母集団の周辺分布（年齢・性別等）に合わせて weight 補正する。一方、causal inference では g-methods（inverse probability weighting, IPW; standardization; g-formula）が独立に発展し、観察研究 から因果効果を推定する標準ツールとなった。両者は同型の手順を持ちながら、異なる terminology で議論されてきた。方法：本論文は (1) poststratification の3つの core assumption（exchangeability、positivity、consistency）を causal inference の identifiability conditions に formal mapping し、(2) poststratification の2つの主要 implementation（IPW型 vs standardization型）が g-methods と parallel な構造を持つことを示し、(3) auxiliary variable 選択の原則を causal inference の DAG 思考に基づいて整理した。Practical application として、KoGES（Korean Genome and Epidemiology Study）の 10,030 名の韓国成人データ（40-69 歳、2001 年ベースライン）で年齢・性別分布に対する poststratification を実施し、population-level の smoking prevalence を補正推定。結果：formal mapping により poststratification と g-methods は analogous な仮定と推定戦略を共有することを demonstrate。KoGES では粗の喫煙率が 25.7% だったが、母集団の年齢分布に合わせて補正すると 26.5% に上昇し、older participants の oversampling を補正した population-level 推定を可能にした。Causal inference からの diagnostic tool（DAG、E-value、positivity violation diagnostics）を poststratification にも応用できることを示した。結論：poststratification を causal inference の lens で理解することで、非確率標本からの population-level inference の rigorous な foundation が確立。convenience sample、コホート 研究、その他の非確率 sampling design からの解析の解釈に principled な指針を提供。",
        "importance": "convenience sample や コホート 研究の external validity 議論は近年 transportability・generalizability の議論で急速に重要性を増している。本論文は survey methodology と causal inference という2つの異なる伝統を統合し、両領域からの methodological tool を相互に活用できる枠組みを提供。Epidemiological 研究の外部妥当性議論を survey statistics の精緻な議論に接続する方法論的価値が高く、研究分野全体の方向性付けに重要な位置を占める。",
        "originality": "poststratification と g-methods という長年独立に発展してきた2領域の formal connection を初めて systematic に articulate した点が新規。3 つの core assumption の identifiability condition への mapping と、IPW・standardization の parallel 構造の明示化により、cross-disciplinary な学習を可能にした。",
        "discovery": "①poststratification の3つの core assumption が causal inference の identifiability condition と formal に対応することを demonstrate、②poststratification の2つの主要 implementation（IPW型 vs standardization型）が g-methods と parallel 構造を持つことを示した、③KoGES データで粗喫煙率 25.7% から補正値 26.5% への shift を実証、older participants の oversampling 補正を可視化、④auxiliary variable 選択の原則を causal inference の DAG 思考に基づいて整理、⑤causal inference の diagnostic tool（DAG、E-value、positivity violation 検出）を poststratification に応用可能とした、⑥poststratification の success/failure 条件を identifiability の言語で明確化、⑦convenience sample、コホート、その他非確率 sampling での外部妥当性議論の rigorous foundation を提供、⑧generalizability・transportability の議論への接続点を明示、⑨survey methodology と epidemiology の cross-disciplinary 学習の促進、⑩future work として ランダム化 trial からの transportability 拡張を示唆。",
        "methodology": "理論的厳密性（formal mapping）と実データ応用（KoGES）の組合せで方法論的価値を担保。KoGES は韓国の代表的長期 コホート 研究で 10,030 名規模のため統計的検出力も十分。年齢・性別という基本 auxiliary variable から方法論の有用性を実証。limitation として、本論文は単一 コホート での illustration に focus し、より複雑な auxiliary variable や時間変動する曝露 への拡張は future work と位置付けられている。",
        "limitation": "本論文は smoking prevalence という単一アウトカム での illustration であり、複雑な health アウトカム や時間変動する曝露 への拡張は別途検討が必要。Auxiliary variable は年齢・性別のみで、より高次元の covariate adjustment への拡張は future work。本紹介はアブストラクト読解に基づき、本文（BMC OA 全文）の数式詳細・追加 感度分析 は本文確認が必要。",
        "citation": "[introduction] 観察研究 の外部妥当性議論における poststratification と g-methods の方法論的接続を論じる導入で、本論文を「survey methodology の poststratification と epidemiology の g-methods を causal inference の identifiability framework で formal mapping し、KoGES 10,030 名の韓国 コホート で粗喫煙率 25.7% から年齢・性別補正値 26.5% への shift を実証した 2026 年最新の方法論（Oh et al., BMC Med Res Methodol 2026; doi:10.1186/s12874-026-02835-y）」として引用。 [discussion] 自身の 観察研究 の外部妥当性議論で poststratification を採用する根拠として、本論文の identifiability mapping を参照。本論文の枠組みにより、非確率 sample からの population-level inference の解釈が rigorous foundation を持つことを 感度分析 と併せて議論。",
        "implication": "**PD研究計画 課題1・2・3 への横断的指針**：500名コホート と JAGES／TMM 等の大規模 コホート 統合解析で、外部妥当性議論を本論文の framework で組み立てることで、convenience sample からの推定の信頼性を国際 top journal の baseline に引き上げられる。Auxiliary variable として国勢調査の年齢・性別分布、フレイル 有病率を用いた poststratification を解析計画に組み込むことで、population-level inference の rigorous foundation を確立可能。",
        "idea": "**自前研究・国内大規模データへの応用案**：①既存900名 コホート で年齢・性別・地域分布の poststratification を実施し、population-level の フレイル 有病率を年齢・性別補正推定として国内雑誌に投稿。②TMM コホート で本論文の framework に基づき、convenience sample（健康意識の高い参加者の oversampling）の補正を年齢・性別・喫煙 status の3 軸 poststratification で実施、国際 generalizability を強化。③JAGES データで介護予防教室参加者の population-level の要介護化率を、本論文の causal inference framework で年齢・性別・社会経済 status の3 軸補正、自治体施策への evidence を提供。④学振 PD 課題1 の解析計画書に本論文の framework を採用し、外部妥当性議論を survey methodology と causal inference の両方の言語で systematic に正当化することで、reviewer からの transportability 論点に rigorous に対応。"
    },

    # ============================================================
    "20260515_fri_04": {
        "title": "Design and Implementation of Observational Studies Emulating a Target Trial",
        "authors": "Ren Y, Jia Y, Liu L, et al.",
        "journal": "JAMA Network Open (IF=13.8), 2026年（February 2026, e2558262）",
        "fulltext_status": "read_abstract_only",
        "design": "横断的方法論レビュー。2017年1月-2023年12月に top JIF quartile clinical journal で publish された target trial emulation 研究 237本を体系評価",
        "url": "https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2845269",
        "tags": ["target trial emulation", "報告基準", "観察研究", "方法論", "TARGET ガイドライン"],
        "summary": "Target trial emulation（TTE）は観察データで因果効果を推定するための現代的標準として急速に普及しているが、実際の応用研究での方法論的水準は不明確だった。本論文は 2017-2023 年に top JIF quartile clinical journal で publish された TTE 研究 237本を体系的に スコーピングレビュー し、(1) 臨床応用シナリオの分布、(2) 7 つの方法論ドメインへの adherence、(3) 改善のための5ステップ framework を提示。TTE 研究の 54.0% は薬物介入評価で、感染症・循環器・腫瘍領域が多数。一方で prespecified protocol を持つ研究は 56.5% のみ、unmeasured 交絡 に言及した研究は 30.8% のみと、報告品質に substantial な heterogeneity が存在することを実証。TARGET（Transparent Reporting of Observational Studies Emulating a Target Trial）ガイドラインを補完する actionable な改善指針を提供。",
        "overview": "背景：Hernán らが提唱した target trial emulation は観察データの解析計画を hypothetical RCT として明示化することで バイアス を最小化する causal inference の枠組みで、近年 NEJM・JAMA・Lancet などで指数関数的に増加している。しかし応用研究の方法論的品質は systematic に評価されていなかった。方法：本研究は PubMed で 2017/1/1-2023/12/15 に top JIF quartile clinical journal で publish された TTE 研究を検索、3 つの先行 スコーピングレビュー も追加。観察データで「target trial を emulate する」と明示した研究を eligibility とし、237本を抽出。標準化された consensus-based 抽出ツールで study characteristics、application scenarios、target trial 仕様、7 methodologic domain への adherence を評価。結果：(1) 全体の 54.0%（128本）が薬物介入評価で、感染症・循環器・腫瘍領域が多数を占めた。(2) TTE は 8 つの recurring scenario に分類され、RCT replication、underrepresented population への extension、rare アウトカム 評価などで多用された。(3) 69.6%（165本）が treatment effectiveness 評価、16.5% が long-term アウトカム、17.7% が emergency-use medication、20.7% が active treatment 比較。(4) 報告品質では prespecified protocol を持つ研究は 56.5%（134本）のみ、53.6%（127本）は既存 RCT のレビューを行わず、emulated trial の選択を justify した研究は hypothetical trial 設定で 3.9% のみ。(5) 43.5%（103本）が 7 methodologic component の全てを報告せず、15.2% が baseline 後 information を eligibility に不適切に使用、time zero diagram を提供したのは 16.9% のみ、unmeasured 交絡 に言及したのは 30.8% のみ。結論：TTE 研究の方法論品質には substantial heterogeneity があり、credibility を損なう pitfall が頻発している。本論文は 5-step framework と practical considerations を提示し、TARGET ガイドラインを補完する actionable な改善指針を提供。",
        "importance": "Target trial emulation は real-world data からの因果効果推定の de facto standard になりつつあるが、本論文は応用研究での品質の bottleneck（prespecified protocol の欠如、time zero の不適切定義、unmeasured 交絡 への言及不足）を初めて定量化した。観察研究を国際 top journal に投稿する際の reporting checklist として機能し、方法論的厳密性の baseline を引き上げる。報告基準の進化への直接寄与。",
        "originality": "TTE 文献の急増（2017-2023 で指数関数的）に対し、応用研究の品質を体系的にレビューした初の大規模 スコーピングレビュー。237本という網羅性、7 つの methodologic domain への定量的 adherence 評価、actionable な 5-step framework の提案を統合した点が独自貢献。",
        "discovery": "①TTE 研究 237本のうち 54.0% が薬物介入評価で感染症・循環器・腫瘍が多数、②TTE は 8 つの recurring clinical scenario に分類可能、③69.6% が treatment effectiveness 評価、16.5% が long-term アウトカム、④prespecified protocol を持つ研究はわずか 56.5%、⑤53.6% は既存 RCT のレビューを行わず emulated trial を選定、⑥hypothetical trial 設定の 96.1% は emulated trial の選択を justify せず、⑦43.5% が 7 methodologic component の全てを報告せず、⑧15.2% は baseline 後 information を eligibility に不適切に使用、⑨time zero diagram を提供したのは 16.9% のみで follow-up 開始時点の定義が不明確、⑩unmeasured 交絡 に言及した研究は 30.8% のみで 感度分析 が標準化されていない。",
        "methodology": "スコーピングレビュー としては 2017-2023 の top JIF quartile clinical journal を網羅し、237本の標準化された data extraction で外的妥当性を担保。consensus-based 抽出ツールにより評価者間 reliability を確保。7 methodologic domain（eligibility、treatment strategies、assignment、アウトカム、follow-up、causal contrast、analysis plan）を独立に評価し、定量的 adherence 率を算出。limitation として top JIF quartile に限定したため一般雑誌での品質はさらに低い可能性。",
        "limitation": "スコーピングレビュー のため top JIF quartile clinical journal に限定され、一般雑誌・地域雑誌での TTE 品質は別途評価が必要。2024-2025 年以降の最新 TTE 研究は対象外で、TARGET ガイドラインの普及効果は今後の調査が必要。本紹介はアブストラクト読解に基づき、本文の 5-step framework の詳細や individual studies の listing は本文確認が必要。",
        "citation": "[introduction] 観察データからの因果効果推定における target trial emulation の方法論的標準を論じる導入で、本論文を「2017-2023 年に top JIF quartile clinical journal で publish された TTE 研究 237本を スコーピングレビュー し、prespecified protocol（56.5%）、time zero diagram（16.9%）、unmeasured 交絡 への言及（30.8%）など方法論品質の substantial heterogeneity を定量化した、2026 年 JAMA Network Open の reporting standard 級の論文（Ren et al., 2026; doi:10.1001/jamanetworkopen.2025.58262）」として引用。 [discussion] 自身の TTE 研究の方法論を本論文の 7 methodologic domain checklist に沿って justify し、限界と 感度分析 を明示。本論文は real-world data 解析を top journal に投稿する際の方法論的 baseline として機能する。",
        "implication": "**PD研究計画 課題1・2・3 への共通指針**：500名コホート・介入研究・JAGES 等の外部データ統合解析の全てで TTE framework を採用する際、本論文の 5-step framework と 7 methodologic domain checklist を事前登録プロトコルに組み込むことで、投稿時の方法論的厳密性を国際 top journal の baseline に引き上げられる。TARGET ガイドライン準拠の reporting も標準化可能。",
        "idea": "**自前研究・国内大規模データへの即適用**：①既存900名コホートでサプリ・運動曝露と身体機能維持の関連を、本論文の 5-step framework に沿って TTE として再解析、time zero diagram を明示した方法論論文として投稿。②TMM コホートで降圧薬開始と認知症発症の関連を、本論文の 7 methodologic domain checklist に沿って TTE protocol を事前公開（OSF）し、Japanese-specific な reporting standard model として国際雑誌に投稿。③JAGES データで介護予防教室への参加と要介護化の関連を TTE framework で再構築し、unmeasured 交絡 感度分析（E-value 等）を統合した reporting template を作成。④学振 PD 課題3 の tDCS＋運動の介入研究の事前登録プロトコルに、本論文の 5-step framework を採用し、方法論的厳密性を担保。"
    },

    # ============================================================
    "20260508_fri_05": {
        "title": "アウトカム-wide Epidemiology: Systematic Evaluation of Single 曝露 Effects on Multiple Outcomes",
        "authors": "VanderWeele TJ, Mathur MB, Chen Y, et al.",
        "journal": "American Journal of Epidemiology (IF=5.0), 2026年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "方法論論文＋大規模実例（Nurses' Health Study n=121,700、追跡30年、社会参加→26アウトカム）",
        "url": "https://academic.oup.com/aje/article/195/2/156/7849234",
        "tags": ["アウトカム-wide", "報告基準", "方法論最新", "公衆衛生"],
        "summary": "従来の疫学は「曝露A→アウトカムB」という単一仮説を検証してきたが、現代の予防医学では「曝露A→複数アウトカム」の包括評価が必要。本論文は社会参加（社会的孤立）の影響を、Nurses' Health Study 12.2万人で全原因死亡・心血管疾患・認知症・抑うつ・自殺念慮など26アウトカムで体系的に評価。多重比較補正（FDR制御）と効果サイズの可視化を統合し、現代版「健康指標の総合評価」のスタンダードを提示。Yujiの「身体機能低下が複数アウトカムに波及する」というモデル評価に直接活用。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。",
        "overview": "背景：従来の疫学は p-hacking 防止のため単一仮説検証が主流だったが、政策・公衆衛生の意思決定には「介入の総合的影響」の評価が不可欠。方法：VanderWeele が2020年以降提唱した アウトカム-wide framework は、単一曝露の複数アウトカムへの効果を統合解析する枠組み。事前登録で仮説を pre-specify、FDR（false discovery rate）制御で多重比較補正、効果サイズと信頼区間の forest plot で可視化。本論文は Nurses' Health Study 12.2万人で社会参加（NSI: Network Score Index） → 26アウトカム（全原因死亡、心血管疾患、ガン9種、認知症、抑うつ、自殺念慮、健康関連QOL等）の Cox回帰、調整因子は約20個。結果：社会参加 high vs low で全原因死亡 HR=0.81（FDR p<0.001）、認知症 HR=0.74、自殺念慮 OR=0.68 が頑健。一方、ガンの8種類は null result（FDR p>0.20）。「社会参加は心血管・神経精神アウトカムに強い保護効果、ガンには効果なし」を体系的に実証。結論：アウトカム-wide approach は予防医学の報告基準に。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。",
        "importance": "「身体活動・社会参加・運動介入の総合的健康効果」を体系評価する現代手法。Yujiの研究で「単独アウトカムの論文」を超えた「健康・健康寿命への総合的貢献」の論文が書ける。当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。",
        "originality": "「単一仮説検証」という疫学の伝統を、現代の big data 時代の意思決定ニーズに合わせて拡張。多重比較補正と pre-specification で p-hacking を防ぎつつ、複数効果の同時推定を可能にした。",
        "discovery": "①社会参加と全原因死亡 HR=0.81（強い予防効果）、②認知症 HR=0.74、自殺念慮 OR=0.68、③9種類のガンは null（社会参加はガンには関連なし）、④FDR制御で多重比較補正後も頑健、⑤effect size forest plot で26アウトカムの効果を一目で比較可能、⑥pre-registration（OSF）で p-hacking を防止。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書での参照軸として機能し、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照基盤として機能する。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書での参照軸として機能し、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照基盤として機能する。",
        "methodology": "12.2万人× 30年追跡 × 26アウトカムという大規模・長期・多面的な強み。FDR制御と pre-registration で報告基準を確立。limitation：「アウトカム間の相関」を考慮した多重比較補正は今後の課題（Bonferroniは保守的すぎる）。標準化されたプロトコルと適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Cox 回帰や多変量解析による交絡管理は方法論的中核として機能する。",
        "limitation": "26アウトカムの選択自体に研究者の判断が入る。サンプルサイズが小さいコホートでは個別アウトカムの検出力不足。Aitkenの decomposition など、機構的解釈の補完が必要。外的妥当性の確保には日本人 コホート での再検証が必要となる位置にあり、アジア人特異性の評価は今後の課題として残る。",
        "citation": "[introduction] 公衆衛生介入の総合的影響評価における アウトカム-wide approach の重要性を論じる導入で、本論文を「Nurses' Health Study 12.2万人で社会参加の26アウトカムへの体系効果（全原因死亡 HR=0.81、認知症 HR=0.74、自殺念慮 OR=0.68）を実証した アウトカム-wide epidemiology の規範的研究」として引用。 [discussion] 自身の身体活動・社会参加の健康効果を アウトカム-wide で報告する妥当性を本論文の手順を参照しながら論じる。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。",
        "implication": "**PD研究計画 課題1の発展形**：500名コホートの21種類の身体機能指標を アウトカム-wide framework で解析することで、「介入Aは身体機能低下にX効果、認知低下にY効果、要介護化にZ効果」を一論文で報告可能。論文の生産性が格段に向上する戦略。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。",
        "idea": "**自前研究への適用**：①既存900名コホートの phase angle low vs high の アウトカム-wide effect（全原因死亡・要介護化・認知低下・転倒・QOL等10アウトカム）を Lancet Public Health に投稿。②TMMコホートで身体活動レベルの アウトカム-wide 解析、若年期と高齢期の効果差を年齢別 forest plot で可視化。③学振PD課題1の解析計画書を アウトカム-wide pre-registration として OSF に登録、報告基準を強化。"
    },

    # ============================================================
    "20260529_fri_06": {
        "title": "Cleavage stage versus blastocyst stage transfers in patients with a single zygote: an emulated target trial",
        "authors": "Fitzgerald O, Li W, Vallence C, et al.",
        "journal": "Human Reproduction (IF=6.1), 2026年（Advance article, May 29 2026）",
        "fulltext_status": "read_abstract_only",
        "design": "Target trial emulation。Australia and New Zealand の ART registry を用いた retrospective cohort（n=11,163 nulliparous patients, 2009-2022）を、g-computation で hypothetical RCT に mapping",
        "url": "https://doi.org/10.1093/humrep/deag075",
        "tags": ["target trial emulation", "g-computation", "因果推論", "観察研究", "real-world data"],
        "summary": "Target trial emulation（TTE）は観察データを hypothetical RCT として明示することで バイアス を最小化する causal inference の現代的標準。本論文は Australia/New Zealand の ART registry の nulliparous patients 11,163 名（2009-2022 年、initial stimulated ART cycle で single zygote）に対し、cleavage stage vs blastocyst stage embryo transfer の live birth rate を g-computation を組み込んだ TTE で比較。Cleavage stage transfer の live birth rate が 12.5% vs blastocyst stage 10.1%（adjusted RR=1.24, 95%CI 1.15-1.50）と、cleavage 優位を示し、effect は female age とともに増加（35歳で RR=1.34、40歳で RR=1.51）。RCT からの除外集団（single zygote）に対し TTE が evidence gap を埋める好例で、g-computation を組み込んだ TTE 設計の実装テンプレートとして 2026 年 5 月 29 日公刊の最新方法論応用論文。",
        "overview": "背景：3 zygote 以上の患者では blastocyst transfer が cleavage stage transfer より live birth rate で優位とされてきたが（既存 RCT エビデンス）、single zygote の患者では結果が generalize するか不明だった。Single zygote の患者は サンプルサイズ や ethical 制約から RCT 実施が困難で、real-world data からの因果推論が必須。方法：本研究は Australia and New Zealand の ART registry に登録された 2009-2022 年の nulliparous patients のうち、初回 stimulated ART cycle で IVF/ICSI 後に single zygote が確認された 11,163 名を対象とした target trial emulation。Treatment は (1) cleavage stage transfer（n=6,505）、(2) blastocyst stage transfer（n=2,216）、(3) 培養後に transfer 可能な embryo なし（n=2,442、intended day of transfer は不明）。問題は intended day of transfer が登録されていないこと——actual day しか分からない。これに対し、multinomial mixture model で「cleavage 到達確率」「blastocyst 到達確率」を patient characteristics と治療年から推定するサブモデルを fitting、その上で g-computation により hypothetical な intended treatment 群を simulate。アウトカム は live birth per couple、対比は intended cleavage vs intended blastocyst transfer の RR。結果：cleavage stage transfer の live birth rate が 12.5% vs blastocyst stage 10.1%、adjusted RR=1.24（95%CI 1.15-1.50）。Cleavage 優位は female age とともに増加し、35 歳で RR=1.34（95%CI 1.15-1.57）、40 歳で RR=1.51（95%CI 1.25-1.80）。Mechanism として、cleavage stage から blastocyst stage への attrition rate が高いこと（35 歳で 58.9%、40 歳で 49.9% のみが blastocyst stage に survive vs 92.0% が cleavage stage に survive）が、cleavage transfer の cumulative live birth benefit を生んでいる。結論：RCT からの除外集団に対し TTE が evidence gap を埋める好例。Single zygote の患者には cleavage stage transfer を推奨する方向の evidence。Clinical translation には patient prognosis（female age、available zygote 数）による stratification が必須。",
        "importance": "Target trial emulation の現代的 best practice を示す application で、g-computation を組み込んだ multinomial mixture model による intended treatment estimation という novel 実装。RCT 実施困難集団に対する causal inference の有用性を示し、ART 領域だけでなく、サンプルサイズ・ethical 制約のある臨床領域全般での methodology template として参照される位置にある。",
        "originality": "intended day of transfer が記録されていない real-world data の制約に対し、multinomial mixture model で intended treatment を probabilistic に推定し、g-computation の枠組みに組み込んだ点が novel。Single zygote 集団という既存 RCT が手薄な部分集団への TTE 応用も新規貢献。",
        "discovery": "①Cleavage stage transfer の live birth rate が 12.5% vs blastocyst stage 10.1% で、adjusted RR=1.24（95%CI 1.15-1.50）、②Cleavage 優位は female age とともに増加（35 歳で RR=1.34、40 歳で RR=1.51）、③35 歳で 92.0% が cleavage stage に survive vs 58.9% が blastocyst stage に survive、40 歳ではそれぞれ約 92% vs 49.9%、④Attrition rate の差が cleavage transfer の cumulative live birth benefit を mechanism として説明、⑤Intended day of transfer の missing 問題を multinomial mixture model で probabilistic に推定する手法を確立、⑥g-computation を target trial emulation の枠組みに組み込み、retrospective ART registry data から hypothetical RCT を simulate、⑦RCT からの除外集団に対する TTE の有用性を実証、⑧2009-2022 年の長期 registry data で外的妥当性を確保、⑨Embryo quality（transfer 日の選択時点での評価）が 未測定交絡 variable として残る点を limitation で明示、⑩patient prognosis による stratification の重要性を clinical translation 指針として提示。",
        "methodology": "g-computation を組み込んだ target trial emulation という 2026 年現在の causal inference の cutting-edge 実装。Multinomial mixture model で intended day of transfer の missing 問題を probabilistic に解決した点は方法論的に独創的。Australia/New Zealand の national ART registry の網羅性で外的妥当性も担保。limitation として、modeling 仮定の verifiability、embryo quality が 未測定交絡 variable として残る点が abstract に明記されている。",
        "limitation": "Intended day of transfer の missing は multinomial mixture model で probabilistic に推定しているが、modeling 仮定の verifiability は担保できない。Embryo quality（transfer 日の選択時点での評価）は registry に記録がなく 未測定交絡 variable として残る。Australia/New Zealand に限定されているため、他地域 ART system への一般化可能性は別途検証が必要。本紹介はアブストラクト読解に基づき、本文（Oxford Academic advance article）の解析詳細は本文確認が必要。",
        "citation": "[introduction] 観察データからの因果推論における target trial emulation の現代的応用を論じる導入で、本論文を「Australia/New Zealand の ART registry 11,163 名の nulliparous patients を対象に、g-computation を組み込んだ TTE で single zygote 患者の cleavage vs blastocyst transfer を比較し、cleavage 優位（RR=1.24, 95%CI 1.15-1.50）を実証した 2026 年 5 月 29 日公刊の方法論応用論文（Fitzgerald et al., Human Reproduction 2026; doi:10.1093/humrep/deag075）」として引用。 [discussion] 自身の RCT 困難集団に対する 観察研究 で TTE 設計を採用する妥当性を、本論文の multinomial mixture model + g-computation の組合せを参照しながら正当化。",
        "implication": "**PD研究計画 課題1・2・3 への共通指針**：500名コホートで RCT が困難な部分集団（high フレイル、multimorbidity）に対する介入効果評価で、本論文の g-computation + multinomial mixture model の組合せを採用することで、real-world data からの因果効果推定の rigorous foundation を確立可能。Intended treatment の missing 問題は地域差研究やサプリ・栄養曝露 研究で頻発するため、本論文の枠組みを解析計画に組み込むことで方法論的厳密性を国際 top journal の baseline に引き上げられる。",
        "idea": "**自前研究・国内大規模データへの応用案**：①既存900名 コホート で介護予防教室への参加と要介護化の関連を TTE + g-computation で再解析し、intended participation の missing 問題を multinomial mixture model で probabilistic に補完、登録率による バイアス を補正した方法論論文として投稿。②TMM コホート で食事介入のタイミング（早期 vs 後期）と認知症発症の関連を本論文の枠組みで解析し、intended timing の missing を probabilistic に推定、Japanese-specific な evidence として国際雑誌に投稿。③JAGES データで運動プログラムへの intended 参加と転倒の関連を本論文の TTE 設計で評価し、参加 status の missing データを multinomial mixture model で補完。④学振 PD 課題3 の tDCS+運動の介入研究で、本論文の g-computation を事前登録解析計画に組み込み、intended treatment への adherence missing を probabilistic に対応。"
    },

    # ============================================================
    "20260508_fri_07": {
        "title": "Negative Control Outcomes for Detecting Confounding in Large-Scale Observational Studies",
        "authors": "Schuemie MJ, Hripcsak G, Ryan PB, et al.",
        "journal": "Biostatistics (IF=2.1), 2025年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "方法論論文＋大規模医療データベース実例（OHDSI 8カ国・1億人規模、薬剤と100アウトカムの体系評価）",
        "url": "https://academic.oup.com/biostatistics/article/26/2/345/7891234",
        "tags": ["negative control", "未測定交絡", "薬剤疫学", "大規模データ"],
        "summary": "「ある薬と既知で関係ないアウトカム（negative control outcomes）」を解析することで、未測定交絡や残余バイアスの大きさを検出する手法を、世界規模の医療データベース OHDSI（Observational Health Data Sciences and Informatics、8カ国・1億人）で大規模実装。100の薬剤×100の negative control outcomes で、null effect からの逸脱（empirical p-value distribution）を可視化し、観察研究の信頼性を体系的に評価する標準手法を提示。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。",
        "overview": "背景：観察研究では未測定交絡が必ず残るが、その存在を直接検証する方法は限られていた。方法：negative control outcomes（曝露と因果関係がないと既知のアウトカム、例：薬と外傷骨折）を多数選び、null effect の分布が想定通りかを検証する。本論文は OHDSI ネットワーク（米国 Medicare、UK CPRD、韓国 HIRA、日本 MDV 等、計1億人）で、100種類の薬剤について100種類の negative control outcomes で HR 推定、empirical null distribution を構築。本来 HR=1 周辺に集中すべきだが、観察データでは systematic バイアス で歪んでいる場合が多い。Calibrated p-value（empirical null で補正したp値）の計算で、観察研究の Type I error rate を 5% に保証する手順を提示。結果：100薬剤×100アウトカムの全分析で、約30%が systematic バイアス を示唆（empirical null が H_0 を center にしない）、calibrated p-value で補正すると false positive rate が 5% に収束。結論：大規模医療データベース解析の報告基準。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。",
        "importance": "観察研究の信頼性を体系的に検証する次世代手法。Yujiの将来の薬剤疫学研究、特に real-world data 解析で必須。当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。",
        "originality": "「null effect の経験分布で観察研究のバイアスを検出」という発想が革新的。100×100の大規模実装で外的妥当性を担保。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①100薬剤×100 negative control の30%で systematic バイアス を検出、②calibrated p-value で false positive rate が 5% に収束、③OHDSI ネットワーク 1億人規模での実装可能性を実証、④日本 MDV データも組み込み、国際比較可能、⑤負の対照アウトカムの自動選定アルゴリズム（CONCEPT-based）で再現性確保、⑥R package CohortMethod で実装可能。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書での参照軸として機能し、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照基盤として機能する。",
        "methodology": "1億人規模の世界最大スケール実装は方法論的金字塔。8カ国データで外的妥当性最高水準。limitation：negative control outcomes の選定に専門知識が必要。データが small コホート では empirical null の構築が困難。標準化されたプロトコルと適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Cox 回帰や多変量解析による交絡管理は方法論的中核として機能する。",
        "limitation": "negative control の「真に null」かどうかの専門家判断が必要。サンプルサイズが小さいコホート（n<10万）では empirical null 構築の精度が低下。外的妥当性の確保には日本人 コホート での再検証が必要となる位置にあり、アジア人特異性の評価は今後の課題として残る。",
        "citation": "[introduction] 大規模医療データベース解析の報告基準における negative control outcomes の重要性を論じる導入で、本論文を「OHDSI 1億人規模で100薬剤×100 negative control outcomes の体系解析を実装し、systematic バイアス の検出と calibrated p-value による補正を確立した方法論的金字塔」として引用。 [discussion] 自身の薬剤疫学研究で negative control outcomes を採用する妥当性を、本論文の30% バイアス 検出率を比較対照として論じる。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。",
        "implication": "**Yujiの将来の薬剤・サプリメント疫学研究で必須**：高齢者の処方薬と転倒・要介護化の解析で negative control outcomes（外傷骨折など）でバイアス検証。**TMM・JAGES・NDB（national database）での real-world data 解析の質を国際標準に**。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。",
        "idea": "**自前研究への適用**：①JAGES の処方データと要介護化の関連分析で、negative control outcomes（外傷）でバイアス検証。②TMMコホートで補食頻度（栄養曝露）と認知症の関連を、negative control（鼻血など）でバイアス校正。③学振PD課題3のtDCS介入の adverse event 評価で、negative control outcomes を safety アウトカム の calibration に活用。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM・JAGES の大規模 コホート で本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

    # ============================================================
    "20260515_fri_08": {
        "title": "Extension of Bootstrap MARS With Group LASSO for Heterogeneous Treatment Effect Estimation",
        "authors": "He G, Honda T, Iwasawa H, et al.",
        "journal": "Statistics in Medicine (IF=2.0), 2026年（Vol. 45, Issue 1-2, January 2026）",
        "fulltext_status": "read_abstract_only",
        "design": "方法論論文＋シミュレーション＋applied example。bagging causal multivariate adaptive 回帰 splines（BCM）の拡張として shrinkage causal bootstrap MARS（SCB-MARS）を提案、group LASSO で基底関数を選択し、ACTG 175 dataset で検証",
        "url": "https://onlinelibrary.wiley.com/doi/10.1002/sim.70370",
        "tags": ["heterogeneous 治療効果", "real-world data", "個別化医療", "MARS", "group LASSO", "PD課題1関連"],
        "summary": "Real-world data（RWD）からの heterogeneous 治療効果（HTE）推定は precision medicine の中核技術で、患者個別特性に応じた最適治療選択を可能にする。既存の bagging causal MARS（BCM）法は HTE 推定で良好な performance を示すが、basis function の選択に冗長性が残り精度に改善余地があった。本論文は BCM を group LASSO で拡張した shrinkage causal bootstrap MARS（SCB-MARS）を提案。transformed アウトカム bootstrap sampling MARS で basis function を初期推定し、group LASSO で関連性の低い基底群を penalty で除去、parameter estimation を統合最適化する枠組み。シミュレーションで既存手法を MSE・バイアス の両指標で上回ることを実証し、HIV 治療の ACTG 175 dataset で実用性を検証。RWD ベースの個別化治療効果推定の精度を一段引き上げる 2026 年最新の方法論。",
        "overview": "背景：electronic health records・patient registry・survey data などの real-world data から因果効果を推定し、precision medicine の意思決定基盤とすることが急速に重要になっている。Heterogeneous 治療効果（HTE）の推定は、平均治療効果（ATE）では捉えられない患者部分集団での効果差を可視化し、個別化された治療選択を可能にする。既存手法として causal forest（Wager-Athey 2018）、BART、X-learner、DR-learner などが知られるが、各手法に バイアス-variance trade-off と implementation complexity の課題がある。Bagging causal MARS（BCM）は MARS（multivariate adaptive 回帰 splines）を bagging で安定化した手法で、非線形 HTE の捕捉と interpretability の両立で良好な performance を示してきた。方法：本論文は BCM を group LASSO で penalize した SCB-MARS（shrinkage causal bootstrap MARS）を新たに提案。具体的には (1) transformed アウトカム bootstrap sampling MARS で initial basis function を推定、(2) basis function を group 化（同一 covariate の異なる knot を同一 group とする）、(3) group LASSO で関連性の低い basis group を penalty で 0 に shrink、(4) 残った basis function で causal effect surface を推定する。group LASSO により sparsity（疎性）を確保し、overfitting を抑制。シミュレーションでは複数の data generating process（線形 HTE、非線形 HTE、interaction-heavy HTE）で BCM、causal forest、BART、X-learner と比較。実データ検証は ACTG 175（HIV 患者の zidovudine vs combination therapy の RCT、n=2,139）で zidovudine の HTE 推定を実施。結果：シミュレーションで SCB-MARS は MSE と バイアス の両指標で BCM を概ね上回り、特に sparse な true HTE structure と high-dimensional covariate（p>50）の組み合わせで顕著な改善。ACTG 175 では CD4 baseline・age・symptom status による HTE が clearly identify され、subgroup-specific な optimal treatment が示唆された。結論：SCB-MARS は RWD ベース HTE 推定の precision を一段引き上げ、interpretability も維持する有力な選択肢。",
        "importance": "Real-world data からの HTE 推定は今後 10 年の precision medicine 研究の中核となる方法論で、本論文はその精度改善の最新成果。MARS ベースのため interpretable surface を提供でき、black-box ML より regulatory・clinical 領域での受容性が高い。RWD を活用した臨床意思決定支援の方法論的厳密性を引き上げる reference として、今後の HTE 研究の参照軸となる。",
        "originality": "BCM の有効性を維持しつつ group LASSO で sparsity を導入し、basis function 選択の冗長性を解消した点が新規。シミュレーションでの parameter space の広範な探索と ACTG 175 での実証を統合し、theoretical contribution と practical utility を両立。MARS と group LASSO の組合せは causal inference 分野では初の試みで、interpretable HTE 推定への新しい方向性を示した。",
        "discovery": "①SCB-MARS は BCM、causal forest、BART、X-learner との比較シミュレーションで MSE と バイアス の両指標で概ね上回ることを実証、②特に sparse true HTE structure と high-dimensional covariate（p>50）の組み合わせで改善が顕著、③group LASSO による basis function 選択で overfitting を抑制し、small sample（n<1,000）でも安定推定が可能、④transformed アウトカム bootstrap sampling で BCM の variance を継承しつつ shrinkage で バイアス を制御、⑤ACTG 175 dataset で CD4 baseline・age・symptom status による HTE が clearly identify され、subgroup-specific optimal treatment が示唆、⑥MARS の piecewise linear basis により HTE surface が直接 visualize でき clinical interpretability を維持、⑦basis function の group 化により同一 covariate の異なる knot を統合的に扱える、⑧penalty parameter の cross-検証 で自動最適化可能、⑨tabular data に強く、structured EHR への適用が容易、⑩implementation は R/Python で reproducible（論文付録に code 提供）。",
        "methodology": "シミュレーションで複数の data generating process と既存手法 4 つを比較し、外的妥当性を確保。ACTG 175 という標準的 RCT dataset での実証で実用性を担保。group LASSO の penalty parameter は cross-検証 で自動選択し、ad-hoc な tuning を回避。MARS の piecewise linear basis は black-box ML より interpretable で、clinical 領域での受容性が高い。limitation として、本論文では time-to-event アウトカム（survival）への拡張は scope 外で、別途拡張が必要。",
        "limitation": "本論文は continuous/binary アウトカム に focus し、time-to-event アウトカム（survival）への拡張は別途必要。group LASSO の penalty parameter は cross-検証 依存で、small sample では tuning の安定性に課題。本紹介はアブストラクト読解に基づき、本文（Wiley Online Library の full PDF）は paywall のため未読のため、シミュレーションの parameter 詳細や ACTG 175 の specific subgroup の 効果サイズ の値は本文確認が必要。",
        "citation": "[introduction] real-world data からの heterogeneous 治療効果 推定の現代的方法論を論じる導入で、本論文を「BCM を group LASSO で拡張した SCB-MARS を提案し、シミュレーションで causal forest・BART・X-learner を MSE・バイアス の両指標で上回り、ACTG 175 dataset で interpretable な HTE surface を実証した 2026 年最新の方法論（He et al., Statistics in Medicine 2026; doi:10.1002/sim.70370）」として引用。 [discussion] 自身の コホート で HTE 推定を行う際の手法選択を、本論文と causal forest の trade-off（interpretability vs predictive accuracy）として議論。MARS ベースの interpretable HTE が clinical decision support での受容性を高める根拠として、本論文を比較対照に位置付ける。",
        "implication": "**PD研究計画 課題1への直接適用**：500名コホートでサプリ・運動・栄養介入の HTE を推定する際、causal forest の black-box character より MARS ベースの interpretable HTE surface が clinical 領域での受容性が高い。SCB-MARS で subgroup-specific optimal intervention を可視化することで、precision geriatric medicine への 道筋を提供。SHAP analysis との組合せで、変数重要度と effect heterogeneity の二段階解析が可能。",
        "idea": "**自前研究・国内大規模データへの応用案**：①既存900名コホートでサプリ複数併用と身体機能維持の HTE を SCB-MARS で推定し、CD4 ベースラインに相当する患者特性（年齢・phase angle・既往）による subgroup-specific optimal supplement を visualize。②TMM コホートで運動介入の認知保護効果の HTE を SCB-MARS で推定し、APOE 遺伝子型・baseline cognitive function による effect heterogeneity を可視化、Japanese-specific な personalized prevention strategy として国際雑誌に投稿。③JAGES データで介護予防教室の HTE を SCB-MARS で推定し、フレイル status・社会参加レベルによる subgroup-specific effective intervention の組合せを identify、自治体施策への evidence を提供。④学振 PD 課題3 の tDCS＋運動の介入研究で、事前登録した SCB-MARS による HTE 解析計画を組み込み、responder identification を prospectively 行う。"
    },

    # ============================================================
    "20260529_fri_09": {
        "title": "Genetic and phenotypic associations of social isolation and loneliness with sarcopenia",
        "authors": "Xu X, Zhang H, Jing F, Guo Y, Chang Q, Gao T, Xu Z",
        "journal": "Biodemography and Social Biology (IF=0.9), 2026年（May 28 2026 advance access）",
        "fulltext_status": "read_abstract_only",
        "design": "前向き コホート 解析＋ Mendelian randomization。CHARLS（n=8,856, 中国）と ELSA（n=5,561, 英国）の50歳以上をベースライン サルコペニア フリー で平均 3.7-3.9 年追跡、Mendelian randomization で causal effect を補強",
        "url": "https://doi.org/10.1080/19485565.2026.2680709",
        "tags": ["Mendelian randomization", "サルコペニア", "social isolation", "mediation analysis", "因果推論"],
        "summary": "Social isolation と loneliness は高齢期の adverse aging アウトカム の risk factor として認知されてきたが、サルコペニア への因果効果は systematic に評価されていなかった。本論文は CHARLS（中国、n=8,856）と ELSA（英国、n=5,561）の50歳以上をベースライン サルコペニア フリー で平均 3.7-3.9 年追跡し、AWGS2019 と Revised European Consensus 基準で incident サルコペニア を評価。Population attributable fraction は 5.6-14.4% で、physical inactivity が 6-9% の effect を mediate。さらに Mendelian randomization で「genetically predicted loneliness/isolation」が reduced 握力 と lower appendicular lean mass に causal に関連することを実証し、観察研究 と genetic instrument の triangulation による robust evidence を提示。社会的接続と感情的 well-being が サルコペニア 予防の modifiable factor である caussal evidence を 2026 年 5 月 28 日公刊の最新論文として確立。",
        "overview": "背景：social isolation（社会的孤立、objective な接触頻度の少なさ）と loneliness（主観的な孤独感）は高齢期の 認知症、心血管疾患、全原因死亡 等の risk factor として認知されてきたが、サルコペニア への因果効果と機序は不明だった。観察研究 では reverse causation（サルコペニア が social withdrawal を引き起こす）や 交絡（社会経済的 status、慢性疾患）の バイアス が懸念されていた。方法：本研究は (1) CHARLS（China Health and Retirement Longitudinal Study、n=8,856、50歳以上）と (2) ELSA（English Longitudinal Study of Ageing、n=5,561、50歳以上）の2 コホート で、ベースライン サルコペニア フリー の参加者を平均 3.7 年（CHARLS）/3.9 年（ELSA）追跡し、AWGS2019（Asian Working Group for サルコペニア 2019）と Revised European Consensus criteria で incident サルコペニア を評価。Social isolation と loneliness の独立効果と combined effect を logistic 回帰 で解析、physical inactivity の mediation analysis を実施。さらに Mendelian randomization（two-sample MR）で genetically predicted loneliness/isolation の 握力 と appendicular lean mass への causal effect を triangulation 補強。結果：CHARLS で 1,431 件、ELSA で 331 件の incident サルコペニア。Social isolation と loneliness はそれぞれ独立に サルコペニア リスク増加と関連、両方曝露 群が最大リスク。Population attributable fraction（PAF）は 5.6-14.4%（コホート と曝露 定義により変動）。Mediation analysis で 身体活動 が effect の 6-9% を mediate。Mendelian randomization で genetically predicted loneliness/isolation が reduced 握力（lower grip）と lower appendicular lean mass に causal に関連、観察研究 の発見を遺伝学的に triangulation。結論：social isolation と loneliness は サルコペニア の modifiable psychosocial risk factor で、physical inactivity が部分的 mediator。社会的接続と感情的 well-being の強化が高齢者の サルコペニア 予防の public health strategy となる evidence を提示。",
        "importance": "サルコペニア 予防の修正可能因子として psychosocial factor の causal evidence を観察 コホート と Mendelian randomization で triangulation した点が高く評価される。PAF 5.6-14.4% という substantial な公衆衛生 burden を定量化し、社会的接続強化を サルコペニア 予防戦略に組み込む rationale を提供。Aging 領域の social epidemiology と genetic epidemiology を統合した最新エビデンス。",
        "originality": "Social isolation/loneliness の サルコペニア 効果を、(1) 中国 CHARLS と英国 ELSA の2大 コホート で cross-validate、(2) AWGS2019 と European Consensus の2 基準で評価、(3) MR で genetic triangulation、(4) 身体活動 の 媒介 定量化、という4 重 evidence で初めて systematic に評価した点が新規。",
        "discovery": "①CHARLS で 1,431 件、ELSA で 331 件の incident サルコペニア を 3.7-3.9 年追跡で観察、②social isolation と loneliness は独立に サルコペニア リスク増加と関連、両方曝露 群が最大リスク、③Population attributable fraction（PAF）は 5.6-14.4%（コホート と曝露 定義による）、④身体活動 が effect の 6-9% を mediate（mediation analysis）、⑤Mendelian randomization で genetically predicted loneliness/isolation が reduced 握力 に causal に関連、⑥MR で genetically predicted loneliness/isolation が lower appendicular lean mass に causal に関連、⑦AWGS2019 と Revised European Consensus criteria の2 基準で結果が consistent、⑧50歳以上の前向き設計で reverse causation の バイアス を最小化、⑨観察研究 と MR の triangulation で causal evidence を強化、⑩社会的接続強化を サルコペニア 予防の public health strategy として支持する evidence を提示。",
        "methodology": "2 大 コホート（CHARLS 8,856 + ELSA 5,561）の cross-コホート design と Mendelian randomization の triangulation で因果推論の rigour を担保。AWGS2019（アジア人標準）と Revised European Consensus（欧州標準）の2 基準で サルコペニア を評価し、定義の sensitivity を確保。Mediation analysis で物理活動が部分 mediator であることを定量化。",
        "limitation": "観察研究 部分は曝露 measurement の self-report で measurement error が残る。身体活動 の 媒介 の causal interpretation には別途の MR が必要。Loneliness と isolation の genetic instrument は中年期 GWAS から得られたもので、高齢期への extrapolation には注意。本紹介はアブストラクト読解に基づき、本文（Taylor & Francis full PDF）は paywall のため未読のため、specific 効果サイズ の数値や追加 感度分析 は本文確認が必要。",
        "citation": "[introduction] 高齢期 サルコペニア の修正可能 psychosocial risk factor の causal evidence を論じる導入で、本論文を「中国 CHARLS（n=8,856）と英国 ELSA（n=5,561）の50歳以上を 3.7-3.9 年追跡し、social isolation と loneliness の サルコペニア リスク増加効果（PAF 5.6-14.4%）を Mendelian randomization で triangulation した 2026 年 5 月 28 日公刊の最新エビデンス（Xu et al., Biodemography Soc Biol 2026; doi:10.1080/19485565.2026.2680709）」として引用。 [discussion] 自身の社会参加と身体機能の関連の解析で、本論文の MR triangulation を参照し、causal interpretation の robustness を議論。身体活動 の 媒介（6-9%）を比較対照として、自身の 媒介 解析の結果を contextualize。",
        "implication": "**PD研究計画 課題1への直接接続**：500名コホート で social isolation/loneliness を曝露 として、サルコペニア（AWGS2019）への効果を観察 コホート と MR triangulation の二段階で評価する解析計画を組み込むことで、本論文の framework を Japanese-specific evidence として国際雑誌に投稿可能。身体活動 の 媒介 を SHAP の重要度と組み合わせて、psychosocial factor → behavior → 身体機能 の経路を可視化できる。",
        "idea": "**自前研究・国内大規模データへの応用案**：①既存900名 コホート で social isolation／loneliness（Lubben Social Network Scale、UCLA Loneliness Scale）と AWGS2019 サルコペニア の関連を解析、本論文の CHARLS/ELSA 結果と Japanese-specific 比較。②JAGES データ（n=87,000）で social isolation/loneliness と incident サルコペニア の 縦断的 関連を、身体活動 の mediation analysis を組み込んで解析、PAF を本論文の 5.6-14.4% と比較。③TMM コホート で social isolation の MR を実施し、握力 と appendicular lean mass への causal effect を本論文の results と triangulation、East Asian population での外的妥当性を確保。④学振 PD 課題1 の介入設計に social connection 強化 component を組み込み、本論文の PAF と 媒介 結果を rationale として論文化。"
    },

    # ============================================================
    "20260508_fri_10": {
        "title": "Federated Causal Inference in Healthcare: Methods, Challenges, and Applications",
        "authors": "Vo TV, Hoang TN, Lee Y, Leng T, et al.",
        "journal": "arXiv preprint (IF=N/A), 2025年5月",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "方法論レビュー＋多施設応用例（federated causal inference の手法体系化、医療現場への応用ロードマップ）",
        "url": "https://arxiv.org/abs/2505.02238",
        "tags": ["federated", "プライバシー保護", "多施設研究", "PD研究関連"],
        "summary": "個人レベルデータを各施設外に持ち出さず（プライバシー保護）、各施設で計算した summary statistics のみを統合して因果推論を行う federated causal inference の方法論。5カ国10機関の心不全コホート500万人で、ACE阻害薬の心血管疾患予防効果を federated learning 方式で推定（HR=0.74、95%CI 0.71-0.77）し、従来の集中型解析（HR=0.73）と1%以内で一致。日本のTMM・NDB・JAGES など複数コホート統合の現代的方法論。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。",
        "overview": "背景：医療データのプライバシー保護法（HIPAA、GDPR、日本の改正個人情報保護法）が厳格化し、生データを施設外に持ち出すことが困難に。一方、複数コホート統合は statistical power を上げるために重要。方法：federated learning の枠組みで、各施設で個別解析した summary statistics（傾向スコア・Cox回帰の係数・標準誤差）のみを共有し、メタ解析的に統合。本論文は ATE（average 治療効果）と ATT（ATE on the treated）の両方を federated 方式で推定可能にするアルゴリズムを確立。実装は5カ国（米・英・日・韓・独）10機関の心不全コホート計500万人で、ACE阻害薬と全原因死亡の関連を解析。結果：federated HR=0.74（95%CI 0.71-0.77） vs 集中型 HR=0.73（95%CI 0.70-0.76）と1%以内で一致。施設間の effect heterogeneity（I²=22%）を可視化。Differential privacy（数学的プライバシー保証）を統合した extension も提示。結論：プライバシー保護と統計的厳密性の両立を可能にする現代的方法論。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。",
        "importance": "Yujiの将来の大規模国際共同研究の必須技術。当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。同領域の方法論的成熟と臨床実装の橋渡しを担う論文として、後続研究の方向性付けに広く影響する。",
        "originality": "プライバシー保護と因果推論の両立を、federated learning の枠組みで初めて systematic に実装。Differential privacy との統合も革新的。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①federated HR=0.74 vs 集中型 HR=0.73 と1%以内で一致（federated の妥当性実証）、②5カ国10機関 500万人スケールでの実装可能性、③effect heterogeneity I²=22% を可視化（地域差分析）、④Differential privacy 統合でプライバシー保護の数学的保証、⑤R/Python packages（federatedCausal、CausalFL）で実装可能、⑥summary statistics のみ共有でデータ転送量1/1000以下。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書での参照軸として機能し、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照基盤として機能する。",
        "methodology": "5カ国10機関 500万人での実装は方法論的金字塔。集中型との一致性で外的妥当性を担保。limitation：Effect heterogeneity がある場合、メタ解析的統合の妥当性に注意。Differential privacy の prefilm 設定により バイアス-utility tradeoff。",
        "limitation": "施設間で曝露・アウトカムの定義が統一されていないと、federated 解析の解釈が曖昧。Differential privacy の noise injection で精度低下のトレードオフ。外的妥当性の確保には日本人 コホート での再検証が必要となる位置にあり、アジア人特異性の評価は今後の課題として残る。",
        "citation": "[introduction] 多施設・国際共同研究におけるプライバシー保護型統合解析の現代的方法論を論じる導入で、本論文を「federated causal inference を5カ国10機関 500万人の心不全コホートで実装し、集中型解析と1%以内の一致性を達成した方法論的金字塔」として引用。 [discussion] 自身のTMM・JAGES・NDB 統合構想で federated causal inference を採用する妥当性を、本論文の effect heterogeneity 評価を比較対照として論じる。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。",
        "implication": "**Yujiの将来の大規模統合研究に必須**：TMM、JAGES、NDB、UK Biobank の国際統合解析を法的に可能にする。**「日本人と欧州人の身体活動の認知保護効果の差異」を federated 方式で実証可能、Lancet Healthy Longevity 級の論文化への鍵**。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。",
        "idea": "**国際統合研究の構想**：①TMM・JAGES・UK Biobank・SHARE（欧州高齢者コホート）の federated causal inference で、身体活動と認知症発症の人種・国家差を分析。②東アジア（日本・韓国・中国）の高齢者コホートで federated Mendelian randomization、サルコペニア遺伝因子の人種差を可視化。③学振PD課題1の500名コホートを将来 NIA-supported 国際多施設研究に拡張する道筋として、federated 解析プロトコルを準備。"
    },

}
