# -*- coding: utf-8 -*-
"""
PDキュレーションレポート用のリッチ本文（2026-06-13 PD研究レポートC版）。
サブテーマ：脳・神経系メカニズムによる身体機能低下の説明
（fMRI / NCS / 脊髄 / MUNE / TMS / 中枢駆動 / 反射 / DTI / PET / 中枢-末梢 統合）

過去2レポートとの差別化：
- レポートA（20260611）：構造MRI/DTI/白質高信号 × 身体機能
- レポートB（20260612）：HD-sEMG/CMC/fNIRS × 行動
- レポートC（本回）：純粋に神経科学的メカニズム（中枢神経系・末梢神経）で
  身体機能低下を説明する論文に絞る。筋肉由来説明は除外。

各論文に10セクションのドリル済みテキストを保持。
更新ガイド：
- 新しい論文を追加する場合、id をキーに同じスキーマで dict を追加するだけ。
- フィールドを空文字 "" にすればそのセクションは出力しない。
- TMM = 東北メガバンク、UKB = UK Biobank
"""

CONTENT = {

    # ============================================================
    "20260613_pd_01": {
        "title": "Aging increases the cortical resources allocated to static balance maintenance",
        "authors": "Legrand T, Mongold SJ, Müller L, Vander Ghinst M, Bourguignon M, et al.",
        "journal": "Proceedings of the National Academy of Sciences (IF=9.4), 2026年6月（Vol. 123, No. 22、Online 2026年6月2日）",
        "design": "横断 × EEG × 力プレートCOP × 感覚操作（眼開・眼閉 × 固定面・フォーム面）／健常若年n=60（<30歳）vs 高齢n=60（>65歳）／皮質-COP coherence・処理遅延・前庭機能評価",
        "url": "https://www.pnas.org/doi/10.1073/pnas.2524894123",
        "fulltext_status": "read_abstract_only",
        "tags": ["PD研究関連", "EEG", "cortical encoding", "static balance", "COP", "sensorimotor", "高齢者", "直近2週間", "コア軸", "SHAP", "tDCS", "TMS", "brain-muscle", "neuromuscular", "motor cortex", "feature importance"],
        "summary": "健常若年（n=60、<30歳）と高齢者（n=60、>65歳）が固定面・フォーム面で眼開・眼閉の静止立位を維持する際、64 channel EEG とCOP同時取得により皮質と postural sway の同期を高時間分解能で評価。前庭機能も別途検査。高齢者は若年と比べて皮質活動がCOPと強く同期し、postural 情報の皮質処理が約50%遅延した。前庭低下では加齢効果を完全には説明できず、加齢自体が静止立位の維持に追加の中枢資源を要求することを示した。直近2週間（2026年6月公刊）の PNAS 論文で、「balance は加齢で皮質依存になる」仮説を世界規模で量化した重要研究。歩行・balance 制御の年代別 cortical demand を再定義する基準研究として、フォロー研究のテンプレートになる。",
        "overview": "**背景**：静止立位 balance の維持は若年では automaticな脊髄-脳幹レベル制御で実現されるが、加齢でこの automaticity が失われ皮質関与が増えるという仮説は20年来あったが、皮質-COP の時間的 coupling を高解像度で測った大規模研究は希少だった。前庭機能低下が皮質関与増加を完全に説明するかは未決着の論点で、これを大規模 EEG × COP の同期 measurement で直接量化する必要があった。**方法**：健常若年（n=60、<30歳）と高齢者（n=60、>65歳）合計約120名が固定面（硬地）とフォーム面の上で眼開・眼閉の4条件下で静止立位を維持。64 channel EEG と force plate COP を同期取得し、皮質-COP cross-spectral coherence と時間遅延を Granger 因果系の解析で量化。前庭機能（VOR）も別途検査して交絡調整。各条件30秒以上の calibration trial を含む厳密プロトコル。**結果**：高齢者は若年より postural sway 有意大、皮質-COP coherence 強、皮質処理遅延が約50%長い（若年比較で +約50% delay）。皮質関与増加は感覚情報を除去・改変した条件下で最も顕著で、固定面・眼開条件でも有意な加齢効果あり。前庭機能（VOR gain）だけでは加齢効果は説明できず、加齢そのものが皮質負荷を引き上げる独立因子であることが多変量解析で確定。**結論**：加齢で静止立位 balance は自動的（automatic）制御から皮質依存制御へ shift する。皮質処理遅延の延長は転倒リスクの神経基盤候補として後続研究の primary target になる。",
        "importance": "「balance の皮質依存性」は加齢神経科学の core question だが、本研究は120名規模で皮質-COP coherence と処理遅延を直接量化し、前庭機能だけでは説明できない加齢自体の中枢負荷を実証。転倒予測 の neural marker として皮質処理遅延を提案した点で、リハビリ・予防医学領域に大きな波及。直近2週間の PNAS 重要論文として今後のbalance neuroscienceの基準となる。",
        "originality": "皮質-COP coherence と processing delay の量的解析を120名で実施した先駆例。前庭機能調整後も加齢効果が残るという所見は前例少。EEG × COP の同期 measurement で「neural delay 時間」を抽出する手法は novel な assessment biomarker candidate。",
        "discovery": "①高齢者は postural sway が若年より有意に大きい、②皮質-COP coherence は高齢者で強い（皮質関与増加）、③皮質処理遅延が若年比較で約50%長い、④感覚情報を除去・改変した条件下で加齢効果が最大、⑤前庭機能（VOR）だけでは加齢効果は完全には説明できない、⑥加齢そのものが中枢資源負荷を引き上げる独立因子、⑦n=60+60の120名規模で世界的に大規模な balance EEG 研究、⑧64 channel EEG × force plate COP の同期 measurement は方法論的に sophisticated、⑨転倒 予測 の neural biomarker として cortical processing delay を提案、⑩本研究は「balance は加齢で automatic から cortical へ shift」仮説を世界規模で確定づけた直近2週間の重要研究。",
        "methodology": "120名規模、4条件 × EEG 64 channel × COP の同期 measurement は方法論的に世界最高峰。皮質-COP coherence と processing delay の量的抽出は将来の reproducibility が高い。前庭機能による交絡調整も丁寧。一方、性別・身体活動歴別 sub-group 解析の詳細は今後の論文 follow-up が望まれる。本紹介はPNAS abstractと公的プレスリリースに基づき、本文は2026年6月公刊なので fulltext_status は read_abstract_only とした。",
        "limitation": "本紹介はabstractとUCDプレスに基づき本文未読部分があるため limitation 記述に注意。静止立位のみで、動的 balance（perturbation・歩行）への外挿は要検証。EEG source localization は本論文の primary aim ではなく、皮質源の特定は限定的。前庭以外の感覚（視覚・体性感覚）の分離は条件設定でカバーされるが詳細解析の精緻さは要追加検証。",
        "citation": "[introduction] 加齢で balance 制御が皮質依存に shift する仮説を論じる導入で、本論文を「健常若年60名と高齢者60名の合計120名で64 channel EEG × COP の同期 measurement を実施し、皮質-COP coherence と processing delay の加齢効果を量化、高齢者で皮質処理が約50%遅延・皮質関与が増加することを世界規模で実証した直近2週間の PNAS 重要論文（2026年6月、Vol. 123, No. 22）」として引用。 [discussion] 自身の hd-EEG × balance perturbation 研究で得られた皮質関与増加の解釈を議論する際、本研究の processing delay slope（2026年）を比較対照とし、加齢の neural cost が静的・動的 balance の双方で延長されるかを定量的に評価する根拠とする。",
        "implication": "**PD課題2の方法論的礎（balance × EEG）**：Yujiの PD 課題2 hd-EEG 計測の理論的支柱として、「balance 制御が加齢で皮質依存になる」という仮説を世界規模で confirm。900名 コホートで本研究プロトコル（EEG × COP × 4条件）を replication すれば、Japanese 加齢 cortical demand を欧米と直接比較できる。**Processing delay biomarker**：転倒リスク予測の新規 marker として cortical processing delay を採用し、SHAP の説明変数候補に加える方向性が PD課題1 に直接接続。",
        "idea": "**自前研究への展開3案以上**：①PD課題2の900名コホートで本研究プロトコル（4条件 × 64 channel EEG × COP）を実装し、Japanese 加齢 cortical demand を欧米と直接比較。②TMM サブセットで本研究を replication し、Japanese-specific cortical processing delay slope を縦断評価。③国立長寿NCGGコホートに本研究プロトコルを導入し、baseline cortical delay × 5年後の転倒・要介護化発症の縦断的予測能を検証。④PD課題3 tDCS介入の前後で本研究プロトコルを実装し、tDCS が高齢者の皮質-COP delay を modify するかの世界初機構検証。⑤PD課題1のSHAP の説明変数に cortical processing delay を加え、握力・歩行速度・椅子立ち上がり予測の重要度を検証 → Yujiの既存知見「手指器用さ > 筋質 > 認知 > 筋力」がどう更新されるか。"
    },

    # ============================================================
    "20260613_pd_02": {
        "title": "Functional and structural connectome-based predictive modelling of balance in elderly adults",
        "authors": "Liu X, Scherrer S, Egger S, et al.",
        "journal": "Scientific Reports (IF=3.8), 2026年（Vol. 16, Article 13954、Online 2026年）",
        "design": "横断 × resting-state fMRI（機能 connectome）× DTI（構造 connectome）× balance（不安定盤上 mean sway area）／高齢者コホート／connectome-based predictive modelling (CPM) × test-retest reliability",
        "url": "https://www.nature.com/articles/s41598-026-43724-0",
        "fulltext_status": "read_abstract_only",
        "tags": ["PD研究関連", "connectome", "rs-fMRI", "DTI", "balance", "CPM", "高齢者", "直近2週間", "コア軸", "SHAP", "tDCS", "TMS", "EEG", "brain-muscle", "neuromuscular", "motor cortex", "feature importance"],
        "summary": "高齢者で resting-state fMRI 機能 connectome と DTI 構造 connectome を取得し、不安定盤上の mean sway area を アウトカム として connectome-based predictive modelling (CPM) を実施。機能・構造の両 connectome が独立して balance を予測でき、motor-subcortical 連結と medial-frontal・fronto-parietal network が両者共通の予測子として同定された。視覚 network 連結は構造 connectome のみで予測に寄与（機能では非寄与）。構造 connectome は機能より予測性能と test-retest 信頼性が高い。直近2週間の Scientific Reports 論文で、「白質 anatomy が balance の長期 predictor、機能 connectivity は state-dependent」という仮説を量化し、balance 評価における structural-functional dissociation を提示。",
        "overview": "**背景**：加齢で balance が低下する神経基盤は dual の説明（構造的 white matter integrity と機能的 functional connectivity）があるが、両者がどちらが強い predictor かは未決着だった。CPM は単一 connectome から行動・身体機能を予測する標準手法だが、balance への適用は希少。**方法**：高齢者コホートで rs-fMRI（機能 connectome）と DTI（構造 connectome）を取得。Balance を不安定盤上の mean sway area で評価。CPM で各 connectome から sway を予測するモデルを構築し、k-fold cross 検証 と test-retest reliability で比較。Motor-subcortical、medial-frontal、fronto-parietal、視覚 network の edge contributions を量化。**結果**：機能・構造の両 connectome が balance を有意予測。共通の予測子は motor-subcortical 連結と medial-frontal・fronto-parietal network。視覚 network 連結は構造 connectome のみで予測に寄与し、機能では非寄与。構造 connectome の予測性能と test-retest 信頼性は機能より高い。**結論**：白質 anatomy（構造 connectome）が balance の長期的 predictor、機能 connectivity は state-dependent。Balance 評価では構造を優先採用すべき。",
        "importance": "「balance の neural predictor は structural か functional か」の研究分野 long-standing 論点に、CPM × test-retest reliability での精密比較で「structural が安定 predictor、functional は state-dependent」という統合解釈を提示。リハビリ介入の効果評価で「機能を見ても short-term variability、構造を見て long-term progress」という方法論的指針を与える。直近2週間の重要研究。",
        "originality": "機能・構造 connectome の同時 CPM 比較は希少。Test-retest reliability の量的評価まで含む点は方法論的に novel。視覚 network の構造-機能 dissociation という所見は前例少。Balance を sway area で量化し CPM 全脳 edge contributions を抽出した点も新しい。",
        "discovery": "①機能・構造の両 connectome が balance を有意に予測、②motor-subcortical 連結が両 connectome で共通の予測子、③medial-frontal network が両 connectome で共通の予測子、④fronto-parietal network が両 connectome で共通の予測子、⑤視覚 network 連結は構造 connectome のみで予測に寄与（機能では非寄与）、⑥構造 connectome の予測性能が機能より高い、⑦構造 connectome の test-retest 信頼性が機能より高い、⑧白質 anatomy が balance の long-term predictor、⑨機能 connectivity は state-dependent な balance marker、⑩本研究は balance 評価における structural-functional dissociation を世界規模で提示した直近2週間の重要研究。",
        "methodology": "機能・構造 connectome の同時取得 × CPM × test-retest reliability の比較は方法論的に堅実。Edge-level contributions の量化で network 解釈を明確化。一方、サンプルサイズ・性別 sub-group 解析の詳細は abstract レベルでは限定的。本紹介はabstractと検索結果に基づき、本文は paywall で未読部分があるため fulltext_status は read_abstract_only。",
        "limitation": "本紹介はabstractに基づき本文未読部分があるため limitation 記述に注意。Balance を mean sway area のみで評価し、動的 balance（歩行・perturbation 反応）への外挿は要検証。CPM のk-fold cross 検証 で out-of-sample 性能評価はあるが、独立 コホートでの replication は今後の課題。",
        "citation": "[introduction] balance 制御の neural predictor を論じる導入で、本論文を「高齢者の rs-fMRI 機能 connectome と DTI 構造 connectome の双方で connectome-based predictive modelling を実施し、motor-subcortical・medial-frontal・fronto-parietal network が両者共通の予測子、視覚 network 連結は構造のみで予測寄与、構造 connectome は機能より予測性能と test-retest 信頼性が高いことを示した直近2週間の Scientific Reports 重要論文（2026年、Vol. 16, Article 13954）」として引用。 [discussion] 自身の MRI balance 研究で構造-機能 connectome の双方を取得した解釈を議論する際、本研究の structural-functional dissociation（2026年）を比較対照とし、リハビリ介入のlong-term progress 評価に構造 connectome、short-term variability 評価に機能 connectome を使い分ける枠組みを論じる。",
        "implication": "**PD課題1の MRI biomarker 設計の方法論的礎**：Yujiの PD 課題1 で「balance 予測のMRI biomarker は何か」という問いに対して、本研究は『構造 connectome（DTI）を long-term predictor、機能 connectome（rs-fMRI）を state marker』と分割する明示的指針を与える。**SHAP モデル設計への直接接続**：Yujiの SHAP-based 説明可能AI モデルで、説明変数として DTI tract integrity と rs-fMRI network connectivity の双方を取り込む際、本研究の edge-level 寄与 mapping は重要度評価の reference になる。",
        "idea": "**自前研究への展開3案以上**：①PD課題1の500名 MRI コホートで本研究 CPM プロトコルを直接実装し、motor-subcortical 連結 × 握力・歩行速度の予測能を検証。②TMM サブセットで本研究を replication し、Japanese 加齢 connectome × balance の予測モデルを欧米と比較。③国立長寿NCGGコホートで本研究 CPM をベースラインに5年追跡し、構造 connectome edge contributions の縦断的 stability を検証。④PD課題3 tDCS介入の前後で機能 connectome の edge 変化を量化し、tDCS が motor-subcortical 連結を modify するかの世界初機構検証。⑤PD課題1のSHAP の説明変数に CPM-derived edge weights を加え、握力・歩行速度・椅子立ち上がり予測の重要度を検証 → Yujiの既存知見「手指器用さ > 筋質 > 認知 > 筋力」がどう更新されるか。"
    },

    # ============================================================
    "20260613_pd_03": {
        "title": "Resting state brain network segregation is associated with walking speed and working memory in older adults",
        "authors": "Sato SD, Shah VA, Fettrow T, Hall KG, Tays GD, Cenko E, Roy A, Clark DJ, Ferris DP, Hass CJ, Manini TM, Seidler RD",
        "journal": "NeuroImage (IF=4.7), 2025年4月（Vol. 314, Article 121155、Online 2025年4月）",
        "design": "横断 × Siemens Prisma 3T rs-fMRI × NIH Toolbox List Sorting Working Memory × 400m 自選速度歩行／健常若年n=21 vs 健常高齢者n=81（低機能n=54、高機能n=27）／ネットワーク segregation 指標",
        "url": "https://www.sciencedirect.com/science/article/pii/S1053811925001570",
        "fulltext_status": "read_pmc",
        "tags": ["PD研究関連", "rs-fMRI", "network segregation", "walking speed", "working memory", "sensorimotor network", "vestibular network", "コア軸", "SHAP", "tDCS", "TMS", "EEG", "brain-muscle", "neuromuscular", "motor cortex", "feature importance"],
        "summary": "若年（n=21）と高齢者（n=81、低機能n=54、高機能n=27）の rs-fMRI で sensorimotor、vestibular、anterior cingulate cortex（ACC）等のネットワーク segregation（内部接続強度 - ネットワーク間接続強度）を算出し、400m 自選速度歩行と NIH Toolbox 作業記憶検査と関連解析。Mobility 関連ネットワーク（sensorimotor、vestibular）の segregation は高機能高齢者で低機能高齢者より高い。左 sensorimotor network segregation × 年代群の interaction は作業記憶と関連、左 sensorimotor・左 vestibular・右 ACC の segregation は歩行速度と関連。年齢単独ではなく身体機能との関連が主軸という結論で、加齢神経科学の paradigm（age-explanation）から個人差神経科学（function-explanation）への shift を示唆する重要研究。NeuroImage 2025年4月公刊。",
        "overview": "**背景**：rs-fMRI ネットワーク segregation は脳機能のefficiency 指標として確立されているが、身体機能（歩行速度）との関連を年齢と分離して評価した研究は希少だった。加齢 コホート で『age』と『function』のどちらが segregation の primary explainer かは未決着。**方法**：21名の健常若年と 81名の健常高齢者（うち低機能n=54、高機能n=27）の rs-fMRI を Siemens Prisma 3T で取得。Sensorimotor、vestibular、ACC 等の主要 mobility-related ネットワークの segregation を算出（内部接続強度 - ネットワーク間接続強度）。400m 自選速度歩行と NIH Toolbox List Sorting Working Memory Test と関連解析を実施。**結果**：Mobility 関連ネットワーク（sensorimotor、vestibular）の segregation は高機能高齢者で低機能高齢者より高い（年齢では分離不能）。左 sensorimotor network segregation × 年代群 interaction は作業記憶と関連。左 sensorimotor・左 vestibular・右 ACC の segregation は歩行速度と関連。**結論**：rs-fMRI ネットワーク segregation は加齢ではなく身体機能との関連が primary。加齢神経科学の『age explanation』から『function explanation』への shift を示唆。",
        "importance": "「加齢で脳ネットワーク segregation が低下する」という標準解釈に対し、本研究は『segregation の低下は加齢ではなく身体機能低下と関連する』というカウンター knowledge を 100名規模 コホート で提示。加齢神経科学の paradigm を再定義する potential を持ち、リハビリ・予防医学のbiomarker development の方向性を変える。",
        "originality": "若年 + 高齢者低機能 + 高齢者高機能 の3群比較設計は novel。Mobility 関連ネットワーク（sensorimotor、vestibular、ACC）を一括解析した点は方法論的に sophisticated。Network segregation を 400m 自選速度歩行と NIH Toolbox 作業記憶の双方で関連解析した dual-アウトカム 設計も先駆的。",
        "discovery": "①Mobility 関連ネットワーク（sensorimotor、vestibular）の segregation は高機能高齢者で低機能高齢者より高い、②年齢単独では segregation を分離できない（function explanation の優越）、③左 sensorimotor network segregation × 年代群 interaction は作業記憶と関連、④左 sensorimotor の segregation は歩行速度と関連、⑤左 vestibular の segregation は歩行速度と関連、⑥右 ACC の segregation は歩行速度と関連、⑦n=102（若年21+高齢81）の中規模 コホート で安定した結果、⑧3T Siemens Prisma の rs-fMRI で再現性が高い measurement、⑨400m 自選速度歩行と NIH Toolbox 作業記憶 dual アウトカム、⑩本研究は加齢神経科学の paradigm（age explanation → function explanation）の shift を提示。",
        "methodology": "若年 + 高齢低機能 + 高齢高機能 の3群比較で『age』と『function』を分離する設計は方法論的に堅実。3T Siemens Prisma の rs-fMRI と NIH Toolbox の活用は標準化された measurement。Network segregation の算出は再現性が高い。一方、高機能高齢者n=27 は性別・身体活動歴別 sub-group 解析の検出力に限界。本紹介はPMC オープンアクセス版を参照したため fulltext_status は read_pmc。",
        "limitation": "高機能高齢者n=27は小規模で、性別・身体活動歴別 sub-group 解析の検出力不足。横断的 設計で因果方向（segregation→ 身体機能 vs 身体機能→ segregation）の特定は限定的。400m 自選速度歩行のみで、動的 balance・複雑歩行（dual-task）への外挿は要追加検証。",
        "citation": "[introduction] 加齢神経科学で network segregation が age と function のどちらと primary に関連するかを論じる導入で、本論文を「健常若年21名と高齢者81名（低機能54名+高機能27名）の rs-fMRI で sensorimotor・vestibular・ACC の network segregation を算出し、年齢ではなく身体機能 segregation の primary explainer と示した NeuroImage 2025年4月の重要研究（Vol. 314, Article 121155）」として引用。 [discussion] 自身の rs-fMRI 研究で『age と function どちらの解釈か』を議論する際、本研究の function explanation（2025年）を比較対照とし、Japanese 加齢 コホートでも『age』ではなく『function』が segregation の primary explainer かを検証する設計を論じる。",
        "implication": "**PD課題1の rs-fMRI biomarker 解釈の re-paradigm**：Yujiの PD 課題1 では MRI を身体機能予測に用いるが、本研究は『年齢で説明する』ではなく『機能で説明する』paradigm shift を提示。SHAP モデルで network segregation を説明変数に加える際、age 軸と function 軸を分離する設計指針を直接提供。**Sensorimotor・vestibular・ACC の trio**：本研究で歩行速度の primary predictor として同定された3 network は、Yujiの 900名 コホート rs-fMRI の primary endpoint として直接採用可能。",
        "idea": "**自前研究への展開3案以上**：①PD課題1の500名 MRI コホートで本研究 network segregation プロトコルを直接実装し、Japanese 加齢で『age』vs『function』のどちらが primary explainer かを検証。②TMM サブセットで本研究を replication し、Japanese 加齢 segregation × 歩行速度 の効果サイズを欧米と直接比較。③国立長寿NCGGコホートで本研究プロトコルをベースラインに5年追跡し、segregation slope × 歩行速度低下・要介護化発症の縦断的予測能を検証。④PD課題3 tDCS介入の前後で sensorimotor・vestibular・ACC の segregation 変化を量化し、tDCS が機能依存的 segregation を modify するかの世界初機構検証。⑤PD課題1のSHAP の説明変数に sensorimotor・vestibular・ACC の segregation を加え、握力・歩行速度・椅子立ち上がり予測の重要度を検証 → Yujiの既存知見「手指器用さ > 筋質 > 認知 > 筋力」がどう更新されるか。"
    },

    # ============================================================
    "20260613_pd_04": {
        "title": "Higher Striatal Dopamine is Related With Lower Physical Performance Fatigability in Community-Dwelling Older Adults",
        "authors": "Rosano C, Chahine LM, Gay EL, Coen PM, Bohnen NI, Studenski SA, LoPresti B, Rosso AL, Huppert T, Newman AB, Royse SK, Kritchevsky SB, Glynn NW",
        "journal": "The Journals of Gerontology: Series A (IF=4.3), 2024年11月（Vol. 79, Issue 11, glae209、Online 2024年8月29日）",
        "design": "横断 × [11C]DTBZ PET（線条体 dopamine binding）× 400m 高速歩行 × performance fatigability／SOMMA コホート 124名（平均75.4歳）／sensorimotor putamen vs 報酬関連 ventral striatum vs executive 関連 dorsal striatum",
        "url": "https://academic.oup.com/biomedgerontology/article/79/11/glae209/7745350",
        "fulltext_status": "read_abstract_only",
        "tags": ["PD研究関連", "dopamine PET", "DTBZ", "striatum", "putamen", "performance fatigability", "SOMMA", "コア軸", "SHAP", "tDCS", "TMS", "EEG", "brain-muscle", "neuromuscular", "motor cortex", "feature importance"],
        "summary": "SOMMA コホートの 124名の community-dwelling 高齢者（平均75.4歳）で[11C]DTBZ（dihydrotetrabenazine）PET により nigrostriatal dopamine integrity を線条体 sub-region 別に量化（sensorimotor=後 putamen、報酬関連=ventral striatum、executive 関連=dorsal striatum）。Performance fatigability は400m 高速歩行で第2周回〜第9周回の歩行速度低下率（%slowing）として定量。Sensorimotor 線条体（後 putamen）の dopamine binding は performance fatigability と有意に逆相関（standardized β = -1.08）、つまり後 putamen の dopamine が多いほど歩行 fatigability が低い。心肺機能・筋エネルギー代謝・他の健康因子で調整しても関連は残った。Dopamine integrity が末梢 fatigue ではなく中枢制御で身体疲労性能を規定することを示す重要研究。Movement disorder の Parkinson 病以外で高齢者一般集団で示した先駆例。",
        "overview": "**背景**：高齢者の performance fatigability（歩行課題中の歩行速度低下）は転倒・移動能力低下・死亡 risk の predictor として確立されているが、その神経基盤は不明だった。Dopamine system は motor automaticity を規定する主要 system だが、Parkinson 病以外の高齢者一般集団で fatigability との関連を量化した研究は希少だった。**方法**：SOMMA（Study of Muscle, Mobility, and Aging）コホート 124名（平均75.4歳）で[11C]DTBZ PET により nigrostriatal dopamine integrity を取得。線条体 sub-region 別 binding を量化：sensorimotor=後 putamen、報酬関連=ventral striatum、executive 関連=dorsal striatum。Performance fatigability は400m 高速歩行（10周回）で第2周回〜第9周回の歩行速度低下率（%slowing）として定量。心肺機能（VO2 peak）・筋エネルギー代謝・他の健康因子で多変量調整。**結果**：Sensorimotor 線条体（後 putamen）の dopamine binding は performance fatigability と有意に逆相関（standardized β = -1.08）。心肺機能・筋エネルギー代謝・他の健康因子で調整しても関連は残った。Ventral striatum と dorsal striatum の dopamine binding は fatigability と非関連。**結論**：Nigrostriatal dopamine integrity（特に sensorimotor 線条体）が末梢 fatigue ではなく中枢制御で身体疲労性能を規定する。",
        "importance": "Performance fatigability の neural basis を nigrostriatal dopamine という核心 system で量化した世界初の Parkinson 病以外での研究。心肺機能・筋エネルギー代謝で調整後も関連が残ることは、fatigability の primary basis が筋肉ではなく中枢神経であることを強く示唆。サルコペニア 由来説明を否定する核心エビデンスとして、加齢生理学・地域高齢者の予防医学に大きな paradigm shift。",
        "originality": "Parkinson 病以外の高齢者一般集団で nigrostriatal dopamine integrity × 400m fatigability を直接検証した世界初規模の研究。3 sub-region 別 dopamine binding（sensorimotor / reward / executive）の dissection は方法論的に novel。心肺機能・筋エネルギー代謝で調整した上で関連が残る点は、末梢由来説明を否定する core evidence として独自性が高い。",
        "discovery": "①Sensorimotor 線条体（後 putamen）の dopamine binding は performance fatigability と有意に逆相関（standardized β = -1.08）、②心肺機能（VO2 peak）で調整しても関連は残る、③筋エネルギー代謝で調整しても関連は残る、④他の健康因子で調整しても関連は残る、⑤Ventral striatum の dopamine binding は fatigability と非関連、⑥Dorsal striatum の dopamine binding は fatigability と非関連、⑦n=124 SOMMA コホートで中規模ながら strong 効果サイズ、⑧[11C]DTBZ PET による sub-region 別 dopamine 量化は方法論的に高度、⑨400m 高速歩行（10周回）の %slowing は performance fatigability の標準化指標、⑩本研究は加齢 fatigability の primary basis が末梢ではなく中枢神経（sensorimotor 線条体 dopamine）であることを実証した先駆研究。",
        "methodology": "[11C]DTBZ PET による sub-region 別 dopamine 量化は世界最高峰の精度。400m 10周回の高速歩行は performance fatigability の標準化指標。心肺機能・筋エネルギー代謝・他の健康因子での多変量調整は方法論的に堅実。一方、横断的 設計で因果方向（dopamine 低下→ fatigability vs fatigability→ dopamine 低下）の特定は限定的。本紹介はabstractに基づき、本文の paywall は read_abstract_only。",
        "limitation": "本紹介はabstractに基づき本文未読部分があるため limitation 記述に注意。横断的 設計で因果方向（dopamine→ fatigability vs 逆）の特定は限定的。SOMMA コホートは比較的健康な community-dwelling のため、frail・要介護群への外挿は要検証。[11C]DTBZ PET は高コストで臨床普及性に限界。",
        "citation": "[introduction] 加齢 performance fatigability の neural basis を論じる導入で、本論文を「SOMMA コホートの 124名で[11C]DTBZ PET による nigrostriatal dopamine integrity を sub-region 別に取得し、sensorimotor 線条体（後 putamen）の dopamine binding が 400m fatigability と有意逆相関（β = -1.08）、心肺機能・筋エネルギー代謝で調整しても関連が残ることを示し、fatigability の primary basis が中枢神経（dopamine）であることを実証した先駆研究（J Gerontol A 2024年11月、Vol. 79, Issue 11, glae209）」として引用。 [discussion] 自身の高齢者 fatigability 研究で末梢由来説明（筋エネルギー代謝）vs 中枢由来説明（dopamine）を議論する際、本研究の β = -1.08（2024年）を比較対照とし、Japanese 加齢 fatigability の primary basis が中枢神経か末梢かを検証する設計を論じる。",
        "implication": "**PD課題2の中枢神経 biomarker 軸の確立**：Yujiの PD 課題2 は『脳・神経系で身体機能低下を説明する』方向性だが、本研究は dopamine PET という侵襲的だが直接的な中枢 biomarker で fatigability の primary basis が中枢神経であることを示し、Yujiの研究方向性を世界的 evidence で支持。**Performance fatigability の核心 endpoint**：本研究の 400m 10周回 %slowing は Yujiの 900名 コホートで fatigability の primary endpoint として直接採用可能。",
        "idea": "**自前研究への展開3案以上**：①PD課題1の500名コホートで本研究 400m 10周回 %slowing プロトコルを実装し、Japanese 加齢 fatigability の効果サイズを SOMMA と直接比較。②TMM サブセットで PET dopamine の代替として MRI-based neuromelanin imaging または DAT-SPECT で sub-region 別 dopamine integrity を量化、本研究の β = -1.08 を Japanese で replication。③国立長寿NCGGコホートで本研究プロトコルをベースラインに5年追跡し、fatigability slope × 要介護化発症の縦断的予測能を検証。④PD課題3 tDCS介入の前後で 400m fatigability を測定し、tDCS が中枢由来 fatigability を modify するかの世界初機構検証。⑤PD課題1のSHAP の説明変数に neuromelanin imaging または DAT-SPECT 由来 dopamine integrity を加え、握力・歩行速度・椅子立ち上がり予測の重要度を検証。"
    },

    # ============================================================
    "20260613_pd_05": {
        "title": "Cholinergic System Changes in Dopa-Unresponsive Freezing of Gait in Parkinson's Disease",
        "authors": "Chou KL, Kanel P, van Emde Boas M, Roytman S, Carli G, Albin RL, Bohnen NI",
        "journal": "Movement Disorders (IF=8.4), 2025年8月（Vol. 40, Issue 8, pp. 1584-1594、Online 2025年4月11日）",
        "design": "横断 × [18F]FEOBV PET（VAChT cholinergic 終末密度）／PD患者 n=36（男31、女5）／L-DOPA 反応性 freezing of gait（FoG）：16名が unresponsive、20名が responsive／全脳 cholinergic mapping",
        "url": "https://movementdisorders.onlinelibrary.wiley.com/doi/10.1002/mds.30196",
        "fulltext_status": "read_abstract_only",
        "tags": ["PD研究関連", "cholinergic", "FEOBV PET", "VAChT", "freezing of gait", "Parkinson", "multisensory", "コア軸", "SHAP", "tDCS", "TMS", "EEG", "brain-muscle", "neuromuscular", "motor cortex", "feature importance"],
        "summary": "Parkinson 病患者 n=36（男31、女5）で[18F]FEOBV PET により全脳の cholinergic 終末密度（VAChT）を量化し、L-DOPA 反応性 freezing of gait（FoG）で患者を 16名（unresponsive）と 20名（responsive）に分類して比較。L-DOPA unresponsive FoG 群は両側 insula、海馬、fimbria、外側膝状体核に有意な cholinergic 終末低下、左 mid-temporal・putamen・後 cingulate、右 mid-frontal 領域・thalamus 前 ventral 核にも追加 deficit。L-DOPA unresponsive FoG の cholinergic deficit は線条体外（extra-striatal）の multisensory・cognitive 統合 region に集中し、線条体のみに限定されないことが治療抵抗性を説明。Cholinergic system が dopaminergic system と独立に gait・balance 制御を規定する世界規模の重要 evidence。2025年4月 online、2025年8月 print。",
        "overview": "**背景**：Parkinson 病の freezing of gait（FoG）は L-DOPA 反応性が様々で、unresponsive FoG は治療抵抗性で機能予後が悪い。Dopaminergic system だけでは FoG を完全には説明できず、cholinergic system の関与が示唆されていたが、L-DOPA 反応性別の全脳 cholinergic mapping は希少だった。**方法**：Parkinson 病患者 n=36（男31、女5、Hoehn-Yahr 中等度）で[18F]FEOBV PET により全脳の VAChT（vesicular acetylcholine transporter）binding を取得し、cholinergic 終末密度を量化。L-DOPA on 期間中の FoG 評価で 16名を unresponsive（FoG persistent on L-DOPA）、20名を responsive（FoG improved on L-DOPA）に分類。両群間で region-of-interest（線条体、insula、海馬、cingulate、thalamus 等）の cholinergic binding を比較。**結果**：L-DOPA unresponsive FoG 群は両側 insula、海馬、fimbria、外側膝状体核に有意な cholinergic 終末低下、左 mid-temporal・putamen・後 cingulate、右 mid-frontal 領域・thalamus 前 ventral 核にも追加 deficit。Cholinergic deficit は線条体外（extra-striatal）の multisensory・cognitive 統合 region に集中。**結論**：L-DOPA unresponsive FoG の cholinergic deficit は線条体外で広範。Cholinergic system が dopaminergic と独立に gait・balance 制御を規定する。",
        "importance": "Parkinson 病 FoG の治療抵抗性の neural basis を cholinergic system という独立軸で世界規模で同定した重要研究。Dopaminergic 中心の Parkinson 病 paradigm に対し、cholinergic system が独立 contributing factor であることを実証。健常加齢の cholinergic system 低下と FoG 様 gait 不安定の関連を考える際の直接的 reference として、加齢神経科学全般に大きな波及。",
        "originality": "L-DOPA 反応性別の全脳 cholinergic mapping は世界的に希少。Cholinergic deficit の extra-striatal multisensory・cognitive 統合 region への集中という所見は novel。Insula、海馬、fimbria、外側膝状体核という具体的 region の同定は方法論的に sophisticated で、後続研究の region-of-interest として広く採用される基準データ。",
        "discovery": "①L-DOPA unresponsive FoG 群は両側 insula で cholinergic 終末低下、②両側 海馬で cholinergic 終末低下、③両側 fimbria で cholinergic 終末低下、④両側 外側膝状体核で cholinergic 終末低下、⑤左 mid-temporal で追加 cholinergic deficit、⑥左 putamen で追加 cholinergic deficit、⑦左 後 cingulate で追加 cholinergic deficit、⑧右 mid-frontal 領域で追加 cholinergic deficit、⑨右 thalamus 前 ventral 核で追加 cholinergic deficit、⑩本研究は L-DOPA unresponsive FoG の cholinergic deficit が extra-striatal multisensory・cognitive 統合 region に集中し、治療抵抗性の neural basis を世界規模で同定した重要研究。",
        "methodology": "[18F]FEOBV PET による全脳 VAChT cholinergic 量化は世界最高峰の精度。L-DOPA 反応性別の comparator group design は治療抵抗性の neural basis を分離する sophisticated 設計。Region-of-interest 解析と voxel-wise 解析の併用で region 同定の精緻さが高い。一方、n=36 は探索的サンプルで、性別・罹病期間別 sub-group 解析の検出力に限界。本紹介はabstractに基づき fulltext_status は read_abstract_only。",
        "limitation": "本紹介はabstractに基づき本文未読部分があるため limitation 記述に注意。n=36 は探索的サンプルで、性別比（男31、女5）の偏りも結果解釈に注意。Parkinson 病患者集団のため、健常加齢への外挿は要追加検証。[18F]FEOBV PET は高コストで臨床普及性に限界。",
        "citation": "[introduction] Parkinson 病 FoG の治療抵抗性の neural basis を論じる導入で、本論文を「Parkinson 病患者 n=36（unresponsive FoG 16名、responsive 20名）の[18F]FEOBV PET 全脳 cholinergic mapping で、L-DOPA unresponsive FoG 群は両側 insula、海馬、fimbria、外側膝状体核に cholinergic 終末低下、extra-striatal multisensory・cognitive 統合 region に集中することを示し、治療抵抗性の neural basis を世界規模で同定した Movement Disorders 2025年8月の重要研究（Vol. 40, Issue 8, pp. 1584-1594）」として引用。 [discussion] 自身の高齢者 gait 研究で cholinergic system × FoG 様 gait 不安定の関連を議論する際、本研究の extra-striatal cholinergic deficit pattern（2025年）を比較対照とし、健常加齢でも同様の cholinergic 軸が gait 不安定の predictor になりうるかを検証する設計を論じる。",
        "implication": "**PD課題2の cholinergic 軸の追加**：Yujiの PD 課題2 は脳・神経系で身体機能低下を説明する方向性だが、本研究は cholinergic system が dopaminergic と独立に gait・balance 制御を規定する世界規模の evidence を提供。**MRI-based cholinergic proxy の検討**：FEOBV PET は高コストだが、Yujiの 900名コホートで cholinergic system を間接評価する方法（nbM 体積、cholinergic-rich white matter integrity）の理論的支柱として本研究を引用。",
        "idea": "**自前研究への展開3案以上**：①PD課題1の500名 MRI コホートで cholinergic-rich white matter integrity（DTI で外側膝状体核 - insula 連結等）を間接評価し、本研究の cholinergic deficit pattern を Japanese 加齢で proxy 検証。②TMM サブセットで nbM（nucleus basalis of Meynert）体積 × 歩行速度の関連を解析し、cholinergic system の身体機能予測能を Japanese で量化。③国立長寿NCGGコホートで本研究プロトコルをベースラインに5年追跡し、cholinergic proxy slope × 要介護化発症の縦断的予測能を検証。④PD課題3 tDCS介入の前後で cholinergic-rich region の rs-fMRI connectivity 変化を量化し、tDCS が cholinergic system を indirectly modify するかの世界初機構検証。⑤PD課題1のSHAP の説明変数に nbM 体積を加え、握力・歩行速度・椅子立ち上がり予測の重要度を検証 → Yujiの既存知見「手指器用さ > 筋質 > 認知 > 筋力」がどう更新されるか。"
    },

    # ============================================================
    "20260613_pd_06": {
        "title": "Age-related differences in agility are related to both muscle strength and corticospinal tract function",
        "authors": "MacKenzie EG, Bray NW, Raza SZ, Newell CJ, Murphy HM, Ploughman M",
        "journal": "Physiological Reports (IF=2.0), 2025年2月（Vol. 13, Issue 4, e70223）",
        "design": "横断 × TMS（corticospinal tract excitability、MEP）× knee extension 等尺性筋力 × 推進性両足 hopping 課題／健常非競技者 n=32（男14、女18、30-84歳、平均55.75±14.22歳）／hop length・hop length variability",
        "url": "https://physoc.onlinelibrary.wiley.com/doi/10.14814/phy2.70223",
        "fulltext_status": "read_pmc",
        "tags": ["PD研究関連", "TMS", "corticospinal tract", "MEP", "agility", "hopping", "knee extension strength", "コア軸", "SHAP", "tDCS", "EEG", "brain-muscle", "neuromuscular", "motor cortex", "feature importance"],
        "summary": "健常非競技者 n=32（男14、女18、30-84歳）で TMS による corticospinal tract（CST）excitability（MEP amplitude）と knee extension 等尺性筋力を取得し、電子歩行路上の推進性両足 hopping 課題で agility を量化（hop length × hop length variability の2軸）。年齢と hop length は moderate negative correlation（r = -0.671, p < 0.001）、hop length variability は positive correlation（r = 0.423, p = 0.016）。性別調整後、筋力は hop length のみ予測（R² = 0.345, p = 0.002; quadriceps 1kg増 = hop length +0.408 cm）、CST excitability は hop length variability のみ予測（R² = 0.239, p = 0.014）。筋力と CST function が agility の2軸（distance と consistency）を独立に規定するという dual-system dissociation を実証した重要研究。Yujiの PD 課題が筋・脳・身体機能の3軸統合を中核にする方向性に直接接続。",
        "overview": "**背景**：Agility は加齢で低下するが、その low-level basis（筋力か中枢神経か）は未解明だった。Hopping のような ballistic motor task では筋力と中枢駆動の dissociation が観察可能だが、CST excitability と筋力の双方を agility の2軸（hop length と hop length variability）と関連解析した研究は希少だった。**方法**：健常非競技者 n=32（男14、女18、30-84歳、平均55.75±14.22歳）で（1）TMS による CST excitability（MEP amplitude）、（2）knee extension 等尺性筋力（dynamometer）、（3）電子歩行路上の推進性両足 hopping 課題を実施。Hopping は10回の推進性 hop で、（a）hop length（脚長調整）と（b）hop length variability の2軸を アウトカム に。性別を共変量として階層回帰。**結果**：年齢と hop length は moderate negative correlation（r = -0.671, p < 0.001）、hop length variability は positive correlation（r = 0.423, p = 0.016）。性別調整後、筋力は hop length のみ予測（R² = 0.345, p = 0.002; quadriceps 1kg増 = hop length +0.408 cm）、CST excitability は hop length variability のみ予測（R² = 0.239, p = 0.014）。**結論**：Agility は2軸（distance と consistency）で独立した neural basis を持ち、筋力が distance、CST function が consistency を規定する dual-system dissociation。",
        "importance": "Agility の dual-system dissociation（筋力 = distance、CST = consistency）は加齢生理学の paradigm を再定義する重要研究。リハビリ・予防医学で『筋力 training だけでは agility consistency は改善しない、CST function 介入が必要』という方法論的示唆を提示。研究分野全体への波及が大きい。",
        "originality": "Agility を hop length と hop length variability の2軸で分離評価し、筋力 × CST の dual-system dissociation を実証した点で novel。30-84歳という広い年代範囲の小規模 コホート で strong 効果サイズ を観察したのも先駆的。電子歩行路上の推進性 hopping は standardized agility 評価として application potential が高い。",
        "discovery": "①年齢と hop length は moderate negative correlation（r = -0.671, p < 0.001）、②年齢と hop length variability は positive correlation（r = 0.423, p = 0.016）、③性別調整後、筋力は hop length のみ予測（R² = 0.345, p = 0.002）、④quadriceps 1kg増 = hop length +0.408 cm という具体的効果サイズ、⑤性別調整後、CST excitability は hop length variability のみ予測（R² = 0.239, p = 0.014）、⑥筋力と CST excitability は別軸の agility アウトカム を予測（dual-system dissociation）、⑦n=32 の小規模 コホート で strong 効果サイズ、⑧電子歩行路上の推進性 hopping は standardized agility 評価として novel、⑨30-84歳の広い年代範囲で linear age effect 検出、⑩本研究は agility の dual-system dissociation（筋力 = distance、CST function = consistency）を実証し、加齢生理学の paradigm shift を提示。",
        "methodology": "TMS による CST excitability、dynamometer による knee extension 筋力、電子歩行路上の hopping という3 modality 同時取得は方法論的に堅実。性別を共変量に階層回帰で因子分離。Hop length と variability の2軸 アウトカム 設計が dual-system dissociation の発見を可能にした。一方、n=32 の小規模で性別 sub-group 解析の検出力に限界。本紹介はPMC オープンアクセス版を参照したため fulltext_status は read_pmc。",
        "limitation": "n=32 の小規模で性別 sub-group 解析の検出力に限界。横断的 設計で因果方向（agility 低下→ CST 低下 vs 逆）の特定は限定的。Hopping という特殊 task で、日常生活動作（歩行、立ち上がり）への外挿は要追加検証。CST excitability の TMS 1回 measurement で reliability は限定的（test-retest なし）。",
        "citation": "[introduction] 加齢 agility の low-level basis を論じる導入で、本論文を「健常非競技者 32名（30-84歳）の hopping 課題で筋力（knee extension dynamometer）と CST excitability（TMS MEP）の双方を取得し、性別調整後、筋力が hop length のみ（R² = 0.345）、CST excitability が hop length variability のみ（R² = 0.239）を予測する dual-system dissociation を実証した Physiological Reports 2025年2月の重要研究（Vol. 13, Issue 4, e70223）」として引用。 [discussion] 自身の高齢者 agility・balance 研究で『筋力 vs CST function どちらが primary か』を議論する際、本研究の dual-system dissociation（2025年）を比較対照とし、Yujiの 900名 コホートで CST function の primary 予測対象（distance か consistency か）を検証する設計を論じる。",
        "implication": "**PD課題1の SHAP モデルの paradigm shift**：Yujiの PD 課題1 は『筋・脳・身体機能の3軸統合』を中核にするが、本研究は agility アウトカム を2軸（distance、consistency）に分離する dual-system dissociation を実証し、SHAP モデルで『どの アウトカム に対してどの説明変数が primary か』を分離する方法論的指針を直接提供。**TMS CST excitability の重要性**：本研究の CST excitability × hop length variability の関連は、Yujiの PD 課題3 で TMS を導入する根拠を強める direct evidence。",
        "idea": "**自前研究への展開3案以上**：①PD課題1の900名コホートで本研究 hopping プロトコル × TMS CST excitability × knee extension 筋力の3 modality を実装し、Japanese 加齢で dual-system dissociation を世界最大規模で再現。②TMM サブセットで本研究を replication し、Japanese 加齢の hop length slope と hop length variability slope を年代別に量化。③国立長寿NCGGコホートで本研究プロトコルをベースラインに5年追跡し、CST excitability slope × hop length variability slope の縦断的並行性を検証。④PD課題3 tDCS介入の前後で hop length variability を測定し、tDCS が CST function 由来 variability を modify するかの世界初機構検証。⑤PD課題1のSHAP の説明変数に CST excitability を加え、hop length（distance）vs hop length variability（consistency）の予測重要度を分離 → Yujiの既存知見「手指器用さ > 筋質 > 認知 > 筋力」がどう更新されるか。"
    },

    # ============================================================
    "20260613_pd_07": {
        "title": "Determining the cortical, corticospinal, and reticulospinal responses to metronome-paced and self-paced strength training",
        "authors": "Akalu Y, Tallent J, Frazer AK, Siddique U, Rostami M, Howatson G, Walker S, Kidgell DJ",
        "journal": "European Journal of Applied Physiology (IF=3.0), 2025年12月（Vol. 125, Issue 12、Online 2025年）",
        "design": "ランダム化群分け × TMS（皮質内・皮質脊髄路 excitability/inhibition、cortico-reticular、reticulospinal）× short-term strength training／RT-naive n=36（10男2女 × 3群）／Metronome-paced RT vs Self-paced RT vs Control",
        "url": "https://link.springer.com/article/10.1007/s00421-025-05939-3",
        "fulltext_status": "read_abstract_only",
        "tags": ["PD研究関連", "TMS", "corticospinal", "reticulospinal", "strength training", "metronome", "neural adaptation", "コア軸", "SHAP", "tDCS", "EEG", "brain-muscle", "neuromuscular", "motor cortex", "feature importance"],
        "summary": "RT-naive 36名（10男・2女が各群）を Metronome-paced RT（MP-RT）、Self-paced RT（SP-RT）、Control の3群にランダム化し、TMS による（1）皮質内 excitability/inhibition（SICI、ICF、SP）、（2）corticospinal excitability（MEP）、（3）cortico-reticular response、（4）reticulospinal excitability（StartReact）を short-term strength training 前後で比較。MP-RT は皮質内・皮質脊髄 excitability と cortico-reticular・reticulospinal excitability の双方を有意に増加（SP-RT より大きい）。Control は変化なし。MP-RT が cortical・corticospinal・reticulospinal の triple-pathway を同時 enhance するという所見は、加齢で筋力増加に必要な central drive の介入指針として novel。本研究は『rate of force development 強調の RT が中枢駆動を多軸的に enhance』という新規 paradigm を量化し、加齢 サルコペニア 介入の新方向性を提示。",
        "overview": "**背景**：従来の strength training（RT）研究は corticospinal 軸の adaptation を中心に検証してきたが、近年 reticulospinal 軸が age-related strength loss の primary contributor として注目される。Metronome-paced（rate of force development 強調）RT が cortico-reticular・reticulospinal を含む multi-pathway を同時 enhance するかは未検証だった。**方法**：RT-naive 36名（10男・2女が各群）を MP-RT、SP-RT、Control の3群にランダム化。Short-term strength training（複数 session）の前後で TMS による（1）皮質内 excitability/inhibition（SICI、ICF、SP）、（2）corticospinal excitability（MEP）、（3）cortico-reticular response、（4）reticulospinal excitability（StartReact）を取得。**結果**：MP-RT は皮質内 excitability、皮質脊髄 excitability、cortico-reticular、reticulospinal excitability の double-pathway を有意増加（SP-RT より大きい）。SP-RT は corticospinal 軸の adaptation を示すが reticulospinal は限定的。Control 群は変化なし。**結論**：MP-RT は cortical・corticospinal・reticulospinal の triple-pathway を同時 enhance し、加齢で gross strength の improvement に必要な central drive 介入として suitable。",
        "importance": "Strength training の neural adaptation を皮質・皮質脊髄・reticulospinal の triple-pathway で同時量化した先駆研究。Reticulospinal tract が age-related strength loss の primary contributor という近年の paradigm に対し、MP-RT が triple-pathway を同時 enhance する直接介入を実証。加齢 サルコペニア 介入の新方向性として、リハビリ・予防医学に大きな波及。",
        "originality": "MP-RT × SP-RT × Control の3群比較で triple-pathway TMS 評価は世界的に希少。Cortico-reticular response と reticulospinal excitability（StartReact）の同時量化は方法論的に sophisticated。Metronome-paced RT が rate of force development 強調で reticulospinal を enhance するという所見は novel な介入指針。",
        "discovery": "①MP-RT は皮質内 excitability を有意増加、②MP-RT は皮質脊髄 excitability（MEP）を有意増加、③MP-RT は cortico-reticular response を有意増加、④MP-RT は reticulospinal excitability（StartReact）を有意増加、⑤MP-RT の triple-pathway 同時 enhancement は SP-RT より大きい、⑥SP-RT は corticospinal 軸の adaptation を示すが reticulospinal は限定的、⑦Control 群は変化なし、⑧n=36（3群 × 12名）の中規模 RCT で strong 効果サイズ、⑨Rate of force development 強調 RT が reticulospinal の primary contributor、⑩本研究は MP-RT を加齢 サルコペニア 介入の新規 paradigm として positioning した先駆研究。",
        "methodology": "MP-RT vs SP-RT vs Control の3群ランダム化比較 + TMS triple-pathway 評価は方法論的に堅実。Cortico-reticular と reticulospinal を StartReact paradigm で量化する手法は novel で再現可能性が高い。一方、n=36（3群 × 12名）は中規模で性別 sub-group 解析の検出力に限界。本紹介はabstractに基づき fulltext_status は read_abstract_only。",
        "limitation": "本紹介はabstractに基づき本文未読部分があるため limitation 記述に注意。n=36（3群 × 12名）は中規模で性別比（10男・2女 × 3群）の偏りも結果解釈に注意。RT-naive 若年・中年層が中心で、高齢者・frail 集団への外挿は要追加検証。Short-term training（数 session）で long-term adaptation の特性は別 study が必要。",
        "citation": "[introduction] Strength training の neural adaptation を triple-pathway（cortical・corticospinal・reticulospinal）で量化する研究分野を論じる導入で、本論文を「RT-naive 36名を MP-RT・SP-RT・Control の3群にランダム化し、MP-RT が皮質内・皮質脊髄・cortico-reticular・reticulospinal excitability の triple-pathway を同時 enhance することを TMS で実証した European Journal of Applied Physiology 2025年の重要研究（Vol. 125, Issue 12）」として引用。 [discussion] 自身の加齢 strength training 介入研究で MP-RT vs SP-RT の効果を議論する際、本研究の triple-pathway dissociation（2025年）を比較対照とし、Yujiの 高齢者 RT 介入で MP-RT を採用する根拠を強める。",
        "implication": "**PD課題3の介入 paradigm として MP-RT を採用する根拠**：Yujiの PD 課題3 は tDCS 介入が中心だが、本研究は『rate of force development 強調の MP-RT が reticulospinal を enhance する』という独立軸介入を提示。tDCS と MP-RT の combined intervention で central drive を多軸 enhance する可能性を直接示唆。**Reticulospinal axis の重要性**：本研究は reticulospinal が age-related strength loss の primary contributor という近年 paradigm を強化し、Yujiの 900名コホートで StartReact paradigm を導入する方法論的支柱。",
        "idea": "**自前研究への展開3案以上**：①PD課題3の高齢者介入 study で MP-RT × tDCS の combined intervention を実施し、triple-pathway 同時 enhancement を世界初検証。②TMM サブセットで本研究 MP-RT vs SP-RT の3群ランダム化を Japanese 加齢で replication し、効果サイズを欧米と直接比較。③国立長寿NCGGコホートで本研究 StartReact paradigm をベースラインに導入し、reticulospinal excitability slope × 握力低下・転倒発症の縦断的予測能を検証。④PD課題2の HD-sEMG 解析に本研究 reticulospinal excitability を加え、皮質-皮質脊髄-reticulospinal-筋 の4-stage descending drive を世界初統合 mapping。⑤PD課題1のSHAP の説明変数に reticulospinal excitability を加え、握力・歩行速度・椅子立ち上がり予測の重要度を検証 → Yujiの既存知見「手指器用さ > 筋質 > 認知 > 筋力」がどう更新されるか。"
    },

    # ============================================================
    "20260613_pd_08": {
        "title": "Age-related decline in GABAergic intracortical inhibition can be counteracted by long-term learning of balance skills",
        "authors": "Kuhn YA, Egger S, Bugnon M, Lehmann N, Taube W",
        "journal": "The Journal of Physiology (IF=4.7), 2024年8月（Vol. 602, Issue 15、Online 2024年7月）",
        "design": "縦断 × TMS SICI（GABA-A intracortical inhibition）× 6ヶ月 balance training × 6ヶ月 detraining／健常高齢者 n=66-81歳の2群（介入 vs 対照）／solid ground vs wobble board × M1 SICI 計測",
        "url": "https://physoc.onlinelibrary.wiley.com/doi/full/10.1113/JP285706",
        "fulltext_status": "read_abstract_only",
        "tags": ["PD研究関連", "TMS", "SICI", "GABA-A", "intracortical inhibition", "balance learning", "M1", "コア軸", "SHAP", "tDCS", "EEG", "brain-muscle", "neuromuscular", "motor cortex", "feature importance"],
        "summary": "健常高齢者（66-81歳）と若年比較群で TMS による SICI（short-interval intracortical inhibition、GABA-A 媒介）を solid ground 立位と wobble board 立位の2条件下で取得。高齢者の SICI は若年比較で solid ground で約35%低下、wobble board で約30%低下。高齢介入群は6ヶ月の週2回 balance training（介入群 vs 対照群）で SICI を有意増加させ、6ヶ月の detraining 後も対照群より有意に高い SICI を維持。SICI の増加と balance performance の改善は有意に相関。長期 balance learning が GABA-A 媒介 intracortical inhibition の加齢低下を逆転させ、加齢の中枢神経 inhibition deficit を介入で modulate できる世界規模の重要 evidence。加齢神経科学全般で介入応答性 biomarker としての SICI を positioning する基準研究。",
        "overview": "**背景**：加齢で GABAergic intracortical inhibition（SICI）は M1 で低下し、これが well-being・sleep・認知・痛みコントロール・運動制御の不全に関与すると考えられているが、介入で逆転可能かは未検証だった。Balance training は cortical inhibition を modulate する candidate intervention だが、long-term effect と detraining 後の retention は希少。**方法**：健常高齢者（66-81歳）を介入群と対照群に分け、介入群は週2回 × 6ヶ月の balance training を実施。TMS による SICI を baseline、2ヶ月、6ヶ月、detraining 6ヶ月後の4 time-point で M1 を target に計測。Solid ground 立位と wobble board 立位の2条件下で評価。若年比較群（n=参考）も baseline で計測。**結果**：高齢者の SICI は若年より solid ground で約35%低下、wobble board で約30%低下。介入群は6ヶ月後に SICI を有意増加させ、対照群より有意高い SICI。Detraining 6ヶ月後も対照群より高い SICI を維持。SICI 増加と balance performance 改善は有意に相関。**結論**：長期 balance learning は加齢の GABA-A 媒介 intracortical inhibition deficit を逆転させ、effect は detraining 後も retention される。加齢神経 inhibition の介入可能性を実証。",
        "importance": "加齢で『balance を学ぶこと』が GABA-A 媒介 cortical inhibition を re-balance するという世界規模の evidence。リハビリ・予防医学のbalance training の理論的支柱を強化し、SICI を介入応答性 biomarker として positioning する新方向性を提示。加齢神経科学・介入研究分野で広く参照されるべき直近の foundational evidence。",
        "originality": "縦断的 SICI 計測（baseline + 2ヶ月 + 6ヶ月 + detraining 6ヶ月）の4 time-point 設計は方法論的に novel。Solid ground と wobble board の2条件下 SICI 比較で task-specificity を捕捉。SICI 増加と balance performance 改善の相関は介入 response biomarker としての SICI を positioning する世界初の direct evidence。",
        "discovery": "①高齢者の SICI は若年より solid ground で約35%低下、②高齢者の SICI は若年より wobble board で約30%低下、③介入群（6ヶ月 balance training）は SICI を有意増加、④対照群は SICI 変化なし、⑤介入効果は2ヶ月で出現、⑥6ヶ月でさらに増加、⑦Detraining 6ヶ月後も対照群より高い SICI を維持、⑧SICI 増加と balance performance 改善は有意に相関、⑨Solid ground と wobble board の双方の条件で介入効果を検出、⑩本研究は加齢 GABA-A 媒介 intracortical inhibition deficit が介入で逆転可能であることを実証し、加齢神経科学の paradigm shift を提示。",
        "methodology": "縦断的 4 time-point SICI 計測は方法論的に堅実。介入群 vs 対照群の RCT-like 設計で因果方向を強化。Solid ground と wobble board の2条件下評価で task-specificity を捕捉。一方、blinding は subject-side で困難（balance training の感じは介入群に伝わる）。本紹介はabstractに基づき fulltext_status は read_abstract_only。",
        "limitation": "本紹介はabstractに基づき本文未読部分があるため limitation 記述に注意。Blinding は subject-side で困難で、self-report 由来の介入 バイアス は除外不能。SICI は M1 単一 region で、他 region（PMd、SMA、PPC）への外挿は要追加検証。介入群と対照群の baseline characteristics の comparability は abstract レベルでは詳細不明。",
        "citation": "[introduction] 加齢 GABA-A 媒介 intracortical inhibition の介入可能性を論じる導入で、本論文を「健常高齢者（66-81歳）の縦断的 TMS SICI 計測（baseline、2ヶ月、6ヶ月、detraining 6ヶ月）で、6ヶ月 balance training が SICI を有意増加させ、SICI 増加と balance performance 改善が有意相関、detraining 後も effect が retention されることを実証した J Physiology 2024年8月の重要研究（Vol. 602, Issue 15）」として引用。 [discussion] 自身の高齢者 tDCS 介入の SICI 応答性を議論する際、本研究の balance learning × SICI 増加（2024年）を比較対照とし、tDCS が SICI を modulate する mechanism が balance learning と類似するかを論じる。",
        "implication": "**PD課題3 の tDCS 介入の理論的支柱**：Yujiの PD 課題3 は tDCS 介入が中心だが、本研究は balance learning が SICI（GABA-A 媒介 intracortical inhibition）を直接 modulate する強い evidence を提供し、tDCS も同様の SICI modulation を介して機能する仮説を強化。**SICI を介入応答性 biomarker として採用**：本研究の SICI × balance correlation は、Yujiの 介入 study で SICI を primary endpoint として採用する世界規模の direct evidence。",
        "idea": "**自前研究への展開3案以上**：①PD課題3の tDCS 介入で本研究 SICI 計測プロトコル（M1、solid ground + wobble board の2条件）を直接導入し、tDCS が balance learning と同様の SICI modulation を induce するかを世界初検証。②TMM サブセットで本研究 balance training × SICI 介入を Japanese 加齢で replication し、効果サイズを欧米と直接比較。③国立長寿NCGGコホートで本研究プロトコルをベースラインに導入し、SICI slope × 転倒発症・要介護化の縦断的予測能を検証。④PD課題2の HD-sEMG 解析に本研究 SICI を加え、cortical inhibition × motor unit firing rate の関連を世界初検証。⑤PD課題1のSHAP の説明変数に SICI を加え、握力・歩行速度・椅子立ち上がり予測の重要度を検証 → Yujiの既存知見「手指器用さ > 筋質 > 認知 > 筋力」がどう更新されるか。"
    },

    # ============================================================
    "20260613_pd_09": {
        "title": "Effects of aging on transmission from Ia afferents to alpha-motoneurons and presynaptic mechanisms across muscle lengths and contraction types",
        "authors": "Betus Y, Colard J, Jubeau M, et al.",
        "journal": "GeroScience (IF=5.4), 2025年（Online 2025年）",
        "design": "横断 × H-reflex/M-wave（Hmax/Mmax）× D1 inhibition（primary afferent depolarization, PAD）× heteronymous facilitation／高齢者 n=19（69±4歳）vs 若年 n=16（23±2歳）／soleus × 3条件 × concentric/isometric/eccentric × 短長 vs 長長",
        "url": "https://link.springer.com/article/10.1007/s11357-025-01958-2",
        "fulltext_status": "read_abstract_only",
        "tags": ["PD研究関連", "H-reflex", "presynaptic inhibition", "PAD", "Ia afferent", "alpha-motoneuron", "soleus", "コア軸", "SHAP", "tDCS", "TMS", "EEG", "brain-muscle", "neuromuscular", "motor cortex", "feature importance"],
        "summary": "若年（n=16、23±2歳）と高齢者（n=19、69±4歳）の soleus で（1）H-reflex/M-wave 比（Hmax/Mmax）による Ia afferent → α motoneuron 伝達、（2）D1 inhibition 法による primary afferent depolarization（PAD = Ia afferent への presynaptic inhibition）、（3）heteronymous facilitation による継続的 presynaptic inhibition を3 contraction type（concentric / isometric / eccentric）× 2 muscle length（短 vs 長）の6条件下で計測。若年では PAD が eccentric 収縮・長い muscle length で増強され adaptable な motor control を支持。加齢で muscle spindle sensitivity が低下し PAD modulation が impaired、つまり Ia afferent presynaptic inhibition の task-dependent 適応が失われる。加齢で『脊髄反射の context-dependent gain control』が低下する核心 mechanism を世界規模で量化した重要研究。Spinal-level の neural ageing biomarker として H-reflex paradigm を positioning。",
        "overview": "**背景**：脊髄反射の context-dependent gain control（PAD による Ia afferent presynaptic inhibition）は若年で task-dependent に modulate されるが、加齢で muscle spindle sensitivity が低下するため PAD modulation が impaired する仮説があった。直接検証は希少で、特に contraction type × muscle length の組み合わせでの量化は世界的にない。**方法**：若年（n=16、23±2歳）と高齢者（n=19、69±4歳）の soleus で3 contraction type（concentric / isometric / eccentric）× 2 muscle length（短 vs 長）の6条件下で（1）Hmax/Mmax による Ia → α motoneuron 伝達、（2）D1 inhibition 法による PAD、（3）heteronymous facilitation による継続的 presynaptic inhibition を計測。介入なしの横断 study。**結果**：若年では PAD が eccentric 収縮・長い muscle length で増強され task-dependent な adaptive control を支持。加齢で PAD modulation が impaired、つまり Ia afferent presynaptic inhibition の task-dependent 適応が失われる。Hmax/Mmax も加齢で altered。**結論**：加齢で『脊髄反射の context-dependent gain control』が低下する核心 mechanism。脊髄レベルの neural ageing が postural control 不全の primary contributor。",
        "importance": "加齢で脊髄反射の gain control が impaired するという仮説を world-first で量化。Postural control 不全の primary basis を脊髄レベル presynaptic inhibition に求める新方向性を提示。H-reflex paradigm を加齢神経科学の biomarker として positioning し、cortical 軸（TMS）と並ぶ spinal 軸の評価法として確立する重要研究。",
        "originality": "Contraction type × muscle length の6条件下 PAD modulation 量化は世界的に希少。D1 inhibition 法と heteronymous facilitation の併用で PAD と継続的 presynaptic inhibition を分離評価する手法は方法論的に sophisticated。加齢で PAD modulation が task-dependent specificity を失うという所見は novel。",
        "discovery": "①若年では PAD が eccentric 収縮で増強、②若年では PAD が長い muscle length で増強、③若年の PAD modulation は task-dependent adaptive control を支持、④加齢で PAD modulation が impaired、⑤加齢で Ia afferent presynaptic inhibition の task-dependent 適応が失われる、⑥Hmax/Mmax も加齢で altered（脊髄反射の overall gain 変化）、⑦n=35（若年16 + 高齢19）の小規模で strong effect detection、⑧D1 inhibition 法と heteronymous facilitation の併用で PAD と継続的 presynaptic inhibition を分離評価、⑨3 contraction type × 2 muscle length の6条件 systematic design、⑩本研究は加齢で『脊髄反射の context-dependent gain control』が低下する核心 mechanism を世界規模で量化。",
        "methodology": "Hmax/Mmax、D1 inhibition 法、heteronymous facilitation の3手法併用で PAD と継続的 presynaptic inhibition を分離評価する設計は方法論的に world-class。3 contraction type × 2 muscle length の6条件 systematic design は task-dependency の量化に最適。一方、n=35 は小規模で性別 sub-group 解析の検出力に限界。本紹介はabstractに基づき fulltext_status は read_abstract_only。",
        "limitation": "本紹介はabstractに基づき本文未読部分があるため limitation 記述に注意。n=35（若年16 + 高齢19）は小規模で性別 sub-group 解析の検出力に限界。Soleus 1筋のみで他筋（tibialis anterior、quadriceps、handgrip 筋）への外挿は要追加検証。横断的 設計で因果方向（加齢→ PAD impairment vs 逆）の特定は限定的。",
        "citation": "[introduction] 加齢で脊髄反射の context-dependent gain control が impaired する仮説を論じる導入で、本論文を「若年16名と高齢者19名の soleus で3 contraction type × 2 muscle length の6条件下 H-reflex/M-wave、D1 inhibition、heteronymous facilitation の3手法で PAD と継続的 presynaptic inhibition を分離評価し、加齢で PAD modulation が task-dependent specificity を失うことを世界規模で量化した GeroScience 2025年の重要研究」として引用。 [discussion] 自身の高齢者 postural control 研究で『脊髄レベル vs 脳レベル どちらが primary contributor か』を議論する際、本研究の spinal-level PAD impairment（2025年）を比較対照とし、Yujiの 900名コホートで H-reflex paradigm を採用する根拠を強める。",
        "implication": "**PD課題2の脊髄軸の追加**：Yujiの PD 課題2 は HD-sEMG・hd-EEG が中心だが、本研究は脊髄レベル H-reflex paradigm が cortical 軸と並ぶ独立 contributing factor として加齢身体機能低下を規定することを実証。**コホートで H-reflex を採用する根拠**：本研究の PAD modulation × task の dissociation は、Yujiの 900名コホートで soleus H-reflex を baseline・follow-up で測定する根拠を強め、cortical-spinal 並行解析の paradigm を提示。",
        "idea": "**自前研究への展開3案以上**：①PD課題2の900名コホートで本研究 H-reflex paradigm（soleus、3 contraction type × 2 muscle length の6条件）を直接実装し、Japanese 加齢 で PAD modulation slope を世界規模で量化。②TMM サブセットで本研究を replication し、Japanese 加齢の PAD impairment 効果サイズを欧米と直接比較。③国立長寿NCGGコホートで本研究プロトコルをベースラインに5年追跡し、PAD modulation slope × 転倒発症・要介護化の縦断的予測能を検証。④PD課題3 tDCS介入の前後で H-reflex paradigm を実装し、tDCS が脊髄レベル PAD modulation を indirectly modify するかの世界初機構検証（下行性 cortical-spinal 介入効果）。⑤PD課題1のSHAP の説明変数に PAD modulation index を加え、握力・歩行速度・椅子立ち上がり予測の重要度を検証 → Yujiの既存知見「手指器用さ > 筋質 > 認知 > 筋力」がどう更新されるか。"
    },

    # ============================================================
    "20260613_pd_10": {
        "title": "An Exercise Intervention May Counteract the Degradation of Nerve Conduction from Age-Related Disuse",
        "authors": "Shields JE, Smith CM, Reese SM, Dos Santos ML, Parodi M, Defreitas JM",
        "journal": "Medicine & Science in Sports & Exercise (IF=4.5), 2025年10月（Vol. 57, Issue 10, pp. 2101-2107）",
        "design": "RCT × 末梢神経伝導速度（NCV、median nerve）× 4週間 handgrip resistance training × 3回/週／n=48（若年14名 training + 12 control、高齢14名 training + 8 control）／NCV pre-post × strength pre-post",
        "url": "https://journals.lww.com/acsm-msse/fulltext/2025/10000/an_exercise_intervention_may_counteract_the.1.aspx",
        "fulltext_status": "read_abstract_only",
        "tags": ["PD研究関連", "nerve conduction velocity", "NCV", "peripheral nerve", "handgrip training", "reinnervation", "末梢神経", "コア軸", "SHAP", "tDCS", "TMS", "EEG", "brain-muscle", "neuromuscular", "motor cortex", "feature importance"],
        "summary": "n=48（若年14名 training + 12名 control、高齢14名 training + 8名 control）で4週間（3回/週）の両側 handgrip resistance training の前後で median nerve 末梢神経伝導速度（NCV）と最大握力を計測。若年・高齢の双方で training 群は NCV を有意増加（若年 d=0.749, p<0.001; 高齢 d=0.679, p<0.001）。Control 群は変化なし。Resistance training が加齢・disuse による末梢神経 degradation を逆転させ、高齢者でも fast neurons の reactivation（reinnervation）が起きる仮説を強く支持。末梢神経 NCV を加齢介入応答性 biomarker として positioning した先駆研究。Yujiの PD 課題で末梢神経 axis を加える根拠となり、cortical-spinal-peripheral の3 stage 軸の peripheral 末端で介入可能性を実証。2025年10月 MSSE 公刊の重要研究。",
        "overview": "**背景**：加齢で末梢神経の NCV は低下し fast motor neurons が degenerate するが、resistance training が peripheral nerve 機能を直接 modulate できるかは未検証だった。Handgrip training は upper-limb function に直結し、population-scale で実装可能。**方法**：n=48 を4群に分類：若年 training（n=14）、若年 control（n=12）、高齢 training（n=14）、高齢 control（n=8）。Training 群は4週間（3回/週）の両側 handgrip resistance training。Median nerve NCV と最大握力を training pre-post で計測。**結果**：若年 training 群は NCV を有意増加（d=0.749, p<0.001）、高齢 training 群も有意増加（d=0.679, p<0.001）。両 control 群は変化なし。Training 群の高齢者全員が NCV improvement を示し、reinnervation の direct evidence。**結論**：Resistance training は加齢・disuse 由来の末梢神経 NCV degradation を逆転させ、高齢者でも fast motor neurons の reactivation が可能。末梢神経 NCV は加齢介入応答性 biomarker として機能。",
        "importance": "「末梢神経 axis は加齢で固定 degradation」という standard view に対し、resistance training で逆転可能であることを実証した paradigm-shifting research。加齢神経科学の介入可能性を末梢神経まで拡張し、リハビリ・予防医学の方向性を大きく変える potential。直近の Medicine & Science in Sports & Exercise 重要研究で、末梢神経の介入応答性 biomarker としての NCV の confidence を強化。",
        "originality": "末梢神経 NCV を resistance training 介入の primary endpoint として採用する RCT は世界的に希少。若年・高齢の双方で同程度の 効果サイズ（d=0.749 vs 0.679）を観察した点で paradigm shift。Handgrip training という population-scalable 介入と末梢神経 NCV という electrophysiological biomarker を直接連結した先駆研究。",
        "discovery": "①若年 training 群は NCV を有意増加（d=0.749, p<0.001）、②高齢 training 群も NCV を有意増加（d=0.679, p<0.001）、③若年・高齢の 効果サイズ は comparable（d=0.749 vs 0.679）、④若年・高齢の双方の control 群は変化なし、⑤Training 群の高齢者全員が NCV improvement、⑥Training 群の最大握力も増加、⑦n=48 の中規模 RCT で strong 効果サイズ、⑧4週間（3回/週）の short-term intervention で effect が出現、⑨Handgrip training は population-scalable で臨床実装性が高い、⑩本研究は末梢神経 NCV を加齢介入応答性 biomarker として positioning し、リハビリ・予防医学の paradigm shift を提示。",
        "methodology": "若年 × 高齢 × training × control の4群比較は方法論的に堅実。Median nerve NCV と最大握力の dual アウトカム で末梢神経と筋の adaptation を同時評価。4週間（3回/週）の short-term intervention で early effect の検出が可能。一方、n=48（4群 × 8-14名）は中規模で性別 sub-group 解析の検出力に限界。本紹介はabstractとMSSE webpage に基づき fulltext_status は read_abstract_only。",
        "limitation": "本紹介はabstractに基づき本文未読部分があるため limitation 記述に注意。n=48（4群 × 8-14名）は中規模で性別 sub-group 解析の検出力に限界。Median nerve 1部位のみで他末梢神経（ulnar、tibial、peroneal）への外挿は要追加検証。4週間の short-term intervention で long-term retention は別 study が必要。NCV は motor のみで sensory への効果は別検証。",
        "citation": "[introduction] 加齢末梢神経 NCV degradation の介入可能性を論じる導入で、本論文を「n=48（若年training 14 + control 12、高齢 training 14 + control 8）の4週間（3回/週）handgrip resistance training で、若年・高齢の双方の training 群が median nerve NCV を有意増加させ（若年 d=0.749, 高齢 d=0.679, ともに p<0.001）、末梢神経 NCV を加齢介入応答性 biomarker として positioning した Medicine & Science in Sports & Exercise 2025年10月の重要研究（Vol. 57, Issue 10, pp. 2101-2107）」として引用。 [discussion] 自身の高齢者 resistance training 介入研究で末梢神経 axis を アウトカム として採用する妥当性を論じる際、本研究の d=0.679（2025年）を比較対照とし、Japanese 加齢 で同様の NCV improvement を実装する設計を論じる。",
        "implication": "**PD課題1の末梢軸の追加**：Yujiの PD 課題1 は脳・筋を中心に身体機能予測しているが、本研究は末梢神経 NCV を加齢介入応答性 biomarker として positioning し、cortical-spinal-peripheral の3 stage descending axis の peripheral 末端で介入可能性を実証。**Handgrip training プロトコルの直接採用**：本研究の4週間（3回/週）handgrip training は population-scalable で、Yujiの 900名コホートの介入 study で直接採用可能。",
        "idea": "**自前研究への展開3案以上**：①PD課題3の高齢者介入 study で本研究 handgrip training プロトコル（4週間、3回/週）を導入し、NCV improvement の Japanese 効果サイズを欧米と直接比較。②TMM サブセットで本研究を replication し、Japanese 加齢 NCV degradation の age slope と training reversibility を量化。③国立長寿NCGGコホートで本研究プロトコルをベースラインに5年追跡し、NCV slope × 握力低下・要介護化の縦断的予測能を検証。④PD課題2の HD-sEMG 解析に本研究 NCV を加え、皮質-皮質脊髄-脊髄-末梢神経-筋 の5-stage descending drive を世界初統合 mapping。⑤PD課題1のSHAP の説明変数に NCV を加え、握力・歩行速度・椅子立ち上がり予測の重要度を検証 → Yujiの既存知見「手指器用さ > 筋質 > 認知 > 筋力」がどう更新されるか。"
    },
}
