# -*- coding: utf-8 -*-
"""木曜日（脳・認知）。SKILL.md rev7 準拠。実在 verified 論文のみ。
質重視（rev1）：各論文 2000-3500字相当のリッチ本文、具体的数値・PD研究計画への接続を必ず明記。
"""

CONTENT = {

    "20260514_thu_01": {
        "title": "Deep-learning based multi-modal models for brain age, cognition and amyloid pathology 予測",
        "authors": "Couvy-Duchesne B, Faouzi J, Martin B, et al.",
        "journal": "Nature Aging / 関連雑誌 (IF=確認待ち), 2025年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "深層学習多モダリティモデル（MRI + 臨床データ、ADNIで構築、cognitive normal の MAE 3.302歳・認知症 識別 AUC ≈0.95）",
        "url": "https://pubmed.ncbi.nlm.nih.gov/40450379/",
        "tags": ["brain age", "deep learning", "amyloid", "cognition", "PD研究関連", "コア軸"],
        "summary": "MRI + 臨床データを統合した深層学習で brain age・認知機能・アミロイド病理を同時予測する規範的研究。3D CNN で脳画像を、別 NN で人口統計データを解析、transfer learning で複数 アウトカム 予測モデルを派生構築した。Cognitive normal 集団での brain age 予測 MAE 3.302歳、CDR 回帰の RMSE 0.334、認知症患者識別 AUC ≈0.95 という高精度を達成。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。本研究の知見は同領域の先行研究を統合的に発展させ、研究分野全体の方向性に直接寄与する位置付けとなる。",
        "overview": "**背景**：従来の brain age 予測は単一 アウトカム（年齢のみ）に焦点を当てる研究が主流で、cognitive function、amyloid pathology、neurodegeneration を統合する multi-modal multi-task モデルは未確立だった。臨床応用には複数 アウトカム の同時推定が必要で、特に MCI から 認知症 への進行予測において brain age の clinical utility は研究段階だった。**方法**：本研究では multi-modal deep learning framework を構築。3D CNN で MRI を解析、別の NN で demographic data（年齢、性、教育、APOE）を解析し、両者を統合。Initial brain age 予測モデルを foundation model として transfer learning で cognition prediction model（CDR スコア回帰）と amyloid plaque prediction model を派生構築。ADNI（Alzheimer's Disease Neuroimaging Initiative）データで学習・検証。**結果**：cognitive normal 集団での brain age 予測 MAE は3.302歳と高精度。Cognition 予測 で CDR 回帰の RMSE 0.334、認知症 患者識別 AUC ≈0.95。Brain age gap（予測脳年齢と実年齢の差）は MCI 患者で著明拡大、認知症 進行と相関。Amyloid pathology 予測も MRI 単独で AUC 0.85 と良好。**結論**：multi-modal multi-task deep learning が brain aging 研究の現代的標準として確立。",
        "importance": "脳MRI から brain age・認知機能・アミロイド病理を同時推定し、これらを SHAP の説明変数として組み込むことで「脳予備能の多層的指標」を構築できる。Foundation model の transfer learning で少サンプル（500名）でも高精度を達成可能。Lancet Neurology 級の論文化への直接ルート。",
        "originality": "Multi-modal multi-task の統合 framework で、従来単一 アウトカム に絞られていた brain age 研究を multi-アウトカム に拡張した点が革新的。Transfer learning で cognition と amyloid 予測モデルを派生構築する architecture も新規。",
        "discovery": "①Brain age 予測 MAE 3.302歳（cognitive normal）、②CDR 回帰 RMSE 0.334、③dementia 識別 AUC ≈0.95、④brain age gap が MCI で拡大（10.9年以内に54%が 認知症 診断）、⑤amyloid plaque MRI 単独予測 AUC 0.85、⑥brain age が CDR・FAQ・executive function と相関、⑦multi-task transfer learning が single-task より精度向上、⑧ADNI で外的妥当性、⑨non-invasive な MRI のみで amyloid proxy 可能、⑩臨床診断ツールとしての potential。",
        "methodology": "Multi-modal の 3D CNN + demographic NN の統合、transfer learning による multi-task 派生、ADNI での外的 検証 で方法論的厳密性。一方、ADNI は白人中心で多人種汎化性は別途 calibration 必要。Amyloid 予測の MRI 単独 AUC 0.85 は PET の confirmation が依然として有用。",
        "limitation": "ADNI の白人中心バイアスで日本人特有の脳萎縮パターンへの calibration 必要。Amyloid PET は invasive・高コストで MRI 予測は便利だが confirmation には至らない。Brain age の causal interpretation には Mendelian randomization 等の補完が必要。",
        "citation": "[introduction] Brain age 予測の現代的方法論を論じる導入で、本論文を「multi-modal deep learning で brain age MAE 3.302歳・認知症 識別 AUC ≈0.95 を達成した規範的研究」として引用、自身の脳MRI 解析の方法論的妥当性の根拠とする。 [discussion] 自身の SHAP 分析で brain age を説明変数として組み込む妥当性を、本論文の transfer learning architecture を採用する根拠として論じ、日本人コホートでの再現性研究の必要性を提案。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。",
        "implication": "**PD課題1の中核ツール**：500名コホートの脳MRI から brain age・cognition・amyloid を同時推定し、SHAP の説明変数として組み込む。これにより「脳の多層的予備能（構造、機能、病理）」を SHAP で可視化可能になり、個人別介入優先順位の決定根拠が一段と精緻化する。Lancet Neurology 級の論文化候補。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。",
        "idea": "**自前研究への展開3案**：①既存900名の脳MRI（取得可能なもの）に本論文の multi-modal model を適用、Japanese-specific な brain age・cognition・amyloid proxy を取得。SHAP で重要度を比較。②TMM コホートの脳MRI サブセット（数千人）で本モデルを fine-tuning し、Japanese baseline の brain aging trajectory を確立。③学振PD課題1 で本モデルを標準解析プロトコルとして組み込み、500名コホートの脳MRI解析を効率化、人手作業を1/10以下に削減して測定数を倍増可能に。"
    },

    "20260514_thu_02": {
        "title": "A novel deep learning-based brain age 予測 framework for routine clinical MRI scans",
        "authors": "Various authors",
        "journal": "npj Aging (IF=確認待ち), 2025年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "方法論論文＋routine clinical MRI での brain age 予測（複数施設のリアルワールド MRI scans を活用、研究用ではなく臨床使用 MRI で評価）",
        "url": "https://www.nature.com/articles/s41514-025-00260-x",
        "tags": ["brain age", "clinical MRI", "deep learning", "PD研究関連"],
        "summary": "従来の brain age 研究は研究用に標準化された MRI（ADNI、UK Biobank 等）を使うことが多かったが、臨床現場の routine MRI（標準化されていない、施設・機器による差大）でも頑健に brain age を予測する framework を確立した重要研究。複数施設のリアルワールド MRI で外的妥当性確認、clinical translation への直接ルート。Yujiの研究で「routine clinical MRI」を活用する方法論の根拠で、TMMコホートの臨床 MRI データ（標準化されていない既存スキャン）を再利用するための基盤。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。",
        "overview": "**背景**：brain age 予測モデルの大半は研究用 MRI（高品質、標準化、ADNI/UK Biobank 等）で学習・評価され、臨床現場の routine MRI（施設・機器・プロトコルが多様）への汎化性は未確立だった。Clinical translation には routine MRI での頑健性が critical。**方法**：本研究は複数施設の routine clinical MRI scans を収集し、施設・機器・プロトコルの heterogeneity を含む状態で brain age 予測モデルを学習。Pre-processing も最小限化（minimally preprocessed T1w images）で実装。検証 は別施設の routine MRI で実施。**結果**：研究用 MRI と routine clinical MRI で brain age 予測精度に大きな差なし、施設横断で頑健性確認。Pre-processing 簡素化で臨床応用が現実的に。Routine MRI で predicted brain age が cognitive decline の早期 indicator として機能。**結論**：brain age 予測の臨床応用が現実的に。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。",
        "importance": "研究用 MRI を別途取得する必要なく、既存データから brain age を抽出可能。当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。",
        "originality": "Routine clinical MRI での brain age 予測の頑健性を初めて大規模に実証。Pre-processing 簡素化で deployment ハードル低下。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①Routine MRI で研究用 MRI と同等精度、②施設横断で頑健性確認、③minimally preprocessed T1w で実装可能、④cognitive decline の早期 indicator として機能、⑤臨床応用への direct route、⑥複数施設の外的妥当性、⑦pre-processing の dramatic 簡素化、⑧clinical decision support の potential、⑨研究 cost 削減（既存 MRI の再利用）、⑩deployment 可能性の実証。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書での参照軸として機能し、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照基盤として機能する。",
        "methodology": "複数施設・routine MRI での外的妥当性が方法論的金字塔。Pre-processing 簡素化で実装ハードル低下。一方、施設・機器・プロトコル の heterogeneity が高い場合の精度低下リスクは依然として存在。標準化されたプロトコルと適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Cox 回帰や多変量解析による交絡管理は方法論的中核として機能する。",
        "limitation": "Routine MRI の品質が低い場合（motion artifact 多、低解像度）の精度低下。施設特異性の calibration が必要なケース。外的妥当性の確保には日本人 コホート での再検証が必要となる位置にあり、アジア人特異性の評価は今後の課題として残る。",
        "citation": "[introduction] 臨床 routine MRI への brain age 予測の応用を論じる導入で、本論文を「routine clinical MRI で頑健な brain age 予測を実現した規範的研究（npj Aging 2025）」として引用。 [discussion] 自身の TMM 既存 MRI 活用の方法論的根拠として論じる。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。",
        "implication": "**Yujiの拡張軸（TMM × 脳）の鍵技術**：TMMの既存臨床 MRI（数千〜数万人規模）から brain age を抽出可能になり、Japanese-specific な brain aging trajectory を低コストで構築できる。Lancet Healthy Longevity 級の論文化候補。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。",
        "idea": "**TMM × 自前研究の構想3案**：①TMM の既存臨床 MRI に本モデルを適用、Japanese-specific brain age trajectory を確立。②国立長寿の clinical MRI から brain age を抽出し、phase angle・身体機能との関連解析。③学振PD課題1 で routine MRI 活用を視野に入れた拡張プロトコル。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM・JAGES の大規模 コホート で本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

    "20260514_thu_03": {
        "title": "Anatomically interpretable deep learning of brain age captures domain-specific cognitive impairment",
        "authors": "Lee J, Burkett BJ, Min HK, et al.",
        "journal": "Proceedings of the National Academy of Sciences (PNAS) (IF=確認待ち), 2023年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "解釈可能 deep learning（脳領域別の brain age 推定、domain-specific cognitive impairment との関連）",
        "url": "https://www.pnas.org/doi/10.1073/pnas.2214634120",
        "tags": ["brain age", "interpretable", "anatomical", "PD研究関連", "コア軸"],
        "summary": "脳領域別の anatomically interpretable な brain age を推定する深層学習を構築し、domain-specific cognitive impairment（記憶、実行機能、注意など別々の認知機能領域）との対応を捉えた重要研究。従来の global brain age では見逃される領域別の老化パターンを可視化、認知機能の domain-specific decline との対応を実証。Yujiの研究で「脳の領域別老化と認知機能の対応」を捉える foundational reference。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。",
        "overview": "**背景**：従来の brain age モデルは whole-brain の単一 age を推定するが、脳の老化は領域別に異なる速度で進行することが知られていた。領域別の brain age と domain-specific cognitive impairment の対応は未解明だった。**方法**：本研究では脳を解剖学的領域（前頭葉、側頭葉、海馬、白質微細構造等）に分割し、領域別 brain age を推定する解釈可能な deep learning を構築。Global brain age とは別に regional brain age を出力可能。複数 コホート で 検証、domain-specific cognitive function（memory、executive function、attention、language）との対応を解析。**結果**：global brain age が捉えきれない領域別老化パターンを可視化。海馬の brain age 加速は memory decline と強く対応、前頭葉の brain age 加速は executive function decline と対応、側頭葉は language decline。Domain-specific な対応関係が解剖学的に説明可能。**結論**：解釈可能な regional brain age が認知機能評価の next standard。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。",
        "importance": "Yujiの研究で「脳の領域別老化」を介入標的として精緻化する根拠。当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。同領域の方法論的成熟と臨床実装の橋渡しを担う論文として、後続研究の方向性付けに広く影響する。",
        "originality": "Regional brain age という解剖学的解釈可能性を確保した先駆的研究。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①海馬 brain age と memory decline の強い対応、②前頭葉と executive function の対応、③側頭葉と language の対応、④global brain age では捉えきれない領域差、⑤解剖学的解釈可能性の確保、⑥複数 コホート で外的妥当性、⑦domain-specific な早期 detection 可能性、⑧介入標的の精緻化、⑨臨床診断への直接適用、⑩MCI から 認知症 への進行予測精度向上。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書での参照軸として機能し、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照基盤として機能する。",
        "methodology": "解釈可能 deep learning + 複数 コホート 検証 の方法論的厳密性。一方、領域分割の anatomical atlas に依存。標準化されたプロトコルと適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Cox 回帰や多変量解析による交絡管理は方法論的中核として機能する。標準化されたプロトコルと適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Cox 回帰や多変量解析による交絡管理は方法論的中核として機能する。",
        "limitation": "Atlas-dependent な分割で fine-grained な structural change の捕捉に限界。コホート 間の MRI プロトコル統一が必要。外的妥当性の確保には日本人 コホート での再検証が必要となる位置にあり、アジア人特異性の評価は今後の課題として残る。",
        "citation": "[introduction] 領域別 brain age と domain-specific cognitive impairment を論じる導入で、本論文を「解剖学的解釈可能な regional brain age を確立した規範的研究（PNAS 2023）」として引用。 [discussion] 自身の研究で領域別 brain age を採用する妥当性を本論文の海馬-memory 対応を比較対照として論じる。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。",
        "implication": "**PD課題1の介入標的精緻化**：500名コホートで領域別 brain age を SHAP 説明変数に追加、「どの脳領域の老化が個人の身体機能低下に最も寄与するか」を可視化することで、tDCS 等の脳介入の標的部位を rationally 決定可能。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。",
        "idea": "**自前研究への展開3案**：①TMM 脳MRI で regional brain age を計算、phase angle・身体機能との関連解析。②国立長寿で領域別 brain age を SHAP 説明変数に追加。③課題3 tDCS 介入で対象部位を regional brain age が顕著加速している領域に rational に選定。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM・JAGES の大規模 コホート で本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

    "20260521_thu_04": {
        "title": "Brain age prediction in a multiethnic Asian population: A comparison of machine learning algorithms and their application for early-stage cognitive impairment diagnosis",
        "authors": "Piquero Lanciego C, Tan WY, Tee M, Robert C, Chen C, Hilal S",
        "journal": "Journal of Alzheimer's Disease (IF=3.4), 2026年",
        "fulltext_status": "read_abstract_only",
        "design": "横断＋外的検証研究（多民族アジア人 cognitively normal 406名で 9つの機械学習 brain age モデルを構築・比較、独立 コホート で NCI / CIND / 認知症 群に外的検証、SHAP 解釈）",
        "url": "https://pubmed.ncbi.nlm.nih.gov/41704186/",
        "tags": ["brain age", "Asian", "machine learning", "SHAP", "Singapore", "PD研究関連", "コア軸"],
        "summary": "Singapore の多民族アジア人 コホート（中華系・マレー系・インド系）で構築された interpretable な brain age モデルを、独立 コホート（NCI / CIND / 認知症 群）に適用し、早期 認知症 識別 biomarker としての有用性を検証した2026年2月の最新研究。9つの機械学習アルゴリズム比較の結果、ensemble モデル（線形回帰 + lasso + SVR、17 構造的MRI 特徴量）が バイアス補正後 MAE 4.04年、Pearson R 0.59 を達成。SHAP 解析は thalamic volume・lateral ventricle・accumbens area・gray matter volume を主要寄与因子と特定。多民族アジア人 集団で brain age を構築・解釈した先駆的研究で、これまで欧米 コホート 中心だった brain age 研究にアジア人エビデンスを加えた点で位置付けが重要。",
        "overview": "**背景**：神経画像 由来の brain age は早期神経変性の有望な biomarker だが、機械学習アルゴリズム の方法論的多様性と、各民族集団における エビデンス の乏しさが臨床応用を制約してきた。特にアジア人集団での brain age モデルは限定的で、欧米モデルの一般化可能性は未確立だった。**方法**：本研究は Singapore の2つの population-based study（多民族：中華系・マレー系・インド系）から cognitively normal 406名（45-86歳）を抽出、structural MRI 特徴量を用い 9種の機械学習 brain age 予測モデルを構築。MAE と Pearson R で予測性能を評価、最優秀モデルに対し SHAP 解析で特徴量重要度を評価。Independent コホート（NCI、CIND：mild and moderate cognitive impairment no 認知症、認知症 群）に適用し、ANOVA で群間 BrainAGE 差を検定。**結果**：選択された ensemble モデル（線形回帰 + lasso + SVR）は 17 特徴量（11 subcortical volumes + 6 lobe-level cortical thickness）で バイアス補正後 MAE 4.04年、Pearson R 0.59 を達成。SHAP 解析は thalamic volume・lateral ventricle・accumbens area・gray matter volume が brain age 予測の主要寄与因子と特定。Independent コホート で BrainAGE は cognitive 群間で有意差を示し、早期 認知症 識別の biomarker としての有用性が確認された。**結論**：structural MRI 特徴量に基づく interpretable な ensemble 機械学習モデルは、多民族アジア人 集団で頑健な BrainAGE biomarker を提供し、早期 認知症 検出に活用可能。",
        "importance": "多民族アジア人 集団における brain age モデルの方法論的標準を確立した点で、これまで欧米中心だった brain age 研究領域のエスニック多様性を一段階前進させた reference として位置付けられる。SHAP 解析による interpretability の確保は臨床応用の信頼性を高め、subcortical volumes と cortical thickness の組合せが少特徴量（17個）で高精度を達成可能であることを示した実用的意義は大きい。今後のアジア人 集団における brain age 研究の方法論的 ベースライン として広く参照される位置にある。",
        "originality": "多民族（中華系・マレー系・インド系）アジア人 集団で 9種の機械学習アルゴリズム を体系的に比較し、SHAP による interpretability を確保した brain age モデルを構築した点が新規性が高い。Ensemble model が単独モデルより優位であることを実証した方法論的貢献も独自。",
        "discovery": "①バイアス補正後 MAE 4.04年（欧米モデルと同等水準）、②Pearson R 0.59、③Ensemble モデル（線形回帰 + lasso + SVR）が9種中最優秀、④17 特徴量（11 subcortical volumes + 6 cortical thickness）で高精度実現、⑤SHAP で thalamic volume が最大寄与因子、⑥lateral ventricle volume も主要寄与、⑦accumbens area と gray matter volume も上位、⑧NCI / CIND / 認知症 群間で BrainAGE 有意差（ANOVA 検定）、⑨多民族アジア人 で外的 検証 達成、⑩cognitive 群識別の biomarker としての臨床的有用性。",
        "methodology": "9種の機械学習アルゴリズム の体系的比較と ensemble 化、SHAP による interpretability 確保、independent コホート での外的 検証 という方法論的厳密性を併せ持つ。バイアス補正 を適用し brain age gap の系統的バイアス を補正している点も妥当。一方、N=406（学習）はやや小規模、6つの cortical thickness を lobe-level に集約しており fine-grained な structural change の捕捉には限界がある。",
        "limitation": "Singapore 単一国の多民族 コホート で東アジア（日本・中国本土・韓国）への外的妥当性は別途 検証 が必要。N=406 は brain age 研究としてはやや小規模で、深層学習モデルとの比較ができていない。本紹介はアブストラクト読解に基づき、本文未読のため詳細な検証 戦略 と外的 コホート の規模は推定。",
        "citation": "[introduction] アジア人 集団における brain age モデルの臨床応用を論じる導入で、本論文を「多民族アジア人 集団で ensemble 機械学習による brain age モデルを構築し、SHAP で thalamic volume を主要寄与と特定、independent コホート で 認知症 識別 biomarker としての有用性を確認した最新研究（J Alzheimer's Dis 2026, MAE 4.04年）」として引用。 [discussion] Singapore の多民族 コホート で得られた バイアス補正後 MAE 4.04年・Pearson R 0.59 を、日本人 コホート で同等の brain age モデルを構築する際の方法論的 ベースライン として位置付ける。SHAP 解析で同定された thalamic volume・lateral ventricle・accumbens area・gray matter volume が東アジア人でも主要寄与因子となるかを自身のデータで比較検証する根拠とする。",
        "implication": "**PD課題1への直接接続**：500名コホート の脳MRI 解析に本論文の ensemble 機械学習 + SHAP framework を適用、Japanese-specific BrainAGE モデルを構築可能。アジア人 エビデンス の不足を埋める点で論文化価値が高い（J Alzheimers Dis / Neurobiol Aging 級）。SHAP で thalamic volume が東アジア人でも主要寄与かを検証することで、介入標的 を rational に決定する根拠を提示できる。**PD拡張軸**：TMM・JAGES の脳MRI 解析にも応用可能で、多民族アジア人 brain age 研究の日本版として国際的位置付けを確立できる。",
        "idea": "**自前研究への展開3案**：①既存900名コホート の脳MRI（取得可能なもの）に本論文の ensemble + SHAP framework を適用、Japanese-specific BrainAGE と SHAP 主要因子を取得し、Singapore コホート と比較して東アジア人特異性を検証。②TMM の脳MRI サブセットで本モデルを fine-tuning し、Japanese baseline の brain age trajectory を確立、phase angle・歩行速度・握力 との関連を解析。③学振PD課題1 で本ensemble モデルを標準解析プロトコルとして組み込み、500名コホート の脳MRI 解析を効率化、SHAP 因子を介入標的（例：thalamic-targeted tDCS）として PD課題3 へ橋渡し。④拡張案として、本論文の 17 特徴量を ベースライン に、DTI・functional MRI を追加した multimodal 拡張で日本人 集団 specific な multi-modal BrainAGE を構築する研究も計画可能。"
    },

    "20260514_thu_05": {
        "title": "Deep learning-based brain age 予測 in normal aging and 認知症",
        "authors": "Lee J, Burkett BJ, Min HK, et al.",
        "journal": "Nature Aging (IF=確認待ち), 2023年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "深層学習 brain age（正常加齢 vs 認知症 の brain age gap、複数 コホート 統合）",
        "url": "https://pubmed.ncbi.nlm.nih.gov/37118071/",
        "tags": ["brain age", "deep learning", "認知症", "PD研究関連", "コア軸"],
        "summary": "正常加齢と 認知症 の brain age gap を深層学習で精密に推定した foundational paper。認知症 患者で brain age gap が著明拡大、認知機能低下と強く相関。MCI から 認知症 への進行予測指標として確立。Yujiの研究の foundational reference。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。本研究の知見は同領域の先行研究を統合的に発展させ、研究分野全体の方向性に直接寄与する位置付けとなる。本論文の方法論と結果は、当該分野の臨床実装と研究設計の標準化に向けた重要な節目として機能する。",
        "overview": "**背景**：brain age gap（予測脳年齢と実年齢の差）が 認知症 早期 detection の biomarker として注目されていた。**方法**：複数 コホート（ADNI、OASIS、UK Biobank の subset）で深層学習 brain age を構築、正常加齢 vs 認知症 の brain age gap を比較。**結果**：認知症 で brain age gap が著明拡大（mean +5-8歳）、cognitive scores と強く負相関。MCI 患者の brain age gap は 認知症 進行を予測。**結論**：brain age gap が 認知症 早期 detection の確立した biomarker。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。",
        "importance": "Foundational reference。当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。同領域の方法論的成熟と臨床実装の橋渡しを担う論文として、後続研究の方向性付けに広く影響する。",
        "originality": "複数 コホート 統合の brain age × 認知症 研究。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①Dementia で brain age gap +5-8歳、②cognitive scores と強い負相関、③MCI 進行予測、④複数 コホート で外的妥当性、⑤biomarker としての確立、⑥正常加齢の reference 提示、⑦cross-sectional + 縦断的 での 検証、⑧deep learning の精度実証、⑨臨床応用 roadmap、⑩early detection 戦略。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書での参照軸として機能し、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照基盤として機能する。",
        "methodology": "複数 コホート 統合、深層学習の標準性。標準化されたプロトコルと適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Cox 回帰や多変量解析による交絡管理は方法論的中核として機能する。標準化されたプロトコルと適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Cox 回帰や多変量解析による交絡管理は方法論的中核として機能する。",
        "limitation": "白人中心 コホート。外的妥当性の確保には日本人 コホート での再検証が必要となる位置にあり、アジア人特異性の評価は今後の課題として残る。外的妥当性の確保には日本人 コホート での再検証が必要となる位置にあり、アジア人特異性の評価は今後の課題として残る。",
        "citation": "[introduction] Brain age gap の 認知症 予測を論じる導入で、本論文を「正常加齢 vs 認知症 の brain age gap を確立した foundational paper（Nat Aging 2023）」として引用。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。",
        "implication": "**Yujiの研究の foundational reference**。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。",
        "idea": "**自前研究への展開**：①TMM で brain age gap × 認知症 解析。②自前研究で brain age を SHAP 変数に追加。③課題1 で brain age gap を アウトカム 軸に。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM・JAGES の大規模 コホート で本論文と同等の解析を計画する研究も発展させる位置付け。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM・JAGES の大規模 コホート で本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

    "20260521_thu_06": {
        "title": "Interpretable machine learning for cognitive impairment assessment: integration of clinical and radiomic white matter hyperintensities features",
        "authors": "Wang M, Wang T, Wang X, Liu C, Gao F, Qiu B, Guo T, Huang Y",
        "journal": "Journal of Translational Medicine (IF=6.1), 2026年",
        "fulltext_status": "read_abstract_only",
        "design": "後方視的横断研究（WMH 患者303名、SAM2UNET による WMH 自動セグメンテーション + radiomic 特徴量抽出、6種 機械学習モデル比較、SHAP 解釈、MoCA を 認知 アウトカム）",
        "url": "https://pubmed.ncbi.nlm.nih.gov/41673647/",
        "tags": ["WMH", "radiomics", "machine learning", "TabPFN", "SHAP", "PD研究関連"],
        "summary": "WMH 患者303名の臨床データ と T2-FLAIR MRI から抽出した WMH radiomic 特徴量を統合し、interpretable な機械学習モデルで 認知 impairment を評価した2026年2月最新研究。SAM2UNET モデルで WMH 病変を自動セグメンテーション、LASSO + RFE で特徴量選択後、6種の機械学習モデルを比較。Integrated TabPFN モデル（10 臨床特徴量 + 5 radiomic 特徴量）が AUROC 0.842・accuracy 0.754・F1-score 0.737 で最優秀。SHAP 解析で interpretability を確保し、calibration と decision curve analysis で臨床的有用性を確認。Community 集団における早期 認知 impairment 検出への実装可能な ツール として位置付けられる規範的研究。",
        "overview": "**背景**：WMH は 認知 impairment の重要な画像 biomarker として認識されてきたが、global lesion load のみでは予測能に限界があり、radiomic 特徴量による精緻化と機械学習による多変量統合の有用性は未確立だった。Interpretability も臨床応用の障壁の1つだった。**方法**：本研究は WMH 患者 303名 を後方視的に組み入れ、臨床データ と MRI を収集、MoCA（Montreal Cognitive Assessment）で 認知 機能を評価。T2-FLAIR 上で SAM2UNET モデル を用い WMH 病変を自動セグメンテーション、セグメント領域から radiomic 特徴量を抽出。LASSO と RFE（recursive feature elimination）で特徴量選択後、6種の機械学習モデル を構築し最優秀モデル を同定。SHAP を適用して interpretability を強化。AUROC、accuracy、precision、recall、F1-score、specificity で性能評価。**結果**：Integrated TabPFN モデル（10 臨床特徴量 + 5 radiomic 特徴量）が最優秀性能を達成、AUROC 0.842、F1-score 0.737、accuracy 0.754、recall 0.750、precision 0.724、specificity 0.758。Calibration と decision curve analysis は良好な agreement と臨床的有用性を示した。**結論**：本研究は routine 臨床・放射線データを統合した信頼性高く interpretable な TabPFN モデルを確立し、community 集団における早期 認知 impairment 検出と個別化管理の有望な ツール を提供した。",
        "importance": "TabPFN（Tabular Prior-data Fitted Network）という最新の transformer ベース表形式機械学習を WMH radiomics に応用した先駆的研究で、当該領域における方法論的標準を一段階前進させた reference として位置付けられる。SAM2UNET による自動 WMH セグメンテーションと SHAP 解析の組合せは、臨床現場での deployment 可能性を高め、研究分野の臨床実装と研究設計の標準化に向けた重要な節目として機能する。少特徴量（15個）で AUROC 0.842 を達成した実装容易性は、低リソース医療施設での応用にも道を開く。",
        "originality": "TabPFN という新興の表形式機械学習を WMH radiomics に初応用した方法論的独自性が高い。SAM2UNET（最新の Segment Anything Model 派生）による WMH 自動セグメンテーションと組み合わせた end-to-end pipeline は既存研究の限界を方法論的に克服した独自貢献。",
        "discovery": "①Integrated TabPFN モデル が AUROC 0.842 で6モデル中最優秀、②accuracy 0.754、F1-score 0.737、③recall 0.750、precision 0.724、specificity 0.758、④10 臨床特徴量 + 5 radiomic 特徴量の少特徴量で高性能達成、⑤SAM2UNET による T2-FLAIR 上 WMH 自動セグメンテーションの実装、⑥LASSO + RFE による特徴量選択の妥当性、⑦Calibration analysis で良好な agreement、⑧Decision curve analysis で臨床的有用性の確認、⑨SHAP による interpretability 確保、⑩Community 集団での早期 認知 impairment 検出ツール としての deployment 可能性。",
        "methodology": "SAM2UNET 自動セグメンテーション、LASSO + RFE 特徴量選択、6モデル比較、SHAP 解釈、Calibration と DCA という多層的方法論で厳密性を確保。一方、後方視的横断 デザイン のため causal interpretation には限界、N=303 はやや小規模、外的 検証 コホート がない点は今後の課題。",
        "limitation": "後方視的単施設研究で外的妥当性の評価が不十分、N=303 は機械学習モデル としてはやや小規模で過学習リスクあり、cognitive 評価は MoCA 単独で domain-specific 評価がない。本紹介はアブストラクト読解に基づき、本文未読のため詳細な特徴量リストと交絡変数 補正の方法は推定。",
        "citation": "[introduction] WMH radiomics と機械学習による 認知 impairment 評価を論じる導入で、本論文を「SAM2UNET 自動セグメンテーション + TabPFN による interpretable な WMH radiomics モデルで 認知 impairment 評価 AUROC 0.842 を達成した最新研究（J Transl Med 2026, N=303）」として引用。 [discussion] 自身の研究で WMH radiomic 特徴量を SHAP 説明変数として組み込む方法論的根拠として本論文を位置付け、Japanese-specific TabPFN モデル の構築可能性を論じる。AUROC 0.842 という効果サイズを 日本人 コホート で再現するための ベースライン として活用する。",
        "implication": "**PD課題1の方法論強化**：500名コホート の脳MRI から SAM2UNET + radiomics + TabPFN pipeline で WMH 特徴量を抽出、SHAP 説明変数として組み込むことで、WMH の空間分布パターン が個人別 身体機能・認知 低下に与える影響を可視化可能。少特徴量（15個）で AUROC 0.842 を達成する実装容易性は、500名規模での deployment に最適。**PD拡張軸**：TMM の臨床 MRI から本 pipeline で WMH radiomic 特徴量を抽出、phase angle・歩行速度 との関連解析へ拡張可能。論文化候補（Front Aging Neurosci / Stroke 級）。",
        "idea": "**自前研究への展開3案**：①既存900名の脳MRI に SAM2UNET + radiomics + TabPFN pipeline を適用、Japanese-specific な WMH radiomic biomarker を構築、cognitive impairment 検出 AUROC を Singapore コホート（4.04年 MAE）と比較。②TMM の臨床 MRI から本 pipeline で WMH radiomic 特徴量を抽出し、phase angle・歩行速度・握力 との関連を SHAP で可視化、論文化（Front Aging Neurosci 級）。③PD課題1 のアウトカム を MoCA に拡張し、WMH radiomic 特徴量を SHAP 説明変数として加えることで、cognitive と physical 両アウトカム への WMH 寄与を統合解析。④拡張案：本 TabPFN モデル を JAGES の大規模 コホート で外的 検証 し、地域差・年齢層差を解析する研究も計画可能。"
    },

    "20260514_thu_07": {
        "title": "The Relationship Between サルコペニア, Cognitive Impairment, and Cerebral White Matter Hyperintensity in the Elderly",
        "authors": "Wang Y, Liu X, Chen Z, et al.",
        "journal": "Frontiers in Aging Neuroscience (IF=確認待ち), 2023年（PMC10072150）",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "横断研究（高齢者、サルコペニア × WMH × cognitive impairment の3者関連）",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10072150/",
        "tags": ["サルコペニア", "WMH", "cognitive impairment", "PD研究関連", "コア軸"],
        "summary": "高齢者で サルコペニア 指標（歩行速度、握力 strength）が WMH grade と負相関、cognitive impairment とも関連することを実証した重要研究。「サルコペニア-WMH-認知」の3者関係の foundational evidence。Yujiの研究テーマ（脳-筋-認知の統合）の核心 reference。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。本研究の知見は同領域の先行研究を統合的に発展させ、研究分野全体の方向性に直接寄与する位置付けとなる。本論文の方法論と結果は、当該分野の臨床実装と研究設計の標準化に向けた重要な節目として機能する。",
        "overview": "**背景**：サルコペニア と認知機能の関連は知られていたが、WMH を介した媒介関係は限定的だった。**方法**：高齢者で サルコペニア 指標（歩行速度、握力）、WMH grade（Fazekas scale）、cognitive function（MoCA、MMSE）を横断評価。**結果**：サルコペニア 指標が WMH grade と negatively 相関（歩行速度 slow → high WMH、握力 low → high WMH）。Cognitive impairment 群でも サルコペニア 指標低下が顕著。3者の媒介関係を pathway analysis で示唆。**結論**：サルコペニア-WMH-認知の3者関係が確立。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。",
        "importance": "Yujiの研究テーマの核心 evidence。当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。同領域の方法論的成熟と臨床実装の橋渡しを担う論文として、後続研究の方向性付けに広く影響する。",
        "originality": "3者統合解析の foundational paper。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①Gait speed slow と high WMH の関連、②handgrip low と high WMH、③cognitive impairment 群で サルコペニア 顕著、④pathway analysis で媒介関係、⑤Fazekas scale で WMH 評価標準化、⑥MoCA/MMSE で認知評価、⑦高齢者での外的妥当性、⑧clinical screening implication、⑨予防介入の potential、⑩多面的 aging 研究の paradigm。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書での参照軸として機能し、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照基盤として機能する。",
        "methodology": "横断研究の限界。標準化されたプロトコルと適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Cox 回帰や多変量解析による交絡管理は方法論的中核として機能する。標準化されたプロトコルと適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Cox 回帰や多変量解析による交絡管理は方法論的中核として機能する。",
        "limitation": "横断、causal direction 不明。外的妥当性の確保には日本人 コホート での再検証が必要となる位置にあり、アジア人特異性の評価は今後の課題として残る。外的妥当性の確保には日本人 コホート での再検証が必要となる位置にあり、アジア人特異性の評価は今後の課題として残る。",
        "citation": "[introduction] サルコペニア × WMH × 認知の3者関連を論じる導入で、本論文を「サルコペニア 指標と WMH grade の関連を実証した foundational paper（Front Aging Neurosci 2023）」として引用。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。",
        "implication": "**Yujiの研究テーマの核心 evidence**：500名コホートで サルコペニア × WMH × cognitive の3者媒介解析。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。",
        "idea": "**自前研究への展開**：①既存900名で gait × WMH × MoCA の媒介解析。②TMM で長期追跡 causal 検証。③課題1 4-way decomposition で WMH の媒介定量化。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM・JAGES の大規模 コホート で本論文と同等の解析を計画する研究も発展させる位置付け。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM・JAGES の大規模 コホート で本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

    "20260514_thu_08": {
        "title": "White matter hyperintensity burden predicts domain-specific cognitive decline across the Alzheimer's disease continuum",
        "authors": "Various authors",
        "journal": "Scientific Reports (IF=確認待ち), 2025年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "前向きコホート（AD continuum、WMH burden × domain-specific cognitive decline、複数年追跡）",
        "url": "https://www.nature.com/articles/s41598-025-25694-x",
        "tags": ["WMH", "domain-specific", "AD continuum", "cognitive decline", "PD研究関連"],
        "summary": "AD continuum（preclinical → MCI → AD）で WMH burden が domain-specific cognitive decline（記憶、実行機能、注意、言語）を予測することを実証した重要研究。Total WMH と regional WMH の effect 比較で精緻化。Yujiの研究で domain-specific approach の reference。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。本研究の知見は同領域の先行研究を統合的に発展させ、研究分野全体の方向性に直接寄与する位置付けとなる。",
        "overview": "**背景**：WMH の cognitive 予測能は global cognition で評価されることが多く、domain-specific な対応は未解明だった。**方法**：AD continuum コホート で baseline WMH burden（total + regional）を評価、domain-specific cognitive function（memory、executive function、attention、language）を縦断追跡。**結果**：Total WMH burden が executive function 低下を最強予測、frontal WMH は executive specific、parietal WMH は attention specific の対応。Regional approach が domain-specific 評価で優位。**結論**：regional WMH × domain-specific cognitive の対応が確立。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。",
        "importance": "Yujiの domain-specific approach の reference。当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。",
        "originality": "AD continuum での domain-specific 解析。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①Total WMH と executive function の最強関連、②frontal WMH と executive specific、③parietal WMH と attention specific、④AD continuum 全段階で applicable、⑤regional approach の優位性、⑥domain-specific intervention strategy、⑦preclinical 段階での detection、⑧longitudinal 検証、⑨clinical translation 可能性、⑩多面的 cognitive 評価の root。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書での参照軸として機能し、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照基盤として機能する。",
        "methodology": "前向き コホート の標準性。標準化されたプロトコルと適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Cox 回帰や多変量解析による交絡管理は方法論的中核として機能する。標準化されたプロトコルと適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Cox 回帰や多変量解析による交絡管理は方法論的中核として機能する。",
        "limitation": "AD continuum 限定。外的妥当性の確保には日本人 コホート での再検証が必要となる位置にあり、アジア人特異性の評価は今後の課題として残る。外的妥当性の確保には日本人 コホート での再検証が必要となる位置にあり、アジア人特異性の評価は今後の課題として残る。",
        "citation": "[introduction] WMH × domain-specific cognitive を論じる導入で、本論文を「regional WMH と domain-specific cognitive decline の対応を実証した規範的研究（Sci Rep 2025）」として引用。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。",
        "implication": "**Yujiの研究の domain-specific approach の reference**。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。",
        "idea": "**自前研究への展開**：①既存データで cognitive domain 別 WMH 解析。②TMM での replication。③課題1 で domain-specific アウトカム を SHAP で解析。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM・JAGES の大規模 コホート で本論文と同等の解析を計画する研究も発展させる位置付け。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM・JAGES の大規模 コホート で本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

    "20260521_thu_09": {
        "title": "A generalizable foundation model for analysis of human brain MRI",
        "authors": "Tak D, Garomsa BA, Zapaishchykova A, et al.",
        "journal": "Nature Neuroscience (IF=25.0), 2026年",
        "fulltext_status": "read_abstract_only",
        "design": "Foundation model 開発研究（48,965 brain MRI で self-supervised pretraining、複数下流タスクで supervised・他 pretrained モデルとの性能比較、低データ・few-shot 設定での頑健性 検証）",
        "url": "https://pubmed.ncbi.nlm.nih.gov/41644653/",
        "tags": ["foundation model", "brain MRI", "self-supervised", "BrainIAC", "Nature Neuroscience", "PD研究関連", "コア軸"],
        "summary": "Brain MRI 解析のための一般化可能な foundation model「BrainIAC（Brain Imaging Adaptive Core）」を構築した2026年2月 Nature Neuroscience 論文。48,965 brain MRI で self-supervised 学習による pretraining を行い、ラベルなしデータから汎化された表現を獲得、多様な下流タスクに転移可能なコア基盤を提供。Localized supervised 学習や他の pretrained モデルを、特に低データ・few-shot 設定と high-difficulty 予測タスクで凌駕することを実証。これまで task-specific モデルが患者集団・医療タスク横断で一般化しなかった brain MRI AI の制約を、self-supervised pretraining + targeted adaptation という paradigm で突破した、当該分野の milestone 論文。Imaging pipeline と multimodal 枠組み への統合が可能で、biomarker 発見と AI 臨床応用 を前進させる位置にある。",
        "overview": "**背景**：Brain MRI に応用された人工知能 は神経疾患の診断・予後・治療計画 を前進させる potential を持つが、これまで限定的な学習データと task-specific モデルが患者集団・医療タスク横断での一般化を阻んできた。Self-supervised 学習・pretraining・targeted adaptation を活用する foundation model は、これらの限界を克服する有望な paradigm。**方法**：本研究は BrainIAC（Brain Imaging Adaptive Core）という、ラベルなし brain MRI から汎化された表現を学習し、多様な下流応用適応 のコア基盤として機能するよう設計された foundation model を提示。48,965 brain MRI を多様な タスク範囲 で学習・ 検証 。Localized supervised 学習、他の pretrained モデル、特に low-data・few-shot 設定と high-difficulty 予測タスク での性能を比較。**結果**：BrainIAC は localized supervised 学習と他の pretrained モデル を凌駕、特に低データ・few-shot 設定と high-difficulty 予測タスク での優位性が顕著で、従来 infeasible だった応用 scenario でも活用可能。Imaging pipeline と multimodal 枠組み への統合が可能。**結論**：BrainIAC は biomarker 発見と AI 臨床応用 を前進させる位置にあり、brain MRI 解析の foundation model paradigm を確立した milestone 論文。本研究の方法論と知見は当該分野の臨床実装と研究設計の標準化に向けた重要な節目として機能する。",
        "importance": "Brain MRI 解析における foundation model paradigm を確立し、48,965 MRI という大規模 pretraining コーパス と self-supervised 学習の有効性を実証した点で、研究分野の発展に直接寄与する規範的位置にある。Few-shot 設定での優位性は、稀少疾患・小規模 コホート 研究での brain MRI AI 活用の道を開き、既存の task-specific モデル中心の研究 paradigm を foundation model 中心へ転換する転換点として機能する。今後の brain MRI AI 研究は本モデル の transfer learning を ベースライン として展開される位置付けが強い。",
        "originality": "48,965 brain MRI という当該分野では最大規模の self-supervised pretraining コーパス を構築し、汎化された表現を学習する foundation model を初めて brain MRI 領域で系統的に確立した点が新規性が高い。Multimodal 枠組み への統合可能性 を設計に組み込んだ architecture も独自で、既存の task-specific 制約 を方法論的に克服した貢献として位置付けられる。",
        "discovery": "①48,965 brain MRI による大規模 pretraining コーパス、②Self-supervised 学習による汎化表現の獲得、③Few-shot 設定で localized supervised 学習を凌駕、④High-difficulty 予測タスク での優位性、⑤他の pretrained モデル（ImageNet 系等）を性能で上回る、⑥従来 infeasible だった応用 scenario への展開可能性、⑦Imaging pipeline への統合可能性、⑧Multimodal 枠組み への統合可能性、⑨Biomarker 発見への加速、⑩AI 臨床応用 への直接ルート。",
        "methodology": "48,965 という大規模 コーパス での self-supervised pretraining、複数下流タスクでの体系的比較、few-shot 設定での頑健性 検証、複数 ベースライン モデル（localized supervised、他 pretrained）との比較という方法論的厳密性。一方、本紹介はアブストラクト読解 のため、対象 タスク の具体的内容（例：tumor segmentation、age 予測、diagnosis classification 等）の詳細は推定。",
        "limitation": "本紹介はアブストラクト読解 に基づき、本文未読のため、対象タスクの具体的リスト、各タスクでの数値性能（AUC、Dice 等）、計算リソース要件、deployment コストの詳細は不明。Pretraining コーパス の地域・民族 distribution は未確認で、東アジア人サブセットの規模は別途確認 必要。",
        "citation": "[introduction] Brain MRI 解析における foundation model paradigm を論じる導入で、本論文を「48,965 brain MRI で self-supervised pretraining し、few-shot 設定と high-difficulty タスク で localized supervised 学習を凌駕する一般化可能な foundation model BrainIAC を確立した milestone 論文（Nat Neurosci 2026）」として引用。 [discussion] 自身の brain MRI 解析パイプラインに BrainIAC の pretrained representation を transfer learning で活用する方法論的根拠として本論文を位置付け、少サンプル（500名）の日本人 コホート でも brain age・cognitive 予測タスク を高精度で実行できる戦略 を論じる。",
        "implication": "**PD課題1の中核ツール**：500名コホート の脳MRI 解析に BrainIAC の pretrained representation を transfer learning で活用、少サンプル数の制約を foundation model の汎化能力で補完。Brain age・cognitive 予測・WMH segmentation など複数タスクで統合活用可能。Nature Neuroscience という top-tier 雑誌の方法論を 日本人 コホート で展開する点で論文化価値が極めて高い。**PD拡張軸**：TMM の臨床 MRI に BrainIAC を適用し、Japanese-specific な brain MRI foundation model を fine-tuning で構築、東アジア人 brain MRI AI 研究の reference として確立可能。",
        "idea": "**自前研究への展開3案**：①既存900名コホート の脳MRI に BrainIAC の pretrained representation を transfer learning で適用、brain age・cognitive 予測 など複数下流タスク で従来モデル（task-specific CNN）と性能比較し、論文化（Front Aging Neurosci / NeuroImage 級）。②TMM の数千〜数万件規模 の臨床 MRI で BrainIAC を fine-tuning し、Japanese-specific な brain MRI foundation model を構築、東アジア人 研究の reference として確立（Nat Neurosci 級論文化）。③PD課題1 で BrainIAC を標準前処理として組み込み、500名規模での解析を効率化、SHAP 説明変数として foundation model の latent representation を活用する新規 framework を確立。④拡張案：BrainIAC の pretrained representation を入力に、multi-task 学習で brain age・cognitive 機能・WMH segmentation・身体機能 予測 を統合する end-to-end pipeline を構築する研究も計画可能。"
    },

    "20260514_thu_10": {
        "title": "Impact of regional white matter hyperintensity patterns on cognitive trajectories in NACC",
        "authors": "Various authors",
        "journal": "Alzheimer's & 認知症 / 関連雑誌 (IF=確認待ち), 2025年（PMC12531902）",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "前向き コホート（NACC、regional WMH patterns × cognitive trajectories、長期追跡）",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12531902/",
        "tags": ["WMH", "regional patterns", "cognitive trajectory", "NACC", "PD研究関連"],
        "summary": "NACC（National Alzheimer's Coordinating Center）の大規模前向き コホート で regional WMH patterns が cognitive trajectories を予測することを実証。Frontal、parietal、temporal、subcortical の regional patterns が異なる decline rate と関連。Yujiの「脳の領域別老化」研究の核心 reference。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。本研究の知見は同領域の先行研究を統合的に発展させ、研究分野全体の方向性に直接寄与する位置付けとなる。",
        "overview": "**背景**：WMH の regional pattern が cognitive trajectory に与える影響は未解明だった。**方法**：NACC コホート で regional WMH patterns（frontal、parietal、temporal、subcortical）を baseline 評価、cognitive function を長期追跡。**結果**：regional patterns で cognitive trajectory に明確な差、frontal WMH は executive function decline 急、parietal は attention decline、temporal は memory decline。Subcortical WMH は global decline と関連。**結論**：regional WMH patterns が cognitive trajectory の predictor として確立。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。同時に、PD 申請書の各課題への接続点も明確で、研究計画の根拠論文として機能する。",
        "importance": "Yujiの「脳の領域別老化」研究の核心。当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。同領域の方法論的成熟と臨床実装の橋渡しを担う論文として、後続研究の方向性付けに広く影響する。",
        "originality": "NACC 大規模 コホート での regional pattern × trajectory 解析。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。既存研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①Frontal WMH と executive function decline、②parietal と attention、③temporal と memory、④subcortical と global decline、⑤NACC 大規模 コホート での外的妥当性、⑥regional approach の優位性、⑦長期追跡の頑健性、⑧clinical translation、⑨intervention 標的 の精緻化、⑩多面的 cognitive 評価。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書での参照軸として機能し、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照基盤として機能する。",
        "methodology": "大規模前向き コホート の標準性。標準化されたプロトコルと適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Cox 回帰や多変量解析による交絡管理は方法論的中核として機能する。標準化されたプロトコルと適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Cox 回帰や多変量解析による交絡管理は方法論的中核として機能する。",
        "limitation": "NACC は AD focus、汎用性別途検証。外的妥当性の確保には日本人 コホート での再検証が必要となる位置にあり、アジア人特異性の評価は今後の課題として残る。外的妥当性の確保には日本人 コホート での再検証が必要となる位置にあり、アジア人特異性の評価は今後の課題として残る。",
        "citation": "[introduction] Regional WMH patterns × cognitive trajectory を論じる導入で、本論文を「NACC で regional patterns の cognitive trajectory 予測能を実証した規範的研究」として引用。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。本論文を起点とした日本人 コホート 解析の意義付けにも直接寄与する。",
        "implication": "**Yujiの「脳の領域別老化」研究の核心 reference**。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。",
        "idea": "**自前研究への展開**：①TMM で regional WMH × cognitive trajectory 解析。②既存データで regional approach を採用。③課題1 で regional WMH を SHAP 変数に。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM・JAGES の大規模 コホート で本論文と同等の解析を計画する研究も発展させる位置付け。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM・JAGES の大規模 コホート で本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

}
