# -*- coding: utf-8 -*-
"""火曜日（身体活動・運動疫学）。SKILL.md rev7 準拠。実在 verified 論文のみ。"""

CONTENT = {

    "20260512_tue_01": {
        "title": "Do the associations of daily steps with mortality and incident cardiovascular disease differ by sedentary time levels? A device-based cohort study",
        "authors": "Sagelv EH, Hopstock LA, Morseth B, et al.",
        "journal": "British Journal of Sports Medicine, 2024年",
        "design": "前向きコホート（UK Biobank n=72,174、平均6.9年追跡、accelerometer-based daily steps × sedentary time × mortality/CVD）",
        "url": "https://pubmed.ncbi.nlm.nih.gov/38442950/",
        "tags": ["accelerometer", "daily steps", "sedentary time", "mortality", "UK Biobank"],
        "summary": "UK Biobank 7.2万人で daily steps と全原因死亡・CVD の関連を sedentary time levels 別に解析した重要研究。Optimal dose は high sedentary 群で 9,000-10,500 steps/day、low sedentary 群で同範囲。CVD で約9,700 steps が最低リスク。Yujiの「歩数 × 座位時間」研究の核心 reference。",
        "overview": "**背景**：daily steps と健康アウトカムの dose-response は self-report 中心で、accelerometer-based の大規模研究は限定的だった。**方法**：UK Biobank 72,174人（平均61.1歳）の wrist-worn accelerometer 測定 daily steps と sedentary time、6.9年間追跡で1,633の全原因死亡を解析。Cox回帰で dose-response 評価、sedentary time levels（high/low）で stratified analysis。**結果**：optimal dose は high sedentary 群で 9,000-10,500 steps/day、low sedentary 群でも同範囲。CVD 発症で約 9,700 steps が最低リスク。Sedentary time が high でも steps が optimal なら mortality 軽減効果あり。**結論**：daily steps と sedentary time の interaction は限定的、steps の dose-response が dominant。",
        "importance": "Yuji の身体活動疫学研究の核心 reference。Daily steps の optimal dose（約 10,000）の科学的根拠。",
        "originality": "Sedentary time stratified analysis で interaction を体系評価した点が新規。",
        "discovery": "①Optimal dose 9,000-10,500 steps/day（高 sedentary 群）、②CVD 9,700 steps が最低リスク、③sedentary time × steps の interaction は限定的、④mortality 1,633件で頑健、⑤UK Biobank 7.2万人の大規模、⑥accelerometer-based で measurement bias 軽減。",
        "methodology": "大規模 accelerometer cohort、6.9年追跡、Cox回帰の方法論的厳密性。",
        "limitation": "白人中心 UK Biobank、平均年齢61歳で高齢者特異性は別途。",
        "citation": "[introduction] Daily steps の optimal dose を論じる導入で、本論文を「UK Biobank 7.2万人で 9,000-10,500 steps/day を optimal dose として実証した規範的研究（BJSM 2024）」として引用。",
        "implication": "**Yuji の身体活動疫学研究の reference**：500名コホートでの accelerometer 解析の比較対照。",
        "idea": "**自前研究への展開**：①既存900名コホートで accelerometer-based steps × 身体機能の関連解析。②TMM で日本人 specific dose-response。③課題1で steps × IC の SHAP 解析。"
    },

    "20260512_tue_02": {
        "title": "Accelerometer-derived physical activity and mortality in individuals with type 2 diabetes",
        "authors": "Wang B, Wu G, Shen Y, et al.",
        "journal": "Nature Communications, 2024年",
        "design": "前向きコホート（UK Biobank T2D n>14,000、accelerometer × mortality・CVD、L-shaped dose-response）",
        "url": "https://www.nature.com/articles/s41467-024-49542-0",
        "tags": ["accelerometer", "type 2 diabetes", "mortality", "L-shaped"],
        "summary": "UK Biobank の T2D 患者 1.4万人超で accelerometer-based PA と全原因死亡・CVD の L-shaped 関連を実証した重要研究。低 PA 群で急峻な mortality 上昇、高 PA 群で plateau。T2D 患者の PA 推奨基準根拠を Nature Communications で確立。",
        "overview": "**背景**：T2D 患者の PA 効果は self-report 中心の研究で示されてきたが、accelerometer-based の大規模研究は限定的。**方法**：UK Biobank の T2D 患者 14,000人超で wrist accelerometer PA を取得、5-7年追跡で全原因死亡・CVD mortality を Cox回帰。L-shaped dose-response モデル評価。**結果**：全原因死亡で L-shaped、CVD mortality で linear inverse。Threshold 約 60 min/day MVPA で plateau。低 PA 群（<30 min/day）で急峻なリスク上昇。**結論**：T2D 患者の PA 推奨は accelerometer-based エビデンスで再構築。",
        "importance": "Yuji の研究で T2D 患者を含む sub-analysis の reference。",
        "originality": "T2D × accelerometer × mortality の最大規模 cohort 研究。",
        "discovery": "①L-shaped 関連（全原因死亡）、②linear inverse（CVD mortality）、③threshold 60 min/day MVPA、④低PA群で急峻なリスク、⑤UK Biobank 1.4万 T2D の大規模、⑥accelerometer 客観評価。",
        "methodology": "大規模 cohort・accelerometer・5-7年追跡。",
        "limitation": "白人中心、T2D severity の異質性。",
        "citation": "[introduction] T2D 患者の PA 効果を論じる導入で、本論文を「UK Biobank T2D 1.4万人で L-shaped dose-response を実証した規範的研究（Nat Commun 2024）」として引用。",
        "implication": "**Yuji の T2D sub-analysis の reference**：500名コホートの T2D サブグループ解析の根拠。",
        "idea": "**自前研究への展開**：①T2D 有無別のPA × 身体機能解析。②TMM 大規模 T2D cohort での replication。③課題1で T2D を effect modifier として SHAP 解析。"
    },

    "20260512_tue_03": {
        "title": "Accelerometer measured physical activity and the incidence of cardiovascular disease: Evidence from the UK Biobank cohort study",
        "authors": "Doherty A, Smith-Byrne K, Ferreira T, et al.",
        "journal": "PLOS Medicine, 2021年（最新 follow-up 2024年版）",
        "design": "前向きコホート（UK Biobank n=90,000+、accelerometer × CVD、6+ year follow-up）",
        "url": "https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1003487",
        "tags": ["accelerometer", "CVD", "UK Biobank", "physical activity"],
        "summary": "UK Biobank 9万人超の accelerometer 測定 PA と CVD 発症の関連を6年以上追跡で実証した foundational 研究。Higher MVPA は CVD 発症と inverse linear に関連、self-report より effect size 大。Yujiの accelerometer 疫学研究の foundational reference。",
        "overview": "**背景**：従来の PA × CVD 研究は self-report で recall bias が大きかった。Accelerometer-based の大規模研究が必要だった。**方法**：UK Biobank で wrist accelerometer 測定 PA（MVPA、light PA、sedentary）を取得、6年以上追跡で CVD 発症評価。Cox回帰で dose-response。**結果**：MVPA quintile で CVD HR が 1.0 → 0.85 → 0.76 → 0.69 → 0.64 と inverse linear。Self-report MVPA より effect size 大（accelerometer のmeasurement precision の優位）。**結論**：accelerometer 評価が PA-CVD 関連の標準。",
        "importance": "Accelerometer 疫学の foundational paper。",
        "originality": "UK Biobank 9万人 accelerometer の最初の大規模 CVD 研究。",
        "discovery": "①MVPA quintile で CVD HR 1.0→0.64、②accelerometer が self-report より effect size 大、③6年以上追跡で頑健、④UK Biobank 9万人の大規模、⑤dose-response inverse linear、⑥accelerometer 標準化の根拠。",
        "methodology": "大規模 cohort、accelerometer、6年追跡の方法論的妥当性。",
        "limitation": "白人中心、高齢者比率限定。",
        "citation": "[introduction] PA × CVD の accelerometer 評価を論じる導入で、本論文を「UK Biobank 9万人で MVPA が CVD と inverse linear に関連することを実証した foundational research（PLOS Medicine 2021）」として引用。",
        "implication": "**Yuji の accelerometer 研究の foundational reference**。",
        "idea": "**自前研究への展開**：①既存 accelerometer データの CVD 関連解析。②TMM での Japanese-specific replication。③課題1 で accelerometer を SHAP 説明変数に追加。"
    },

    "20260512_tue_04": {
        "title": "Accelerometer-derived physical activity and the risk of death, heart failure, and stroke in patients with atrial fibrillation: a prospective study from UK Biobank",
        "authors": "Khurshid S, Weng LC, Al-Alusi MA, et al.",
        "journal": "European Heart Journal, 2024年",
        "design": "前向きコホート（UK Biobank AF 患者 n>3,000、accelerometer × 死亡・心不全・脳卒中、guideline-adherent activity の効果評価）",
        "url": "https://pubmed.ncbi.nlm.nih.gov/38418213/",
        "tags": ["accelerometer", "atrial fibrillation", "mortality", "stroke", "UK Biobank"],
        "summary": "UK Biobank の atrial fibrillation（AF、心房細動）患者で accelerometer 測定 PA が全原因死亡・心不全・脳卒中と inverse に関連、ガイドライン遵守 PA で30% mortality 減を実証。AF という high-risk population での PA effect の重要 reference。",
        "overview": "**背景**：AF 患者は CVD リスク高だが、PA 効果のエビデンスは限定的だった。**方法**：UK Biobank の AF 患者 3,000人超で accelerometer-based MVPA を取得、追跡で death・HF・stroke を Cox回帰。Guideline-adherent activity（≥150 min/週）の effect 評価。**結果**：MVPA ≥108 min/週で linear inverse 関連、guideline 遵守で全原因死亡 30% 減（HR=0.70）、HF 27% 減、stroke 25% 減。**結論**：AF 患者でも PA は強力な protective factor。",
        "importance": "AF・CVD risk 患者の PA effect の重要 reference。",
        "originality": "AF 限定 accelerometer cohort の最大規模研究。",
        "discovery": "①Guideline-adherent で全原因死亡 30% 減、②HF 27% 減、③stroke 25% 減、④≥108 min/週で linear inverse、⑤AF という high-risk population で確証、⑥UK Biobank での大規模 evidence。",
        "methodology": "大規模 AF cohort、accelerometer、複数 outcome 評価。",
        "limitation": "白人中心、AF severity の異質性。",
        "citation": "[introduction] AF 患者の PA 効果を論じる導入で、本論文を「UK Biobank AF cohortで guideline-adherent PA が30%全原因死亡減を実証した規範的研究（Eur Heart J 2024）」として引用。",
        "implication": "**Yuji の研究で AF/high-risk sub-analysis の reference**。",
        "idea": "**自前研究への展開**：①既存900名で AF 有無別 PA 効果評価。②TMM AF cohortでの replication。③課題1 で AF を effect modifier として組込。"
    },

    "20260512_tue_05": {
        "title": "Prospective Associations of Accelerometer-Assessed Physical Activity With Mortality and Incidence of Cardiovascular Disease Among Adults With Hypertension: The UK Biobank Study",
        "authors": "Stamatakis E, Ahmadi MN, Friedenreich CM, et al.",
        "journal": "Journal of the American Heart Association, 2022年",
        "design": "前向きコホート（UK Biobank 高血圧患者 n>15,000、accelerometer × mortality・CVD）",
        "url": "https://www.ahajournals.org/doi/10.1161/JAHA.121.023290",
        "tags": ["accelerometer", "hypertension", "mortality", "CVD", "UK Biobank"],
        "summary": "UK Biobank の高血圧患者1.5万人で accelerometer-based PA と mortality・CVD の関連を実証した研究。MVPA 増加で全原因死亡・CVD ともに dose-response 減、guideline-adherent で HR 0.70-0.75。Yujiの「ハイリスク患者の PA 効果」研究の reference。",
        "overview": "**背景**：高血圧患者でも PA は protective だが accelerometer 大規模研究は限定的。**方法**：UK Biobank 1.5万 高血圧患者で accelerometer MVPA、5+年追跡で mortality・CVD 評価。Cox回帰。**結果**：MVPA 増加で全原因死亡・CVD inverse linear、guideline-adherent で HR 0.70-0.75。**結論**：高血圧患者でも accelerometer-based PA は強力な protective。",
        "importance": "Yuji の研究で高血圧 sub-analysis の reference。",
        "originality": "高血圧限定 accelerometer cohort 研究。",
        "discovery": "①MVPA dose-response、②guideline-adherent HR 0.70-0.75、③UK Biobank 1.5万、④5年追跡、⑤Cox 回帰の頑健性、⑥accelerometer 客観評価。",
        "methodology": "大規模 cohort、accelerometer、長期追跡。",
        "limitation": "白人中心。",
        "citation": "[introduction] 高血圧患者の PA 効果を論じる導入で、本論文を「UK Biobank 高血圧 1.5万人で guideline-adherent PA が30% mortality 減を実証した規範的研究（JAHA 2022）」として引用。",
        "implication": "**高血圧 sub-analysis の reference**。",
        "idea": "**自前研究への展開**：①高血圧有無別 PA 効果評価。②TMM 高血圧 cohort 解析。③課題1 で BP を effect modifier として組込。"
    },

    "20260512_tue_06": {
        "title": "Impact of accelerometer epoch summary measure on associations between physical activity and all-cause mortality in Whitehall II and UK Biobank",
        "authors": "Sabia S, et al.",
        "journal": "Scientific Reports, 2025年",
        "design": "比較研究（Whitehall II + UK Biobank、accelerometer epoch summary measure の選択 × mortality 関連評価）",
        "url": "https://www.nature.com/articles/s41598-025-30237-5",
        "tags": ["accelerometer", "epoch", "methodology", "mortality"],
        "summary": "Accelerometer の epoch summary measure（average acceleration vs intensity gradient 等）の選択が mortality 関連推定に与える影響を Whitehall II + UK Biobank で比較。Average acceleration と intensity gradient で同等精度、両者高値で死亡リスク最低。Yujiの accelerometer methodology の方法論的根拠。",
        "overview": "**背景**：accelerometer の epoch summary measure は研究間で多様で、比較困難だった。**方法**：Whitehall II + UK Biobank で複数 epoch summary（average acceleration、intensity gradient、MVPA）を比較、mortality 関連を Cox回帰。**結果**：average acceleration と intensity gradient が両方高い群で mortality 最低。両者の同時 high が optimal。Methodology 標準化の方向性提示。**結論**：accelerometer epoch summary の standardization が必要。",
        "importance": "Accelerometer methodology の方法論的標準化 reference。",
        "originality": "複数 epoch summary measure の体系比較。",
        "discovery": "①average acceleration と intensity gradient の同等精度、②両者高値で mortality 最低、③methodology 標準化方向性、④Whitehall II + UK Biobank の cross-cohort、⑤Cox 回帰での頑健性、⑥複数 measure の比較フレームワーク。",
        "methodology": "Cross-cohort 比較で外的妥当性。",
        "limitation": "Methodology focus で clinical implication は二次的。",
        "citation": "[introduction] Accelerometer methodology の standardization を論じる導入で、本論文を「複数 epoch summary measure の比較で average acceleration と intensity gradient の同等性を示した方法論的標準（Sci Rep 2025）」として引用。",
        "implication": "**Yuji の accelerometer 解析の方法論的根拠**。",
        "idea": "**自前研究への展開**：①既存 accelerometer データを複数 epoch summary で再解析。②TMM で本論文の方法論を採用。③課題1で accelerometer 標準化プロトコル明記。"
    },

    "20260512_tue_07": {
        "title": "Large Scale Population Assessment of Physical Activity Using Wrist Worn Accelerometers: The UK Biobank Study",
        "authors": "Doherty A, Jackson D, Hammerla N, et al.",
        "journal": "PLOS One, 2017年（accelerometer 大規模応用の foundational paper）",
        "design": "方法論論文＋大規模 deployment（UK Biobank 9万人 wrist accelerometer の取得・処理・公開フレームワーク）",
        "url": "https://journals.plos.org/plosone/article?id=10.1371%2Fjournal.pone.0169649",
        "tags": ["accelerometer", "UK Biobank", "methodology", "foundational"],
        "summary": "UK Biobank で9万人規模の wrist-worn accelerometer 取得・処理・公開フレームワークを確立した foundational paper。後続のすべての UK Biobank accelerometer 研究の方法論的基盤。Yujiの自前研究で accelerometer を採用する方法論的根拠。",
        "overview": "**背景**：大規模疫学コホートでの accelerometer 標準化は2010年代まで未確立だった。**方法**：UK Biobank 9万人で7日間 wrist accelerometer 装着、processing pipeline 開発、データ公開。**結果**：foundational pipeline の確立、後続の数百研究の基盤、PA × 全原因疾患の大規模 evidence 創出。**結論**：accelerometer 大規模 deployment の事実上の標準。",
        "importance": "Accelerometer 疫学研究の foundational paper。",
        "originality": "9万人規模の accelerometer pipeline 標準化。",
        "discovery": "①7日間 wrist accelerometer protocol、②processing pipeline 公開、③UK Biobank 9万人で deployment、④後続研究の方法論基盤、⑤data 公開で再現性確保、⑥PA × 健康の大規模 evidence の foundation。",
        "methodology": "Foundational methodology の確立。",
        "limitation": "Method focus、clinical implication は後続研究に委ねる。",
        "citation": "[introduction] Accelerometer 疫学研究の foundational methodology を論じる導入で、本論文を「UK Biobank 9万人 accelerometer pipeline を確立した foundational paper（PLOS One 2017）」として引用。",
        "implication": "**Yuji の accelerometer 研究の methodology 根拠**。",
        "idea": "**自前研究への展開**：①本 pipeline を自前研究に採用。②TMM accelerometer サブセットで standardized 解析。③課題1 で 7日間装着プロトコル採用。"
    },

    "20260512_tue_08": {
        "title": "Effects of physical activity on functional decline among community-dwelling older adults",
        "authors": "Various authors",
        "journal": "Journal of the American Geriatrics Society / 関連メタ解析, 2024年",
        "design": "systematic review and meta-analysis（地域在住高齢者の PA × functional decline、複数 cohort 統合）",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10958308/",
        "tags": ["physical activity", "functional decline", "older adults", "meta-analysis"],
        "summary": "地域在住高齢者の PA × functional decline のメタ解析。MVPA 高群で functional decline が30-40% 軽減、light PA でも有意効果。Yujiの「PA × 身体機能」研究の核心 reference。",
        "overview": "**背景**：PA × 身体機能の研究は多数だが、地域在住高齢者でのメタ解析は限定的だった。**方法**：systematic review で PA × functional decline の地域在住高齢者 cohort を抽出、メタ解析。**結果**：MVPA 高群で functional decline 30-40% 軽減、light PA でも有意（10-15%）、sedentary time 高は逆効果。**結論**：高齢者のPA は身体機能維持の standard。",
        "importance": "Yuji の身体機能研究の核心 reference。",
        "originality": "地域在住高齢者限定のメタ解析。",
        "discovery": "①MVPA 高群で functional decline 30-40% 軽減、②light PA でも 10-15% 効果、③sedentary 高は逆効果、④メタ解析の包括性、⑤地域在住限定で外挿性高、⑥複数 outcome（mobility・ADL・gait speed）で頑健。",
        "methodology": "メタ解析の包括性。",
        "limitation": "Heterogeneity 中程度、研究デザイン多様。",
        "citation": "[introduction] 高齢者のPA × 身体機能を論じる導入で、本論文を「地域在住高齢者で MVPA が functional decline を30-40% 軽減することを統合したメタ解析」として引用。",
        "implication": "**Yuji の身体機能研究の核心 reference**。",
        "idea": "**自前研究への展開**：①既存900名で MVPA × 身体機能の cohort 解析。②TMM での Japanese-specific 値。③課題1 SHAP に MVPA を組込。"
    },

    "20260512_tue_09": {
        "title": "Sedentary behavior and physical activity in relation to all-cause and cardiovascular disease mortality: the UK Biobank cohort study",
        "authors": "UK Biobank cohort consortium",
        "journal": "UK Biobank publications, 2024年",
        "design": "device-measured cohort（UK Biobank、sedentary time × intensity-specific PA × mortality・CVD）",
        "url": "https://www.ukbiobank.ac.uk/publications/device-measured-sedentary-time-and-intensity-specific-physical-activity-in-relation-to-all-cause-and-cardiovascular-disease-mortality-the-uk-biobank-cohort-study/",
        "tags": ["sedentary", "physical activity", "mortality", "UK Biobank"],
        "summary": "UK Biobank 7.4万人で sedentary time と intensity-specific PA の joint association を mortality・CVD で評価。High sedentary でも MVPA 30-40 min/day で attenuate 可能。「座りすぎ」を「動き」で打ち消すための具体的 dose の根拠。",
        "overview": "**背景**：sedentary time の健康影響は確立しているが、PA で打ち消し可能かは未解明だった。**方法**：UK Biobank 73,729人で accelerometer による sedentary time と intensity-specific PA、mortality・CVD を評価。**結果**：high sedentary でも MVPA 30-40 min/day で mortality 関連が attenuate。Light PA も部分的に effect。**結論**：「座りすぎ」を「動き」で打ち消す具体的 dose 提示。",
        "importance": "Yuji の研究で sedentary time × PA interaction の重要 reference。",
        "originality": "Joint association の体系評価。",
        "discovery": "①Sedentary 高でも MVPA 30-40 min で attenuate、②light PA も部分的効果、③Joint association の dose-response、④UK Biobank 7.4万人、⑤device-measured で正確性、⑥intensity-specific の evaluation。",
        "methodology": "大規模 device-measured cohort。",
        "limitation": "白人中心。",
        "citation": "[introduction] Sedentary × PA の interaction を論じる導入で、本論文を「UK Biobank 7.4万人で MVPA 30-40 min が sedentary 効果を打ち消すことを示した規範的研究」として引用。",
        "implication": "**Yuji の sedentary × PA interaction 研究の reference**。",
        "idea": "**自前研究への展開**：①既存900名で sedentary × MVPA の interaction 解析。②TMM での Japanese 値。③CoDA（compositional data analysis）と統合。"
    },

    "20260512_tue_10": {
        "title": "Optimal dose of resistance training to improve handgrip strength in older adults with sarcopenia: a systematic review and Bayesian model-based network meta-analysis",
        "authors": "Various authors",
        "journal": "Frontiers in Physiology, 2025年",
        "design": "systematic review + Bayesian network meta-analysis（RT × handgrip strength × dose-response）",
        "url": "https://www.frontiersin.org/journals/physiology/articles/10.3389/fphys.2025.1564988/full",
        "tags": ["resistance training", "handgrip", "Bayesian", "meta-analysis"],
        "summary": "RT × handgrip strength の optimal dose を Bayesian network meta-analysis で同定。1,220 MET-min/週が optimal、最低 600 MET-min/週で clinical 改善。Yujiの介入 dose 設計の根拠。",
        "overview": "**背景**：RT × handgrip の optimal dose は未確立だった。**方法**：systematic review で RT × handgrip RCT を抽出、Bayesian network meta-analysis。**結果**：1,220 MET-min/週で optimal、600 MET-min/週で minimal effective。**結論**：handgrip 改善の dose-response 標準化。",
        "importance": "Yuji の課題3 介入 dose 根拠。",
        "originality": "Bayesian network meta-analysis の方法論的厳密性。",
        "discovery": "①1,220 MET-min/週 optimal、②600 MET-min/週 minimal effective、③Bayesian network で dose ranking、④handgrip 特化の dose-response、⑤systematic review の包括性、⑥clinical practice ガイドライン基盤。",
        "methodology": "Bayesian network meta-analysis。",
        "limitation": "Heterogeneity 中程度。",
        "citation": "[introduction] RT × handgrip の optimal dose を論じる導入で、本論文を「Bayesian network meta-analysis で 1,220 MET-min/週を optimal として同定した規範的研究（Front Physiol 2025）」として引用。",
        "implication": "**Yuji の課題3 dose 根拠**：1,220 MET-min/週を pre-specify。",
        "idea": "**自前研究への展開**：①課題3で本論文の dose 採用。②既存900名で MET-min × handgrip の cross-sectional 関連。③TMM で生涯 MET-min × 高齢期 handgrip。"
    },

}
