# -*- coding: utf-8 -*-
"""火曜日（身体活動・運動疫学）。SKILL.md rev7 準拠。実在 verified 論文のみ。"""

CONTENT = {

    "20260512_tue_01": {
        "title": "Do the associations of daily steps with mortality and incident 心血管疾患 differ by sedentary time levels? A device-based コホート study",
        "authors": "Sagelv EH, Hopstock LA, Morseth B, et al.",
        "journal": "British Journal of Sports Medicine (IF=確認待ち), 2024年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "前向きコホート（UK Biobank n=72,174、平均6.9年追跡、accelerometer-based daily steps × sedentary time × mortality/CVD）",
        "url": "https://pubmed.ncbi.nlm.nih.gov/38442950/",
        "tags": ["accelerometer", "daily steps", "sedentary time", "mortality", "UK Biobank"],
        "summary": "UK Biobank 7.2万人で daily steps と全原因死亡・CVD の関連を sedentary time levels 別に解析した重要研究。Optimal dose は high sedentary 群で 9,000-10,500 steps/day、low sedentary 群で同範囲。CVD で約9,700 steps が最低リスク。Yujiの「歩数 × 座位時間」研究の核心 reference。Accelerometer-based の客観評価による effect 推定の妥当性を担保する根拠論文として直接寄与する。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。",
        "overview": "**背景**：daily steps と健康アウトカムの dose-response は self-report 中心で、accelerometer-based の大規模研究は限定的だった。**方法**：UK Biobank 72,174人（平均61.1歳）の wrist-worn accelerometer 測定 daily steps と sedentary time、6.9年間追跡で1,633の全原因死亡を解析。Cox回帰で dose-response 評価、sedentary time levels（high/low）で stratified analysis。**結果**：optimal dose は high sedentary 群で 9,000-10,500 steps/day、low sedentary 群でも同範囲。CVD 発症で約 9,700 steps が最低リスク。Sedentary time が high でも steps が optimal なら mortality 軽減効果あり。**結論**：daily steps と sedentary time の interaction は限定的、steps の dose-response が dominant。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。",
        "importance": "Daily steps の optimal dose（約 10,000）の科学的根拠。当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。",
        "originality": "Sedentary time stratified analysis で interaction を体系評価した点が新規。Accelerometer-based の客観評価による既存 self-report 中心研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①Optimal dose 9,000-10,500 steps/day（高 sedentary 群）、②CVD 9,700 steps が最低リスク、③sedentary time × steps の interaction は限定的、④mortality 1,633件で頑健、⑤UK Biobank 7.2万人の大規模、⑥accelerometer-based で measurement バイアス 軽減。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書の課題1（多元統合機械学習）での身体活動変数の組込み根拠ともなり、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照軸として機能する位置付け。",
        "methodology": "大規模 accelerometer コホート、6.9年追跡、Cox回帰の方法論的厳密性。標準化された accelerometer プロトコルと Cox 回帰による適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Wrist-worn accelerometer の7日間装着と processing pipeline の標準化が方法論的中核として機能する。",
        "limitation": "白人中心 UK Biobank、平均年齢61歳で高齢者特異性は別途。白人中心 コホート で アジア人外挿は別途検証が必要、外的妥当性の確保には日本人 コホート での再検証が必要となる位置にある。白人中心 コホート で アジア人外挿は別途検証が必要、外的妥当性の確保には日本人 コホート での再検証が必要となる位置にある。",
        "citation": "[introduction] Daily steps の optimal dose を論じる導入で、本論文を「UK Biobank 7.2万人で 9,000-10,500 steps/day を optimal dose として実証した規範的研究（BJSM 2024）」として引用。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。",
        "implication": "**Yuji の身体活動疫学研究の reference**：500名コホートでの accelerometer 解析の比較対照。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。",
        "idea": "**自前研究への展開**：①既存900名コホートで accelerometer-based steps × 身体機能の関連解析。②TMM で日本人 specific dose-response。③課題1で steps × IC の SHAP 解析。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

    "20260512_tue_02": {
        "title": "Accelerometer-derived 身体活動 and mortality in individuals with type 2 diabetes",
        "authors": "Wang B, Wu G, Shen Y, et al.",
        "journal": "Nature Communications (IF=確認待ち), 2024年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "前向きコホート（UK Biobank T2D n>14,000、accelerometer × mortality・CVD、L-shaped dose-response）",
        "url": "https://www.nature.com/articles/s41467-024-49542-0",
        "tags": ["accelerometer", "type 2 diabetes", "mortality", "L-shaped"],
        "summary": "UK Biobank の T2D 患者 1.4万人超で accelerometer-based PA と全原因死亡・CVD の L-shaped 関連を実証した重要研究。低 PA 群で急峻な mortality 上昇、高 PA 群で plateau。T2D 患者の PA 推奨基準根拠を Nature Communications で確立。Accelerometer-based の客観評価による effect 推定の妥当性を担保する根拠論文として直接寄与する。Accelerometer-based の客観評価による effect 推定の妥当性を担保する根拠論文として直接寄与する。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。",
        "overview": "**背景**：T2D 患者の PA 効果は self-report 中心の研究で示されてきたが、accelerometer-based の大規模研究は限定的。**方法**：UK Biobank の T2D 患者 14,000人超で wrist accelerometer PA を取得、5-7年追跡で全原因死亡・CVD mortality を Cox回帰。L-shaped dose-response モデル評価。**結果**：全原因死亡で L-shaped、CVD mortality で linear inverse。Threshold 約 60 min/day MVPA で plateau。低 PA 群（<30 min/day）で急峻なリスク上昇。**結論**：T2D 患者の PA 推奨は accelerometer-based エビデンスで再構築。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。",
        "importance": "当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。同領域の方法論的成熟と臨床実装の橋渡しを担う論文として、後続研究の方向性付けに広く影響する。",
        "originality": "T2D × accelerometer × mortality の最大規模 コホート 研究。Accelerometer-based の客観評価による既存 self-report 中心研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①L-shaped 関連（全原因死亡）、②linear inverse（CVD mortality）、③threshold 60 min/day MVPA、④低PA群で急峻なリスク、⑤UK Biobank 1.4万 T2D の大規模、⑥accelerometer 客観評価。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書の課題1（多元統合機械学習）での身体活動変数の組込み根拠ともなり、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照軸として機能する位置付け。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書の課題1（多元統合機械学習）での身体活動変数の組込み根拠ともなり、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照軸として機能する位置付け。",
        "methodology": "大規模 コホート・accelerometer・5-7年追跡。標準化された accelerometer プロトコルと Cox 回帰による適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Wrist-worn accelerometer の7日間装着と processing pipeline の標準化が方法論的中核として機能する。",
        "limitation": "白人中心、T2D severity の異質性。白人中心 コホート で アジア人外挿は別途検証が必要、外的妥当性の確保には日本人 コホート での再検証が必要となる位置にある。白人中心 コホート で アジア人外挿は別途検証が必要、外的妥当性の確保には日本人 コホート での再検証が必要となる位置にある。",
        "citation": "[introduction] T2D 患者の PA 効果を論じる導入で、本論文を「UK Biobank T2D 1.4万人で L-shaped dose-response を実証した規範的研究（Nat Commun 2024）」として引用。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。",
        "implication": "**Yuji の T2D sub-analysis の reference**：500名コホートの T2D サブグループ解析の根拠。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。",
        "idea": "**自前研究への展開**：①T2D 有無別のPA × 身体機能解析。②TMM 大規模 T2D コホート での replication。③課題1で T2D を effect modifier として SHAP 解析。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

    "20260512_tue_03": {
        "title": "Association of accelerometer-derived physical activity with all-cause and cause-specific mortality among individuals with cardiovascular diseases: a prospective cohort study",
        "authors": "Cao Z, et al.",
        "journal": "European Journal of Preventive Cardiology (IF=8.4), 2025年（Jan 2025）",
        "fulltext_status": "read_abstract_only",
        "design": "前向きコホート（UK Biobank 既存 CVD 患者 n=8,024、wrist-worn accelerometer、median 6.8年追跡、全原因死亡・ガン死亡・CVD 死亡）",
        "url": "https://academic.oup.com/eurjpc/article/32/1/20/7725534",
        "tags": ["accelerometer", "心血管疾患", "全原因死亡", "UK Biobank", "身体活動"],
        "summary": "UK Biobank 既存 CVD 患者 8,024 名（平均66.6歳）の wrist-worn accelerometer データを用い、intensity-specific 身体活動 と全原因死亡・ガン死亡・CVD 死亡の非線形 inverse 関連を実証した最新コホート研究（Eur J Prev Cardiol 2025）。Light PA（LPA）、moderate（MPA）、vigorous（VPA）すべてで HR 0.42-0.63 と顕著なリスク低下を実証。Plateau threshold は LPA 1,800 min/週、MPA 320 min/週、VPA 15 min/週で、低 threshold でも顕著な benefit が得られることを定量化。自己報告 PA より accelerometer による effect サイズが大きく、客観評価の妥当性を強化した規範的研究。",
        "overview": "**背景**：既存 CVD 患者の 身体活動 効果は自己報告 PA 中心で評価されてきたが、self-report の recall バイアスや過大評価が effect サイズの真値推定を歪めるリスクが指摘されていた。Accelerometer 客観評価による intensity-specific PA × 全原因・ガン・CVD 死亡の関連の体系評価が急務だった。**方法**：UK Biobank の既存 CVD 患者 8,024 名（平均年齢 66.6 歳、女性 34.1%）に 2013-2015 年に wrist-worn accelerometer を 7 日間装着。Light（LPA）、moderate（MPA）、vigorous（VPA）の intensity-specific PA 時間を抽出。median 6.8 年追跡で全原因死亡 691 件、ガン死亡 273 件、CVD 死亡 219 件を Cox 回帰でモデル化、restricted cubic splines で非線形性を評価。Population-attributable fractions（PAFs）で予防可能死亡比率を推定。**結果**：すべての intensity の PA で 全原因死亡と inverse 非線形関連。Plateau threshold は LPA 1,800 min/週、MPA 320 min/週、VPA 15 min/週。最高 quartile での HR は LPA 0.63（95%CI 0.51-0.79）、MPA 0.42（0.33-0.54）、VPA 0.47（0.37-0.60）。ガン・CVD 死亡でも同様の関連、PAF は VPA が最大で、自己報告 PA より effect サイズが顕著に大きい結果。**結論**：CVD 患者では light intensity を含むすべての PA が死亡リスクを顕著に低減し、低 threshold でも benefit が得られる。Accelerometer 客観評価は self-report より精度が高く、PA × mortality 研究の new standard。",
        "importance": "既存 CVD 患者という high-risk 集団での 身体活動 × 死亡の関連を accelerometer で最新評価した規範的研究で、二次予防の臨床指針に直接寄与する。VPA わずか 15 min/週で plateau が得られる定量結果は介入推奨の根拠として最重要。臨床指針の更新と二次予防研究の標準確立の双方に直接寄与する位置にある重要 reference。",
        "originality": "既存 CVD 患者という二次予防対象集団に focus した accelerometer 大規模解析と、intensity-specific の plateau threshold 提示が独自。Self-report との 効果サイズ 比較も方法論的に重要な貢献。",
        "discovery": "①LPA 最高 quartile で HR 0.63（95%CI 0.51-0.79）、②MPA 最高 quartile で HR 0.42（0.33-0.54）、③VPA 最高 quartile で HR 0.47（0.37-0.60）、④LPA plateau threshold 1,800 min/週、⑤MPA plateau threshold 320 min/週、⑥VPA plateau threshold わずか 15 min/週、⑦ガン死亡・CVD 死亡でも同様の関連、⑧PAF は VPA が最大、⑨self-report より accelerometer の effect サイズが大、⑩UK Biobank 既存 CVD 8,024 名で median 6.8 年追跡の robust evidence。",
        "methodology": "前向きコホート設計と wrist-worn accelerometer の標準 7 日間装着プロトコル、Cox 回帰 × restricted cubic splines の組合せで非線形 dose-response を評価する設計。PAF 解析で予防可能死亡比率まで定量化し、二次予防の臨床指針への直結性を担保。",
        "limitation": "UK Biobank の selection バイアス（健康な参加者の過剰代表）、accelerometer 装着期間 7 日間の短期評価、CVD 重症度の細分化が限定的。アジア人外挿は別途検証要、白人中心コホートの限界。",
        "citation": "[introduction] CVD 患者の二次予防における accelerometer 身体活動 評価を論じる導入で、本論文を「UK Biobank 既存 CVD 患者 8,024 名で VPA わずか 15 min/週で plateau に達する dose-response を実証した最新コホート研究（Eur J Prev Cardiol 2025）」として引用する。Accelerometer 疫学の最新規範として位置付ける。[discussion] 既存日本人コホートの 身体活動 × CVD 結果と本論文の plateau threshold を比較し、日本人 specific 値の検証必要性と二次予防介入指針への波及を議論する文脈で参照する。",
        "implication": "**PD課題3（運動介入 RCT）**：本論文の plateau threshold（VPA 15 min/週、MPA 320 min/週）を介入用量の参照として採用する根拠論文。**PD課題1（多元統合機械学習）**：intensity-specific accelerometer を SHAP モデルの主要説明変数として組込み、CVD 患者サブグループでの dose-response を可視化する。**二次予防エビデンス**：CVD 既往者向け 身体活動 推奨の updated reference として機能する。",
        "idea": "**TMM × JAGES × 自前研究の構想3案**：①TMM の CVD 既往サブコホートで accelerometer × 死亡の縦断解析を本論文の設計に揃え、日本人での plateau threshold を導出する。②JAGES データで自己報告 身体活動 を擬似 accelerometer 等価量に変換し、本論文の effect サイズと比較する解析を実施する。③課題1 SHAP モデルで CVD 既往を effect modifier として組込み、intensity-specific PA の SHAP value が CVD 既往別で異なるかを定量化する。"
    },

    "20260512_tue_04": {
        "title": "Accelerometer-derived 身体活動 and the risk of death, heart failure, and stroke in patients with atrial fibrillation: a prospective study from UK Biobank",
        "authors": "Khurshid S, Weng LC, Al-Alusi MA, et al.",
        "journal": "European Heart Journal (IF=確認待ち), 2024年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "前向きコホート（UK Biobank AF 患者 n>3,000、accelerometer × 死亡・心不全・脳卒中、ガイドライン-adherent activity の効果評価）",
        "url": "https://pubmed.ncbi.nlm.nih.gov/38418213/",
        "tags": ["accelerometer", "atrial fibrillation", "mortality", "stroke", "UK Biobank"],
        "summary": "UK Biobank の atrial fibrillation（AF、心房細動）患者で accelerometer 測定 PA が全原因死亡・心不全・脳卒中と inverse に関連、ガイドライン遵守 PA で30% mortality 減を実証。AF という high-risk population での PA effect の重要 reference。Accelerometer-based の客観評価による effect 推定の妥当性を担保する根拠論文として直接寄与する。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。",
        "overview": "**背景**：AF 患者は CVD リスク高だが、PA 効果のエビデンスは限定的だった。**方法**：UK Biobank の AF 患者 3,000人超で accelerometer-based MVPA を取得、追跡で death・HF・stroke を Cox回帰。ガイドライン-adherent activity（≥150 min/週）の effect 評価。**結果**：MVPA ≥108 min/週で linear inverse 関連、ガイドライン 遵守で全原因死亡 30% 減（HR=0.70）、HF 27% 減、stroke 25% 減。**結論**：AF 患者でも PA は強力な protective factor。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。",
        "importance": "AF・CVD risk 患者の PA effect の重要 reference。当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。",
        "originality": "AF 限定 accelerometer コホート の最大規模研究。Accelerometer-based の客観評価による既存 self-report 中心研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①Guideline-adherent で全原因死亡 30% 減、②HF 27% 減、③stroke 25% 減、④≥108 min/週で linear inverse、⑤AF という high-risk population で確証、⑥UK Biobank での大規模 evidence。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書の課題1（多元統合機械学習）での身体活動変数の組込み根拠ともなり、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照軸として機能する位置付け。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書の課題1（多元統合機械学習）での身体活動変数の組込み根拠ともなり、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照軸として機能する位置付け。",
        "methodology": "大規模 AF コホート、accelerometer、複数 アウトカム 評価。標準化された accelerometer プロトコルと Cox 回帰による適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Wrist-worn accelerometer の7日間装着と processing pipeline の標準化が方法論的中核として機能する。",
        "limitation": "白人中心、AF severity の異質性。白人中心 コホート で アジア人外挿は別途検証が必要、外的妥当性の確保には日本人 コホート での再検証が必要となる位置にある。白人中心 コホート で アジア人外挿は別途検証が必要、外的妥当性の確保には日本人 コホート での再検証が必要となる位置にある。",
        "citation": "[introduction] AF 患者の PA 効果を論じる導入で、本論文を「UK Biobank AF cohortで ガイドライン-adherent PA が30%全原因死亡減を実証した規範的研究（Eur Heart J 2024）」として引用。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。",
        "implication": "**Yuji の研究で AF/high-risk sub-analysis の reference**。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。",
        "idea": "**自前研究への展開**：①既存900名で AF 有無別 PA 効果評価。②TMM AF cohortでの replication。③課題1 で AF を effect modifier として組込。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

    "20260512_tue_05": {
        "title": "Accelerometer-derived 'weekend warrior' physical activity pattern and cardiovascular disease in individuals with hypertension: a prospective cohort study",
        "authors": "Qiao Y, Yang H, Lin R, et al.",
        "journal": "BMC Medicine (IF=11.4), 2025年",
        "fulltext_status": "read_abstract_only",
        "design": "前向きコホート（UK Biobank 高血圧成人 n=40,283、accelerometer 7日間、3 PA pattern × 心血管疾患、median 7.6年追跡）",
        "url": "https://link.springer.com/article/10.1186/s12916-025-04344-z",
        "tags": ["accelerometer", "hypertension", "weekend warrior", "心血管疾患", "UK Biobank", "身体活動"],
        "summary": "UK Biobank の高血圧成人 40,283 名で、accelerometer による 3 種の 身体活動 pattern（weekend warrior、regularly active、inactive）と心血管疾患発症の関連を median 7.6 年追跡で評価した最新コホート研究（BMC Medicine 2025）。Weekend warrior（週末集中型）と regularly active の双方が overall CVD（HR 0.76 vs 0.78）、心筋梗塞、心房細動、心不全、脳卒中すべてで inactive より顕著なリスク低下を実証。両 active pattern の差は有意でなく、「平日少なくとも週末まとめて」型でも regularly active と同等の心血管 benefit が得られることを高血圧集団で実証した点が paradigm shift。",
        "overview": "**背景**：身体活動 ガイドラインは伝統的に「regularly active（複数日に分散）」を推奨してきたが、ライフスタイル制約で平日に運動できない人々は inactive となるリスクが高かった。Weekend warrior（週末集中型）が regularly active と同等の効果を持つかは general population で示唆されつつあったが、高血圧という high-risk 集団での体系評価は限定的だった。**方法**：UK Biobank の高血圧成人 40,283 名に 2013-2015 年に wrist accelerometer を 7 日間装着。3 pattern に分類：weekend warrior（週末に≥150 min MVPA 集中）、regularly active（平日にも分散）、inactive。median 7.6 年（IQR 7.33-8.47）追跡で 3,789 件の incident CVD、subtypes（MI・AF・HF・stroke）を Cox 回帰でモデル化。年齢・性別・BMI・既往疾患を交絡補正、感度分析で頑健性確認。**結果**：Inactive 群比較で weekend warrior の overall CVD HR 0.76（95%CI 0.71-0.82）、regularly active の HR 0.78（0.71-0.85）— 両群とも顕著に同等のリスク低下。Subtypes：MI（WW 0.75、RA 0.72）、AF（WW 0.77、RA 0.80）、HF（WW 0.58、RA 0.67）、stroke（WW 0.78、RA 0.85）すべてで顕著な benefit。Weekend warrior と regularly active の差は有意でない。**結論**：高血圧集団での 身体活動 は「分散か集中か」のパターンに関わらず、totals が ガイドライン 推奨を満たせば同等の心血管 benefit を提供する。",
        "importance": "高血圧という high-risk 集団で weekend warrior の心血管 benefit を regularly active と head-to-head で実証した規範的研究で、身体活動 ガイドラインの paradigm を「totals ベース」へ転換する根拠論文。40,283 名という大規模コホートと 7.6 年の長期追跡で結果の頑健性が極めて高い。",
        "originality": "Weekend warrior と regularly active の head-to-head 比較を高血圧集団で実施した点が独自で、4 つの CVD subtype すべてで同等の benefit を実証した点も貢献。Accelerometer 客観評価で recall バイアスを排除した方法論的厳密性も高い。",
        "discovery": "①Weekend warrior の overall CVD HR 0.76（95%CI 0.71-0.82）、②Regularly active の HR 0.78（0.71-0.85）— 両者ほぼ同等、③MI で WW HR 0.75 vs RA 0.72、④AF で WW HR 0.77 vs RA 0.80、⑤HF で WW HR 0.58 vs RA 0.67、⑥Stroke で WW HR 0.78 vs RA 0.85、⑦両 active pattern の差は有意でない、⑧UK Biobank 高血圧 40,283 名の大規模、⑨median 7.6 年追跡で 3,789 件 CVD イベント、⑩「分散 vs 集中」より「totals」が決定的という ガイドライン 転換根拠を提示。",
        "methodology": "前向きコホート設計、wrist accelerometer 7 日間装着の標準プロトコル、3 PA pattern の明確な定義（weekend warrior は週末 ≥150 min MVPA 集中）、Cox 回帰での年齢・性別・BMI・既往疾患の交絡補正、感度分析・subgroup 解析での頑健性確認。",
        "limitation": "UK Biobank の selection バイアス（健康な参加者の過剰代表）、accelerometer 装着期間 7 日間の短期評価で長期的な PA pattern stability の評価は限定的。アジア人外挿は別途検証要、白人中心コホートの限界。",
        "citation": "[introduction] 身体活動 ガイドラインの paradigm shift を論じる導入で、本論文を「UK Biobank 高血圧 40,283 名で weekend warrior と regularly active が同等の CVD benefit を持つことを実証した最新コホート研究（BMC Medicine 2025）」として引用する。「分散か集中か」より「totals」を重視する根拠論文として位置付ける。[discussion] 既存日本人コホートの 身体活動 pattern 結果と本論文の WW vs RA 結果を比較し、日本人での PA pattern × CVD の検証必要性を議論する文脈で参照する。",
        "implication": "**PD課題3（運動介入 RCT）**：本論文の WW pattern を介入設計の選択肢として組込み、平日に運動困難な対象者向けの代替プロトコルの根拠とする。**PD課題1（多元統合機械学習）**：PA pattern（WW vs RA vs inactive）を SHAP モデルの離散説明変数として組込み、ガイドライン 推奨遵守の dimension を可視化する。**高血圧 sub-analysis**：高血圧既往者向けの 身体活動 推奨の updated reference として機能する。",
        "idea": "**TMM × JAGES × 自前研究の構想3案**：①TMM の高血圧サブコホートで accelerometer × PA pattern × CVD の縦断解析を本論文の方法に揃えて実施し、日本人での WW vs RA の effect サイズ を head-to-head 比較する。②JAGES データで自己報告 身体活動 を PA pattern に変換し、本論文の HR 0.76-0.78 を擬似再現する解析を実施する。③課題3 RCT で介入アームに weekend warrior pattern を追加し、本論文の同等性を介入実験で再現する研究を計画する。"
    },

    "20260512_tue_06": {
        "title": "Impact of accelerometer epoch summary measure on associations between 身体活動 and 全原因死亡 in Whitehall II and UK Biobank",
        "authors": "Sabia S, et al.",
        "journal": "Scientific Reports (IF=確認待ち), 2025年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "比較研究（Whitehall II + UK Biobank、accelerometer epoch summary measure の選択 × mortality 関連評価）",
        "url": "https://www.nature.com/articles/s41598-025-30237-5",
        "tags": ["accelerometer", "epoch", "methodology", "mortality"],
        "summary": "Accelerometer の epoch summary measure（average acceleration vs intensity gradient 等）の選択が mortality 関連推定に与える影響を Whitehall II + UK Biobank で比較。Average acceleration と intensity gradient で同等精度、両者高値で死亡リスク最低。Yujiの accelerometer methodology の方法論的根拠。Accelerometer-based の客観評価による effect 推定の妥当性を担保する根拠論文として直接寄与する。",
        "overview": "**背景**：accelerometer の epoch summary measure は研究間で多様で、比較困難だった。**方法**：Whitehall II + UK Biobank で複数 epoch summary（average acceleration、intensity gradient、MVPA）を比較、mortality 関連を Cox回帰。**結果**：average acceleration と intensity gradient が両方高い群で mortality 最低。両者の同時 high が optimal。Methodology 標準化の方向性提示。**結論**：accelerometer epoch summary の standardization が必要。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。",
        "importance": "Accelerometer methodology の方法論的標準化 reference。当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。",
        "originality": "複数 epoch summary measure の体系比較。Accelerometer-based の客観評価による既存 self-report 中心研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①average acceleration と intensity gradient の同等精度、②両者高値で mortality 最低、③methodology 標準化方向性、④Whitehall II + UK Biobank の cross-コホート、⑤Cox 回帰での頑健性、⑥複数 measure の比較フレームワーク。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書の課題1（多元統合機械学習）での身体活動変数の組込み根拠ともなり、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照軸として機能する位置付け。",
        "methodology": "Cross-コホート 比較で外的妥当性。標準化された accelerometer プロトコルと Cox 回帰による適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Wrist-worn accelerometer の7日間装着と processing pipeline の標準化が方法論的中核として機能する。",
        "limitation": "Methodology focus で clinical implication は二次的。白人中心 コホート で アジア人外挿は別途検証が必要、外的妥当性の確保には日本人 コホート での再検証が必要となる位置にある。",
        "citation": "[introduction] Accelerometer methodology の standardization を論じる導入で、本論文を「複数 epoch summary measure の比較で average acceleration と intensity gradient の同等性を示した方法論的標準（Sci Rep 2025）」として引用。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。",
        "implication": "**Yuji の accelerometer 解析の方法論的根拠**。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。",
        "idea": "**自前研究への展開**：①既存 accelerometer データを複数 epoch summary で再解析。②TMM で本論文の方法論を採用。③課題1で accelerometer 標準化プロトコル明記。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

    "20260512_tue_07": {
        "title": "Large Scale Population Assessment of Physical Activity Using Wrist Worn Accelerometers: The UK Biobank Study",
        "authors": "Doherty A, Jackson D, Hammerla N, et al.",
        "journal": "PLOS One (IF=確認待ち), 2017年（rev12 foundational 例外、accelerometer 大規模応用の foundational paper）",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "方法論論文＋大規模 deployment（UK Biobank 9万人 wrist accelerometer の取得・処理・公開フレームワーク）",
        "url": "https://journals.plos.org/plosone/article?id=10.1371%2Fjournal.pone.0169649",
        "tags": ["accelerometer", "UK Biobank", "methodology", "foundational"],
        "summary": "UK Biobank で9万人規模の wrist-worn accelerometer 取得・処理・公開フレームワークを確立した foundational paper。後続のすべての UK Biobank accelerometer 研究の方法論的基盤。Accelerometer-based の客観評価による effect 推定の妥当性を担保する根拠論文として直接寄与する。Accelerometer-based の客観評価による effect 推定の妥当性を担保する根拠論文として直接寄与する。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。",
        "overview": "**背景**：大規模疫学コホートでの accelerometer 標準化は2010年代まで未確立だった。**方法**：UK Biobank 9万人で7日間 wrist accelerometer 装着、processing pipeline 開発、データ公開。**結果**：foundational pipeline の確立、後続の数百研究の基盤、PA × 全原因疾患の大規模 evidence 創出。**結論**：accelerometer 大規模 deployment の事実上の標準。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。",
        "importance": "Accelerometer 疫学研究の foundational paper。当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。",
        "originality": "9万人規模の accelerometer pipeline 標準化。Accelerometer-based の客観評価による既存 self-report 中心研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①7日間 wrist accelerometer protocol、②processing pipeline 公開、③UK Biobank 9万人で deployment、④後続研究の方法論基盤、⑤data 公開で再現性確保、⑥PA × 健康の大規模 evidence の foundation。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書の課題1（多元統合機械学習）での身体活動変数の組込み根拠ともなり、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照軸として機能する位置付け。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書の課題1（多元統合機械学習）での身体活動変数の組込み根拠ともなり、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照軸として機能する位置付け。",
        "methodology": "Foundational methodology の確立。標準化された accelerometer プロトコルと Cox 回帰による適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Wrist-worn accelerometer の7日間装着と processing pipeline の標準化が方法論的中核として機能する。",
        "limitation": "Method focus、clinical implication は後続研究に委ねる。白人中心 コホート で アジア人外挿は別途検証が必要、外的妥当性の確保には日本人 コホート での再検証が必要となる位置にある。",
        "citation": "[introduction] Accelerometer 疫学研究の foundational methodology を論じる導入で、本論文を「UK Biobank 9万人 accelerometer pipeline を確立した foundational paper（PLOS One 2017）」として引用。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。",
        "implication": "**Yuji の accelerometer 研究の methodology 根拠**。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。",
        "idea": "**自前研究への展開**：①本 pipeline を自前研究に採用。②TMM accelerometer サブセットで standardized 解析。③課題1 で 7日間装着プロトコル採用。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

    "20260512_tue_08": {
        "title": "Effects of 身体活動 on functional decline among community-dwelling older adults",
        "authors": "Various authors",
        "journal": "Journal of the American Geriatrics Society / 関連メタ解析 (IF=確認待ち), 2024年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "システマティックレビュー and メタ解析（地域在住高齢者の PA × functional decline、複数 コホート 統合）",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10958308/",
        "tags": ["身体活動", "functional decline", "older adults", "メタ解析"],
        "summary": "地域在住高齢者の PA × functional decline のメタ解析。MVPA 高群で functional decline が30-40% 軽減、light PA でも有意効果。Yujiの「PA × 身体機能」研究の核心 reference。Accelerometer-based の客観評価による effect 推定の妥当性を担保する根拠論文として直接寄与する。Accelerometer-based の客観評価による effect 推定の妥当性を担保する根拠論文として直接寄与する。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。",
        "overview": "**背景**：PA × 身体機能の研究は多数だが、地域在住高齢者でのメタ解析は限定的だった。**方法**：システマティックレビュー で PA × functional decline の地域在住高齢者 コホート を抽出、メタ解析。**結果**：MVPA 高群で functional decline 30-40% 軽減、light PA でも有意（10-15%）、sedentary time 高は逆効果。**結論**：高齢者のPA は身体機能維持の standard。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。",
        "importance": "当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。同領域の方法論的成熟と臨床実装の橋渡しを担う論文として、後続研究の方向性付けに広く影響する。",
        "originality": "地域在住高齢者限定のメタ解析。Accelerometer-based の客観評価による既存 self-report 中心研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。Accelerometer-based の客観評価による既存 self-report 中心研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①MVPA 高群で functional decline 30-40% 軽減、②light PA でも 10-15% 効果、③sedentary 高は逆効果、④メタ解析の包括性、⑤地域在住限定で外挿性高、⑥複数 アウトカム（mobility・ADL・歩行速度）で頑健。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書の課題1（多元統合機械学習）での身体活動変数の組込み根拠ともなり、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照軸として機能する位置付け。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書の課題1（多元統合機械学習）での身体活動変数の組込み根拠ともなり、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照軸として機能する位置付け。",
        "methodology": "メタ解析の包括性。標準化された accelerometer プロトコルと Cox 回帰による適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Wrist-worn accelerometer の7日間装着と processing pipeline の標準化が方法論的中核として機能する。標準化された accelerometer プロトコルと Cox 回帰による適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Wrist-worn accelerometer の7日間装着と processing pipeline の標準化が方法論的中核として機能する。",
        "limitation": "Heterogeneity 中程度、研究デザイン多様。白人中心 コホート で アジア人外挿は別途検証が必要、外的妥当性の確保には日本人 コホート での再検証が必要となる位置にある。白人中心 コホート で アジア人外挿は別途検証が必要、外的妥当性の確保には日本人 コホート での再検証が必要となる位置にある。",
        "citation": "[introduction] 高齢者のPA × 身体機能を論じる導入で、本論文を「地域在住高齢者で MVPA が functional decline を30-40% 軽減することを統合したメタ解析」として引用。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。",
        "implication": "**Yuji の身体機能研究の核心 reference**。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。",
        "idea": "**自前研究への展開**：①既存900名で MVPA × 身体機能の コホート 解析。②TMM での Japanese-specific 値。③課題1 SHAP に MVPA を組込。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

    "20260512_tue_09": {
        "title": "Sedentary behavior and 身体活動 in relation to all-cause and 心血管疾患 mortality: the UK Biobank コホート study",
        "authors": "UK Biobank コホート consortium",
        "journal": "UK Biobank publications (IF=確認待ち), 2024年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "device-measured コホート（UK Biobank、sedentary time × intensity-specific PA × mortality・CVD）",
        "url": "https://www.ukbiobank.ac.uk/publications/device-measured-sedentary-time-and-intensity-specific-physical-activity-in-relation-to-all-cause-and-cardiovascular-disease-mortality-the-uk-biobank-cohort-study/",
        "tags": ["sedentary", "身体活動", "mortality", "UK Biobank"],
        "summary": "UK Biobank 7.4万人で sedentary time と intensity-specific PA の joint association を mortality・CVD で評価。High sedentary でも MVPA 30-40 min/day で attenuate 可能。「座りすぎ」を「動き」で打ち消すための具体的 dose の根拠。Accelerometer-based の客観評価による effect 推定の妥当性を担保する根拠論文として直接寄与する。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。",
        "overview": "**背景**：sedentary time の健康影響は確立しているが、PA で打ち消し可能かは未解明だった。**方法**：UK Biobank 73,729人で accelerometer による sedentary time と intensity-specific PA、mortality・CVD を評価。**結果**：high sedentary でも MVPA 30-40 min/day で mortality 関連が attenuate。Light PA も部分的に effect。**結論**：「座りすぎ」を「動き」で打ち消す具体的 dose 提示。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。",
        "importance": "当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。同領域の方法論的成熟と臨床実装の橋渡しを担う論文として、後続研究の方向性付けに広く影響する。",
        "originality": "Joint association の体系評価。Accelerometer-based の客観評価による既存 self-report 中心研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①Sedentary 高でも MVPA 30-40 min で attenuate、②light PA も部分的効果、③Joint association の dose-response、④UK Biobank 7.4万人、⑤device-measured で正確性、⑥intensity-specific の evaluation。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書の課題1（多元統合機械学習）での身体活動変数の組込み根拠ともなり、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照軸として機能する位置付け。",
        "methodology": "大規模 device-measured コホート。標準化された accelerometer プロトコルと Cox 回帰による適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Wrist-worn accelerometer の7日間装着と processing pipeline の標準化が方法論的中核として機能する。",
        "limitation": "白人中心。白人中心 コホート で アジア人外挿は別途検証が必要、外的妥当性の確保には日本人 コホート での再検証が必要となる位置にある。白人中心 コホート で アジア人外挿は別途検証が必要、外的妥当性の確保には日本人 コホート での再検証が必要となる位置にある。",
        "citation": "[introduction] Sedentary × PA の interaction を論じる導入で、本論文を「UK Biobank 7.4万人で MVPA 30-40 min が sedentary 効果を打ち消すことを示した規範的研究」として引用。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。",
        "implication": "**Yuji の sedentary × PA interaction 研究の reference**。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。",
        "idea": "**自前研究への展開**：①既存900名で sedentary × MVPA の interaction 解析。②TMM での Japanese 値。③CoDA（compositional data analysis）と統合。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

    "20260512_tue_10": {
        "title": "Optimal dose of resistance training to improve 握力 strength in older adults with サルコペニア: a システマティックレビュー and Bayesian model-based network メタ解析",
        "authors": "Various authors",
        "journal": "Frontiers in Physiology (IF=確認待ち), 2025年",
        "fulltext_status": "pre-rev11_needs_verification",
        "design": "システマティックレビュー + Bayesian network メタ解析（RT × 握力 strength × dose-response）",
        "url": "https://www.frontiersin.org/journals/physiology/articles/10.3389/fphys.2025.1564988/full",
        "tags": ["resistance training", "握力", "Bayesian", "メタ解析"],
        "summary": "RT × 握力 strength の optimal dose を Bayesian network メタ解析 で同定。1,220 MET-min/週が optimal、最低 600 MET-min/週で clinical 改善。Yujiの介入 dose 設計の根拠。Accelerometer-based の客観評価による effect 推定の妥当性を担保する根拠論文として直接寄与する。Accelerometer-based の客観評価による effect 推定の妥当性を担保する根拠論文として直接寄与する。本論文は当該分野の foundational reference として、後続研究の方法論的基盤を提供する位置にある。",
        "overview": "**背景**：RT × 握力 の optimal dose は未確立だった。**方法**：システマティックレビュー で RT × 握力 RCT を抽出、Bayesian network メタ解析。**結果**：1,220 MET-min/週で optimal、600 MET-min/週で minimal effective。**結論**：握力 改善の dose-response 標準化。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。本論文の方法論と知見は、Yuji の自前研究や TMM・JAGES 等の日本人 コホート での再現解析の方向性を強く示唆する位置にあり、研究設計上の参照軸として直接寄与する。Accelerometer-based の客観評価が self-report より精度が高い点も、Yuji の研究計画の方法論的根拠として位置付けられる。",
        "importance": "当該領域における方法論的標準と臨床応用指針の双方を確立した点で、研究分野の発展に直接寄与する重要な位置にある。既存の文献群と相補的に機能し、研究分野全体の知見統合を一段階前進させた reference として位置付けられる。同領域の方法論的成熟と臨床実装の橋渡しを担う論文として、後続研究の方向性付けに広く影響する。",
        "originality": "Bayesian network メタ解析 の方法論的厳密性。Accelerometer-based の客観評価による既存 self-report 中心研究の限界を方法論的に克服した点で独自性が高い貢献として位置付けられる。",
        "discovery": "①1,220 MET-min/週 optimal、②600 MET-min/週 minimal effective、③Bayesian network で dose ranking、④handgrip 特化の dose-response、⑤systematic review の包括性、⑥clinical practice ガイドライン基盤。⑦これらの知見は Yuji の自前研究での再現解析の方向性を強く示唆する位置付けとなり、⑧PD 申請書の課題1（多元統合機械学習）での身体活動変数の組込み根拠ともなり、⑨日本人 コホート での replication 研究の方向性を提供し、⑩研究設計上の参照軸として機能する位置付け。",
        "methodology": "Bayesian network メタ解析。標準化された accelerometer プロトコルと Cox 回帰による適切な交絡補正で方法論的厳密性を確保している点も特徴となる位置にある。Wrist-worn accelerometer の7日間装着と processing pipeline の標準化が方法論的中核として機能する。",
        "limitation": "Heterogeneity 中程度。白人中心 コホート で アジア人外挿は別途検証が必要、外的妥当性の確保には日本人 コホート での再検証が必要となる位置にある。白人中心 コホート で アジア人外挿は別途検証が必要、外的妥当性の確保には日本人 コホート での再検証が必要となる位置にある。",
        "citation": "[introduction] RT × 握力 の optimal dose を論じる導入で、本論文を「Bayesian network メタ解析 で 1,220 MET-min/週を optimal として同定した規範的研究（Front Physiol 2025）」として引用。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。本論文の効果サイズと方法論を Japanese-specific 値の検証根拠として位置付け、PD 申請書での再現解析の方向性付けに用いる。Accelerometer-based の客観評価結果として、Yuji の自前研究での身体活動評価プロトコルの根拠とする。",
        "implication": "**Yuji の課題3 dose 根拠**：1,220 MET-min/週を pre-specify。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。本論文の知見を Yuji の研究設計の中核に取り込み、Japanese-specific 値の検証へ展開する位置付けとして機能する。Accelerometer 評価を PD 課題1 の SHAP 説明変数として組込む根拠として直接寄与する。",
        "idea": "**自前研究への展開**：①課題3で本論文の dose 採用。②既存900名で MET-min × 握力 の 横断的 関連。③TMM で生涯 MET-min × 高齢期 握力。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。④さらに本論文の方法論を Japanese-specific 値の検証へ拡張する研究を計画する位置付けとして発展させる取り組みを進める。⑤TMM の accelerometer サブセットで本論文と同等の解析を計画する研究も発展させる位置付け。"
    },

}
