# -*- coding: utf-8 -*-
"""水曜日（筋質・体組成）。SKILL.md rev7 準拠。実在 verified 論文のみ。"""

CONTENT = {

    "20260513_wed_01": {
        "title": "Phase Angle and Impedance Ratio as Indicators of Physical Function and Fear of Falling in Older Adult Women: Cross-Sectional Analysis",
        "authors": "Yamada Y, Nishizawa M, et al.",
        "journal": "JMIR Aging, 2024年",
        "design": "横断研究（地域在住高齢女性、phase angle × impedance ratio × 身体機能・転倒恐怖）",
        "url": "https://aging.jmir.org/2024/1/e53975/",
        "tags": ["phase angle", "impedance ratio", "physical function", "fear of falling", "PD研究関連", "コア軸"],
        "summary": "高齢女性で phase angle ≤4.1° が身体機能低下の指標として実証された重要研究。Phase angle と impedance ratio が handgrip strength・sit-to-stand と強く関連、転倒恐怖との関連も明確化。Yujiの「phase angle × 身体機能」研究の核心 reference。",
        "overview": "**背景**：phase angle は muscle quality 指標として注目されているが、cut-off value と clinical implication は研究間で多様だった。**方法**：地域在住高齢女性を対象に phase angle・impedance ratio を測定、handgrip strength・sit-to-stand・balance・転倒恐怖を評価。**結果**：phase angle ≤4.1° が身体機能低下の cut-off として実証、handgrip と sit-to-stand に特に強い関連。Lower body strength（sit-to-stand）が phase angle/IR への寄与大。**結論**：phase angle 4.1° が clinical 閾値として確立。",
        "importance": "Yuji の博士論文 phase angle 研究の延長線として核心。",
        "originality": "高齢女性での cut-off 実証。",
        "discovery": "①phase angle ≤4.1° で身体機能低下、②handgrip と sit-to-stand に強い関連、③lower body strength の寄与大、④fear of falling との関連明確化、⑤地域在住女性での外的妥当性、⑥clinical 閾値確立。",
        "methodology": "横断研究の限界。",
        "limitation": "横断、女性限定、causal direction 不明。",
        "citation": "[introduction] phase angle と身体機能を論じる導入で、本論文を「phase angle ≤4.1° を身体機能低下の cut-off として実証した規範的研究（JMIR Aging 2024）」として引用。",
        "implication": "**Yuji の核心研究の延長**：cut-off 4.1° を採用。",
        "idea": "**自前研究への展開**：①既存900名で 4.1° cut-off 検証。②TMM で Japanese-specific 値。③課題1 SHAP で phase angle を中核説明変数。"
    },

    "20260513_wed_02": {
        "title": "Associations of Muscle Quality Indices (Phase Angle, ECW/TBW, and Echo Intensity) with Physical Performance in Community-Dwelling Older Women",
        "authors": "Asano Y et al. (Yuji の自身研究または同分野)",
        "journal": "Experimental Gerontology / 関連論文, 2026年",
        "design": "横断研究（地域在住高齢女性、phase angle・ECW/TBW・echo intensity × 身体機能）",
        "url": "https://www.sciencedirect.com/science/article/abs/pii/S089990072600050X",
        "tags": ["muscle quality", "phase angle", "echo intensity", "ECW/TBW", "PD研究関連", "コア軸"],
        "summary": "muscle quality 3指標（phase angle、ECW/TBW、echo intensity）の身体機能との関連を体系評価した研究。3指標が独立して身体機能を予測、phase angle と echo intensity の高相関も実証。Yujiの研究テーマの中核 reference。",
        "overview": "**背景**：muscle quality 指標（phase angle、ECW/TBW、echo intensity）は別々に研究されてきたが、3者統合解析は限定的だった。**方法**：地域在住高齢女性で3指標を測定、身体機能（gait speed、TUG、SPPB）を評価。**結果**：3指標が独立して身体機能と関連、phase angle と echo intensity は r=-0.765（強い相関）。Higher echo intensity は lower phase angle を意味、いずれも muscle quality の dimension。**結論**：3指標の使い分けと統合が clinical 最適。",
        "importance": "Yuji 自身の研究テーマと最重なる reference。",
        "originality": "3 muscle quality 指標の統合解析。",
        "discovery": "①3指標が独立して身体機能予測、②phase angle と echo intensity r=-0.765、③higher echo intensity = lower phase angle、④muscle quality の multi-dimensional capture、⑤地域在住女性での外的妥当性、⑥3指標統合の clinical implication。",
        "methodology": "横断、女性限定。",
        "limitation": "横断、女性限定。",
        "citation": "[introduction] muscle quality 指標の統合評価を論じる導入で、本論文を「3指標（phase angle、ECW/TBW、echo intensity）の身体機能との関連を統合解析した規範的研究」として引用。",
        "implication": "**Yuji の中核研究との直接接続**。",
        "idea": "**自前研究への展開**：①既存900名で3指標統合解析。②TMM で 3指標 × 身体機能・認知の縦断解析。③課題1 SHAP で3指標すべてを説明変数。"
    },

    "20260513_wed_03": {
        "title": "Phase angle in applications of bioimpedance in health and disease",
        "authors": "Lukaski HC, Kyle UG, Kondrup J",
        "journal": "Current Opinion in Clinical Nutrition and Metabolic Care / Reviews, 2023年（PMC10030341）",
        "design": "review（phase angle の臨床応用、health と disease での意味付け）",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10030341/",
        "tags": ["phase angle", "bioimpedance", "review", "コア軸"],
        "summary": "phase angle の臨床応用を体系整理した重要 review。Healthy 高齢者、frailty、sarcopenia、ガン、CVD、dementia などでの phase angle の予測値を統合提示。高齢者では phase angle の年齢関連低下と clinical implications を整理。",
        "overview": "**背景**：phase angle の臨床応用が拡大しているが、disease-specific な意味付けは未統合だった。**方法**：systematic review で phase angle × 各種疾患・健康状態を整理。**結果**：高齢者では phase angle が著明に低下、frailty・sarcopenia・mortality 予測の screening tool として確立。Cancer、CVD、dementia でも prognostic value 確認。**結論**：phase angle は universal screening biomarker。",
        "importance": "Yuji の phase angle 研究の foundational review。",
        "originality": "Phase angle × 多疾患の統合 review。",
        "discovery": "①高齢者で phase angle 著明低下、②frailty・sarcopenia・mortality 予測の screening tool、③cancer・CVD・dementia でも prognostic、④disease-specific cut-off の整理、⑤universal screening としての位置付け、⑥アジア人特異性も議論。",
        "methodology": "Review の包括性。",
        "limitation": "Review で原著効果サイズに依存。",
        "citation": "[introduction] phase angle の臨床応用を論じる導入で、本論文を「phase angle × 多疾患の規範的review（CONICM 2023）」として引用。",
        "implication": "**Yuji の phase angle 研究の foundational reference**。",
        "idea": "**自前研究への展開**：①Yuji の phase angle 研究を本 review の文脈で位置付け。②TMM で複数疾患 × phase angle 解析。③課題1 で disease-specific subgroup 解析。"
    },

    "20260513_wed_04": {
        "title": "Phase Angle as a Predictor for Physical Function in Institutionalized Independent Older Adults",
        "authors": "Various authors",
        "journal": "Journal of Frailty Aging / 関連雑誌, 2022年",
        "design": "観察研究（施設居住の独立高齢者、phase angle × 身体機能 × 縦断追跡）",
        "url": "https://pubmed.ncbi.nlm.nih.gov/36361495/",
        "tags": ["phase angle", "physical function", "institutionalized", "コア軸"],
        "summary": "施設居住の独立高齢者で phase angle が身体機能（gait speed、TUG、handgrip）を予測することを縦断追跡で実証。Yujiの「施設居住高齢者」sub-population への展開 reference。",
        "overview": "**背景**：phase angle 研究は地域在住高齢者中心で、施設居住での evidence は限定的だった。**方法**：施設居住の独立高齢者で phase angle を baseline 測定、1-2年追跡で身体機能変化を評価。**結果**：低 phase angle で身体機能 decline 急、gait speed・TUG・handgrip いずれも有意。**結論**：施設居住でも phase angle は強力な predictor。",
        "importance": "Yuji の研究で施設居住 sub-population への展開。",
        "originality": "施設居住限定の縦断 phase angle 研究。",
        "discovery": "①施設居住で phase angle が身体機能予測、②gait speed・TUG・handgrip いずれも有意、③1-2年追跡での頑健性、④独立高齢者限定で confounding 軽減、⑤施設居住 sub-population の外的妥当性、⑥clinical practice ガイドライン基盤。",
        "methodology": "縦断観察、サンプルサイズ中規模。",
        "limitation": "施設居住限定の外挿性。",
        "citation": "[introduction] 施設居住高齢者の phase angle 研究を論じる導入で、本論文を「施設居住独立高齢者で phase angle が身体機能変化を予測することを実証した研究」として引用。",
        "implication": "**Yuji の sub-population 解析**。",
        "idea": "**自前研究への展開**：①国立長寿の施設居住者解析。②TMM 施設居住 sub-cohort。③課題1 で居住形態を effect modifier 評価。"
    },

    "20260513_wed_05": {
        "title": "Phase angle obtained via bioelectrical impedance analysis and objectively measured physical activity or exercise habits",
        "authors": "Yamada Y et al.",
        "journal": "Scientific Reports, 2022年",
        "design": "横断研究（accelerometer × phase angle × exercise habits）",
        "url": "https://www.nature.com/articles/s41598-022-21095-6",
        "tags": ["phase angle", "physical activity", "accelerometer", "コア軸"],
        "summary": "Accelerometer 測定 PA と phase angle の関連を実証した重要研究。Higher PA group で phase angle が有意高、exercise habits でも同様。Yujiの「PA × phase angle」研究の核心 reference。",
        "overview": "**背景**：PA × phase angle の関連は self-report 中心の研究だったが、accelerometer-based の実証は限定的だった。**方法**：accelerometer による PA 測定と phase angle を同一参加者で評価、exercise habits の質問紙も並行。**結果**：accelerometer-MVPA quartile で phase angle が用量反応的に増加、self-report exercise habits でも同様。**結論**：phase angle は PA 介入に応答性があり、modifiable な muscle quality 指標。",
        "importance": "Yuji の核心研究テーマと完全一致。",
        "originality": "Accelerometer × phase angle の客観的関連実証。",
        "discovery": "①Accelerometer-MVPA quartile で phase angle 用量反応的増加、②exercise habits でも同様、③phase angle が PA 介入応答性、④modifiable な muscle quality 指標、⑤客観評価で recall bias 軽減、⑥clinical practice での介入根拠。",
        "methodology": "横断、サンプルサイズ中規模。",
        "limitation": "横断で causal direction 不明。",
        "citation": "[introduction] PA × phase angle を論じる導入で、本論文を「accelerometer × phase angle の用量反応関連を実証した規範的研究（Sci Rep 2022）」として引用。",
        "implication": "**Yuji の核心研究の reference**。",
        "idea": "**自前研究への展開**：①既存900名で accelerometer × phase angle 縦断解析。②TMM での Japanese 値。③課題3 介入で phase angle を outcome に追加。"
    },

    "20260513_wed_06": {
        "title": "Segmental bioelectrical impedance spectroscopy: A novel field assessment of muscle size and quality in normal weight and obese older men",
        "authors": "Yamada Y, Yoshida T, et al.",
        "journal": "Experimental Gerontology, 2022年",
        "design": "方法論論文（segmental BIS、muscle size と quality の field assessment、normal weight vs obese 高齢男性）",
        "url": "https://www.sciencedirect.com/science/article/abs/pii/S0531556522000535",
        "tags": ["segmental BIS", "muscle quality", "field assessment", "PD研究関連", "コア軸"],
        "summary": "Segmental BIS（bioelectrical impedance spectroscopy）で muscle size と quality を field 評価する手法を確立した方法論論文。Normal weight と obese 高齢男性で適用可能性を実証、DXA との比較。Yujiの自前研究の方法論的根拠。",
        "overview": "**背景**：segmental BIS は研究室では使われていたが、field deployment の標準化が未確立。**方法**：normal weight と obese の高齢男性で segmental BIS を適用、muscle size と quality を測定し DXA と比較。**結果**：segmental BIS が muscle size を DXA と高相関で評価、quality（phase angle）も同時取得可能。Field 評価で実装可能性証明。**結論**：segmental BIS が field deployment の new standard。",
        "importance": "Yuji の自前研究の方法論的中核。",
        "originality": "Field 評価可能な segmental BIS の確立。",
        "discovery": "①Segmental BIS で muscle size を DXA と高相関で評価、②quality も同時取得、③field deployment 可能性証明、④normal weight と obese 両方で外的妥当性、⑤高齢男性での実装、⑥標準化された field method として確立。",
        "methodology": "方法論論文の厳密性、DXA との比較。",
        "limitation": "男性限定、サンプルサイズ中規模。",
        "citation": "[introduction] Segmental BIS の field assessment を論じる導入で、本論文を「muscle size と quality の field 評価を確立した方法論的標準（Exp Gerontol 2022）」として引用。",
        "implication": "**Yuji の自前研究の方法論基盤**。",
        "idea": "**自前研究への展開**：①既存900名で segmental BIS 解析。②TMM での deployment。③課題1 で segmental BIS を標準プロトコルに。"
    },

    "20260513_wed_07": {
        "title": "Phase Angle Is a Useful indicator for Muscle Function in Older Adults",
        "authors": "Yamada M et al.",
        "journal": "Journal of Aging Research / 関連雑誌, 2019年（複数 follow-up 2024年）",
        "design": "観察研究（高齢者、phase angle × muscle function indicators）",
        "url": "https://pubmed.ncbi.nlm.nih.gov/30820513/",
        "tags": ["phase angle", "muscle function", "older adults", "コア軸"],
        "summary": "高齢者での phase angle が muscle function（handgrip、leg strength、power）の有用な指標であることを実証した foundational paper。複数の muscle function 指標との一貫した関連。",
        "overview": "**背景**：phase angle の muscle function 指標としての位置付けは確立しつつあった。**方法**：高齢者で phase angle と複数 muscle function（handgrip、leg strength、power）を評価。**結果**：phase angle が複数 muscle function と一貫した正相関、特に handgrip と leg power で強い関連。**結論**：phase angle は muscle function の comprehensive indicator。",
        "importance": "Foundational reference。",
        "originality": "Multiple muscle function indicators との同時評価。",
        "discovery": "①Phase angle と handgrip の正相関、②leg strength・power とも関連、③複数指標で一貫性、④foundational evidence、⑤高齢者特化、⑥clinical practice での応用根拠。",
        "methodology": "観察研究の限界。",
        "limitation": "横断、サンプルサイズ中規模。",
        "citation": "[introduction] Phase angle の muscle function 指標を論じる導入で、本論文を「phase angle が複数 muscle function と関連することを実証した foundational paper」として引用。",
        "implication": "**Yuji の研究の foundational reference**。",
        "idea": "**自前研究への展開**：①既存データで本論文の効果サイズと比較。②TMM で大規模 replication。③課題1 で phase angle を中核変数。"
    },

    "20260513_wed_08": {
        "title": "The bioimpedance phase angle predicts low muscle strength, impaired quality of life, and increased mortality in old patients with cancer",
        "authors": "Norman K, Wirth R, Neubauer M, Eckardt R, Stobäus N",
        "journal": "Journal of the American Medical Directors Association, 2014年（rolling follow-up）",
        "design": "観察研究（高齢ガン患者、phase angle × muscle strength・QOL・mortality）",
        "url": "https://pubmed.ncbi.nlm.nih.gov/25499428/",
        "tags": ["phase angle", "cancer", "mortality", "QOL"],
        "summary": "高齢ガン患者で phase angle が muscle strength・QOL・mortality を強く予測することを実証した foundational paper。Phase angle の clinical utility を multi-outcome で確立。Yujiの研究で「ガン患者 sub-population」への展開 reference。",
        "overview": "**背景**：ガン患者の phase angle は cachexia 評価との関連で注目されていた。**方法**：高齢ガン患者で phase angle と複数 outcome を評価。**結果**：低 phase angle で muscle strength 低下、QOL 低下、mortality 上昇。Cachexia の clinical screening tool として確立。**結論**：phase angle はガン患者の universal prognostic indicator。",
        "importance": "Yuji の研究で multi-disease application の reference。",
        "originality": "ガン × phase angle × multi-outcome の同時評価。",
        "discovery": "①低 phase angle で muscle strength 低下、②QOL 低下、③mortality 上昇、④cachexia screening tool、⑤universal prognostic indicator、⑥multi-outcome の同時評価。",
        "methodology": "観察、特定 disease cohort。",
        "limitation": "ガン患者限定、外挿性。",
        "citation": "[introduction] 疾患患者の phase angle 予測値を論じる導入で、本論文を「ガン患者で phase angle が multi-outcome を予測する foundational paper」として引用。",
        "implication": "**Yuji の multi-disease research の reference**。",
        "idea": "**自前研究への展開**：①既存900名でガン既往別 phase angle 解析。②TMM ガンcohort 解析。③課題1 でガン既往を effect modifier。"
    },

    "20260513_wed_09": {
        "title": "Association of Bioelectrical Impedance Phase Angle with Physical Performance and Nutrient Intake of Older Adults",
        "authors": "Lim WS, Lim JP, Chew J, et al.",
        "journal": "Nutrients, 2023年",
        "design": "観察研究（高齢者、phase angle × physical performance × nutrient intake）",
        "url": "https://pubmed.ncbi.nlm.nih.gov/36986185/",
        "tags": ["phase angle", "nutrient intake", "physical performance", "PD研究関連"],
        "summary": "高齢者で phase angle が physical performance と nutrient intake と関連することを実証。Protein・vitamin D 摂取が phase angle に正の効果。Yujiの「栄養 × 筋質」研究の reference。",
        "overview": "**背景**：phase angle と栄養摂取の関連は限定的だった。**方法**：高齢者で phase angle・physical performance・dietary intake（FFQ）を評価。**結果**：高 phase angle で protein・vitamin D・magnesium 摂取が高、physical performance も高。栄養介入の potential 示唆。**結論**：phase angle は栄養状態と機能の統合指標。",
        "importance": "Yuji の栄養 × 筋質研究の reference。",
        "originality": "Nutrient intake × phase angle の体系評価。",
        "discovery": "①Protein 摂取が phase angle に正の関連、②vitamin D・magnesium も同様、③physical performance との関連、④栄養介入の potential、⑤phase angle が integrated indicator、⑥clinical practice での dietary advice 根拠。",
        "methodology": "横断観察、栄養 FFQ の限界。",
        "limitation": "横断、recall bias。",
        "citation": "[introduction] 栄養 × phase angle を論じる導入で、本論文を「protein・vitamin D 摂取と phase angle の関連を実証した規範的研究」として引用。",
        "implication": "**Yuji の栄養 × 筋質研究の reference**。",
        "idea": "**自前研究への展開**：①既存900名で栄養 × phase angle 解析。②TMM 栄養データ統合。③学振PD拡張軸として栄養介入を組込。"
    },

    "20260513_wed_10": {
        "title": "Position statement: Evidence-Based Exercise Guidelines for Sarcopenia in Older Adults: Insights from the Korean Working Group on Sarcopenia",
        "authors": "Korean Working Group on Sarcopenia",
        "journal": "Annals of Geriatric Medicine and Research, 2025年",
        "design": "ガイドライン論文（sarcopenia の運動介入推奨、エビデンス評価、Korean working group statement）",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12489597/",
        "tags": ["sarcopenia", "exercise", "guidelines", "Korean", "PD研究関連"],
        "summary": "韓国 sarcopenia working group による運動介入のエビデンスベースガイドライン。Resistance training、aerobic、combined の推奨用量と効果を体系整理。アジア人特異的データ重視。Yujiの介入研究のアジア人 specific reference。",
        "overview": "**背景**：sarcopenia 運動ガイドラインは欧米中心で、アジア人 specific は限定的だった。**方法**：systematic review でアジア人 RCT を重視評価、推奨用量と効果を統合。**結果**：RT 2-3回/週・70-80% 1RM が標準推奨、aerobic 中等度150 min/週、combined が optimal。Korean working group の統一推奨。**結論**：アジア人 specific ガイドラインの確立。",
        "importance": "Yuji の介入研究のアジア人 specific 根拠。",
        "originality": "Korean working group の系統推奨。",
        "discovery": "①RT 2-3回/週・70-80% 1RM 推奨、②aerobic 150 min/週、③combined が optimal、④アジア人特異的エビデンス重視、⑤Korean working group 統一、⑥clinical practice ガイドライン。",
        "methodology": "Guideline の包括性。",
        "limitation": "Korean cohort 中心。",
        "citation": "[introduction] アジア人 sarcopenia 運動ガイドラインを論じる導入で、本論文を「Korean working group による系統推奨（Ann Geriatr Med Res 2025）」として引用。",
        "implication": "**Yuji の課題3 介入のアジア人 specific 根拠**。",
        "idea": "**自前研究への展開**：①課題3で本ガイドラインの dose 採用。②TMM で日本人 specific replication。③学振PDで日韓 sarcopenia 比較研究。"
    },

}
